// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops
{
    /// <summary>
    /// A self-hosted KaOps agent. Creating this resource registers the agent with the control plane and returns a complete Helm values YAML and install command for deploying it in your own cluster. The `InstallValues` output is a ready-to-use values file for the `agentops-agent-base` Helm chart. Destroying the agent archives it first, then deletes it.
    /// 
    /// **Destroying this resource — and any change that forces a new one — needs the `SelfHostedAgentLifecycle` feature enabled for your AgentOps account once the agent's worker has come online.** The feature is off by default. Without it `DELETE /agents/{id}` is refused, and the provider falls back to the ungated delete, which the control plane serves only for an agent that has never heartbeated. So a registered-but-never-deployed agent destroys cleanly on any account, while one whose worker has heartbeated fails the destroy — and, because every replacement destroys before it creates, fails the replacing apply too, leaving the old agent archived and the new one uncreated. Ask Komodor support or your account admin to enable the feature before tearing down or replacing a deployed agent.
    /// </summary>
    [AgentopsResourceType("agentops:index/agent:Agent")]
    public partial class Agent : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Stable agent identifier (slug), unique within the account. Changing this forces a new agent.
        /// </summary>
        [Output("agentId")]
        public Output<string> AgentId { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Name of the LLM credential configured on the account (not the secret value).
        /// </summary>
        [Output("credentialRef")]
        public Output<string?> CredentialRef { get; private set; } = null!;

        /// <summary>
        /// Human-readable display name shown in the UI.
        /// </summary>
        [Output("displayName")]
        public Output<string?> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Helm install command returned by the API at creation time.
        /// </summary>
        [Output("installCommand")]
        public Output<string> InstallCommand { get; private set; } = null!;

        /// <summary>
        /// Complete Helm values YAML returned by the API at creation time. Contains image coordinates, agent config, control-plane URL, and the worker token. Use as `-f values.yaml` with the `agentops-agent-base` chart, passing the worker token separately via `--set-string` if desired.
        /// </summary>
        [Output("installValues")]
        public Output<string> InstallValues { get; private set; } = null!;

        /// <summary>
        /// System prompt / instructions for the agent.
        /// </summary>
        [Output("instructions")]
        public Output<string> Instructions { get; private set; } = null!;

        /// <summary>
        /// Whether the agent has been archived.
        /// </summary>
        [Output("isArchived")]
        public Output<bool> IsArchived { get; private set; } = null!;

        /// <summary>
        /// MCP gateway group to bind to this agent. Can be changed without recreating the agent. Left unmanaged while unset: a group bound outside Terraform is not adopted into state. Once set, the binding is reconciled on every plan, so unbinding it out of band plans a re-bind.
        /// </summary>
        [Output("mcpGroupId")]
        public Output<string?> McpGroupId { get; private set; } = null!;

        /// <summary>
        /// LLM model the agent uses (e.g. `claude-opus-4-8`).
        /// </summary>
        [Output("model")]
        public Output<string?> Model { get; private set; } = null!;

        /// <summary>
        /// Display name as reported by the API.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Agent status (`Online`, `Offline`, `Archived`, etc.).
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Masked hint of the worker token (e.g. `wt_abc1...`).
        /// </summary>
        [Output("workerTokenHint")]
        public Output<string> WorkerTokenHint { get; private set; } = null!;


        /// <summary>
        /// Create a Agent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Agent(string name, AgentArgs args, CustomResourceOptions? options = null)
            : base("agentops:index/agent:Agent", name, args ?? new AgentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Agent(string name, Input<string> id, AgentState? state = null, CustomResourceOptions? options = null)
            : base("agentops:index/agent:Agent", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "installValues",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Agent resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Agent Get(string name, Input<string> id, AgentState? state = null, CustomResourceOptions? options = null)
        {
            return new Agent(name, id, state, options);
        }
    }

    public sealed class AgentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Stable agent identifier (slug), unique within the account. Changing this forces a new agent.
        /// </summary>
        [Input("agentId", required: true)]
        public Input<string> AgentId { get; set; } = null!;

        /// <summary>
        /// Name of the LLM credential configured on the account (not the secret value).
        /// </summary>
        [Input("credentialRef")]
        public Input<string>? CredentialRef { get; set; }

        /// <summary>
        /// Human-readable display name shown in the UI.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// System prompt / instructions for the agent.
        /// </summary>
        [Input("instructions", required: true)]
        public Input<string> Instructions { get; set; } = null!;

        /// <summary>
        /// MCP gateway group to bind to this agent. Can be changed without recreating the agent. Left unmanaged while unset: a group bound outside Terraform is not adopted into state. Once set, the binding is reconciled on every plan, so unbinding it out of band plans a re-bind.
        /// </summary>
        [Input("mcpGroupId")]
        public Input<string>? McpGroupId { get; set; }

        /// <summary>
        /// LLM model the agent uses (e.g. `claude-opus-4-8`).
        /// </summary>
        [Input("model")]
        public Input<string>? Model { get; set; }

        public AgentArgs()
        {
        }
        public static new AgentArgs Empty => new AgentArgs();
    }

    public sealed class AgentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Stable agent identifier (slug), unique within the account. Changing this forces a new agent.
        /// </summary>
        [Input("agentId")]
        public Input<string>? AgentId { get; set; }

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Name of the LLM credential configured on the account (not the secret value).
        /// </summary>
        [Input("credentialRef")]
        public Input<string>? CredentialRef { get; set; }

        /// <summary>
        /// Human-readable display name shown in the UI.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Helm install command returned by the API at creation time.
        /// </summary>
        [Input("installCommand")]
        public Input<string>? InstallCommand { get; set; }

        [Input("installValues")]
        private Input<string>? _installValues;

        /// <summary>
        /// Complete Helm values YAML returned by the API at creation time. Contains image coordinates, agent config, control-plane URL, and the worker token. Use as `-f values.yaml` with the `agentops-agent-base` chart, passing the worker token separately via `--set-string` if desired.
        /// </summary>
        public Input<string>? InstallValues
        {
            get => _installValues;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _installValues = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// System prompt / instructions for the agent.
        /// </summary>
        [Input("instructions")]
        public Input<string>? Instructions { get; set; }

        /// <summary>
        /// Whether the agent has been archived.
        /// </summary>
        [Input("isArchived")]
        public Input<bool>? IsArchived { get; set; }

        /// <summary>
        /// MCP gateway group to bind to this agent. Can be changed without recreating the agent. Left unmanaged while unset: a group bound outside Terraform is not adopted into state. Once set, the binding is reconciled on every plan, so unbinding it out of band plans a re-bind.
        /// </summary>
        [Input("mcpGroupId")]
        public Input<string>? McpGroupId { get; set; }

        /// <summary>
        /// LLM model the agent uses (e.g. `claude-opus-4-8`).
        /// </summary>
        [Input("model")]
        public Input<string>? Model { get; set; }

        /// <summary>
        /// Display name as reported by the API.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Agent status (`Online`, `Offline`, `Archived`, etc.).
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Masked hint of the worker token (e.g. `wt_abc1...`).
        /// </summary>
        [Input("workerTokenHint")]
        public Input<string>? WorkerTokenHint { get; set; }

        public AgentState()
        {
        }
        public static new AgentState Empty => new AgentState();
    }
}
