// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops
{
    public static class GetOutpostInstall
    {
        /// <summary>
        /// Install information for an outpost — Helm chart coordinates, values YAML, and install/upgrade commands.
        /// </summary>
        public static Task<GetOutpostInstallResult> InvokeAsync(GetOutpostInstallArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetOutpostInstallResult>("agentops:index/getOutpostInstall:getOutpostInstall", args ?? new GetOutpostInstallArgs(), options.WithDefaults());

        /// <summary>
        /// Install information for an outpost — Helm chart coordinates, values YAML, and install/upgrade commands.
        /// </summary>
        public static Output<GetOutpostInstallResult> Invoke(GetOutpostInstallInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetOutpostInstallResult>("agentops:index/getOutpostInstall:getOutpostInstall", args ?? new GetOutpostInstallInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Install information for an outpost — Helm chart coordinates, values YAML, and install/upgrade commands.
        /// </summary>
        public static Output<GetOutpostInstallResult> Invoke(GetOutpostInstallInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetOutpostInstallResult>("agentops:index/getOutpostInstall:getOutpostInstall", args ?? new GetOutpostInstallInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetOutpostInstallArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The outpost to get install info for.
        /// </summary>
        [Input("outpostId", required: true)]
        public string OutpostId { get; set; } = null!;

        public GetOutpostInstallArgs()
        {
        }
        public static new GetOutpostInstallArgs Empty => new GetOutpostInstallArgs();
    }

    public sealed class GetOutpostInstallInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The outpost to get install info for.
        /// </summary>
        [Input("outpostId", required: true)]
        public Input<string> OutpostId { get; set; } = null!;

        public GetOutpostInstallInvokeArgs()
        {
        }
        public static new GetOutpostInstallInvokeArgs Empty => new GetOutpostInstallInvokeArgs();
    }


    [OutputType]
    public sealed class GetOutpostInstallResult
    {
        /// <summary>
        /// Helm chart reference.
        /// </summary>
        public readonly string Chart;
        /// <summary>
        /// Helm install command.
        /// </summary>
        public readonly string Command;
        /// <summary>
        /// Key within the credential secret.
        /// </summary>
        public readonly string CredentialSecretKey;
        /// <summary>
        /// Name of the Kubernetes secret holding credentials.
        /// </summary>
        public readonly string CredentialSecretName;
        /// <summary>
        /// Kubernetes namespace for the release.
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// The outpost to get install info for.
        /// </summary>
        public readonly string OutpostId;
        /// <summary>
        /// Helm release name.
        /// </summary>
        public readonly string ReleaseName;
        /// <summary>
        /// Helm upgrade command.
        /// </summary>
        public readonly string UpgradeCommand;
        /// <summary>
        /// Helm values YAML for upgrade.
        /// </summary>
        public readonly string UpgradeValues;
        /// <summary>
        /// Helm values YAML for initial install.
        /// </summary>
        public readonly string Values;

        [OutputConstructor]
        private GetOutpostInstallResult(
            string chart,

            string command,

            string credentialSecretKey,

            string credentialSecretName,

            string @namespace,

            string outpostId,

            string releaseName,

            string upgradeCommand,

            string upgradeValues,

            string values)
        {
            Chart = chart;
            Command = command;
            CredentialSecretKey = credentialSecretKey;
            CredentialSecretName = credentialSecretName;
            Namespace = @namespace;
            OutpostId = outpostId;
            ReleaseName = releaseName;
            UpgradeCommand = upgradeCommand;
            UpgradeValues = upgradeValues;
            Values = values;
        }
    }
}
