// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops
{
    public static class GetReviewers
    {
        /// <summary>
        /// The reviewer agents available to this account, including built-in reviewers, for use in `agentops_review_workflow.reviewer_agent_ids`.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Agentops = Pulumi.Agentops;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Agentops.GetReviewers.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetReviewersResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetReviewersResult>("agentops:index/getReviewers:getReviewers", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// The reviewer agents available to this account, including built-in reviewers, for use in `agentops_review_workflow.reviewer_agent_ids`.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Agentops = Pulumi.Agentops;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Agentops.GetReviewers.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetReviewersResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetReviewersResult>("agentops:index/getReviewers:getReviewers", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// The reviewer agents available to this account, including built-in reviewers, for use in `agentops_review_workflow.reviewer_agent_ids`.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Agentops = Pulumi.Agentops;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Agentops.GetReviewers.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetReviewersResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetReviewersResult>("agentops:index/getReviewers:getReviewers", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetReviewersResult
    {
        /// <summary>
        /// Available reviewer agents.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetReviewersReviewerResult> Reviewers;

        [OutputConstructor]
        private GetReviewersResult(ImmutableArray<Outputs.GetReviewersReviewerResult> reviewers)
        {
            Reviewers = reviewers;
        }
    }
}
