// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops
{
    /// <summary>
    /// An outpost that proxies agent traffic from a remote network.
    /// </summary>
    [AgentopsResourceType("agentops:index/outpost:Outpost")]
    public partial class Outpost : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Upstream endpoints the outpost is allowed to reach. Replaced wholesale on every apply: removing the blocks (or setting `allowlist = []`) clears the allowlist, which leaves the outpost able to reach nothing.
        /// </summary>
        [Output("allowlists")]
        public Output<ImmutableArray<Outputs.OutpostAllowlist>> Allowlists { get; private set; } = null!;

        /// <summary>
        /// Whether the outpost is currently connected.
        /// </summary>
        [Output("connected")]
        public Output<bool> Connected { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Enrollment credential returned once at creation. Never returned on subsequent reads.
        /// </summary>
        [Output("credential")]
        public Output<string> Credential { get; private set; } = null!;

        /// <summary>
        /// Safe-to-display hint for the credential.
        /// </summary>
        [Output("credentialHint")]
        public Output<string> CredentialHint { get; private set; } = null!;

        /// <summary>
        /// Free-form description. Removing it from config clears the stored description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Arbitrary key/value labels. Replaced wholesale on every apply: removing the map (or setting `labels = {}`) clears them.
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// Human-readable outpost name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Enrollment status (`PENDING`, `ENROLLED`).
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Last-update timestamp.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a Outpost resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Outpost(string name, OutpostArgs? args = null, CustomResourceOptions? options = null)
            : base("agentops:index/outpost:Outpost", name, args ?? new OutpostArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Outpost(string name, Input<string> id, OutpostState? state = null, CustomResourceOptions? options = null)
            : base("agentops:index/outpost:Outpost", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "credential",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Outpost resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Outpost Get(string name, Input<string> id, OutpostState? state = null, CustomResourceOptions? options = null)
        {
            return new Outpost(name, id, state, options);
        }
    }

    public sealed class OutpostArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowlists")]
        private InputList<Inputs.OutpostAllowlistArgs>? _allowlists;

        /// <summary>
        /// Upstream endpoints the outpost is allowed to reach. Replaced wholesale on every apply: removing the blocks (or setting `allowlist = []`) clears the allowlist, which leaves the outpost able to reach nothing.
        /// </summary>
        public InputList<Inputs.OutpostAllowlistArgs> Allowlists
        {
            get => _allowlists ?? (_allowlists = new InputList<Inputs.OutpostAllowlistArgs>());
            set => _allowlists = value;
        }

        /// <summary>
        /// Free-form description. Removing it from config clears the stored description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Arbitrary key/value labels. Replaced wholesale on every apply: removing the map (or setting `labels = {}`) clears them.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Human-readable outpost name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public OutpostArgs()
        {
        }
        public static new OutpostArgs Empty => new OutpostArgs();
    }

    public sealed class OutpostState : global::Pulumi.ResourceArgs
    {
        [Input("allowlists")]
        private InputList<Inputs.OutpostAllowlistGetArgs>? _allowlists;

        /// <summary>
        /// Upstream endpoints the outpost is allowed to reach. Replaced wholesale on every apply: removing the blocks (or setting `allowlist = []`) clears the allowlist, which leaves the outpost able to reach nothing.
        /// </summary>
        public InputList<Inputs.OutpostAllowlistGetArgs> Allowlists
        {
            get => _allowlists ?? (_allowlists = new InputList<Inputs.OutpostAllowlistGetArgs>());
            set => _allowlists = value;
        }

        /// <summary>
        /// Whether the outpost is currently connected.
        /// </summary>
        [Input("connected")]
        public Input<bool>? Connected { get; set; }

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("credential")]
        private Input<string>? _credential;

        /// <summary>
        /// Enrollment credential returned once at creation. Never returned on subsequent reads.
        /// </summary>
        public Input<string>? Credential
        {
            get => _credential;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _credential = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Safe-to-display hint for the credential.
        /// </summary>
        [Input("credentialHint")]
        public Input<string>? CredentialHint { get; set; }

        /// <summary>
        /// Free-form description. Removing it from config clears the stored description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Arbitrary key/value labels. Replaced wholesale on every apply: removing the map (or setting `labels = {}`) clears them.
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Human-readable outpost name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Enrollment status (`PENDING`, `ENROLLED`).
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Last-update timestamp.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public OutpostState()
        {
        }
        public static new OutpostState Empty => new OutpostState();
    }
}
