// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops
{
    /// <summary>
    /// A webhook trigger that fires a target agent or workflow when called.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Agentops = Pulumi.Agentops;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // A webhook trigger that invokes an agent when called.
    ///     var deploy = new Agentops.Trigger("deploy", new()
    ///     {
    ///         Name = "deploy-webhook",
    ///         Description = "Fires the deploy agent on inbound webhooks",
    ///         TargetId = "agent_01hxyz",
    ///         TargetType = "agent",
    ///         IsEnabled = true,
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["deployTriggerToken"] = deploy.Token,
    ///     };
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// Triggers are imported by their id.
    /// 
    /// ```sh
    /// $ pulumi import agentops:index/trigger:Trigger deploy trg_01hxyz
    /// ```
    /// </summary>
    [AgentopsResourceType("agentops:index/trigger:Trigger")]
    public partial class Trigger : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Free-form description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Name of the HTTP header carrying the signature. Server-assigned when omitted.
        /// </summary>
        [Output("header")]
        public Output<string> Header { get; private set; } = null!;

        /// <summary>
        /// Whether the trigger is active. Defaults to `True`.
        /// </summary>
        [Output("isEnabled")]
        public Output<bool> IsEnabled { get; private set; } = null!;

        /// <summary>
        /// Human-readable trigger name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// ID of a credential used to sign/verify webhook payloads.
        /// </summary>
        [Output("signingCredentialId")]
        public Output<string> SigningCredentialId { get; private set; } = null!;

        /// <summary>
        /// Inline signing secret. Write-only; never returned by the API.
        /// </summary>
        [Output("signingSecret")]
        public Output<string?> SigningSecret { get; private set; } = null!;

        /// <summary>
        /// ID of the agent or workflow this trigger invokes. Omit (together with `TargetType`) to create a standalone webhook endpoint with no target — e.g. an endpoint an incident pipeline consumes. Changing this forces a new trigger.
        /// </summary>
        [Output("targetId")]
        public Output<string?> TargetId { get; private set; } = null!;

        /// <summary>
        /// Kind of target (e.g. `Agent`, `Workflow`). Omit together with `TargetId` for a standalone webhook endpoint. Changing this forces a new trigger.
        /// </summary>
        [Output("targetType")]
        public Output<string?> TargetType { get; private set; } = null!;

        /// <summary>
        /// Webhook invocation token. Returned only at create and on rotation.
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        /// <summary>
        /// Last-update timestamp.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Webhook payload type. Defaults to the server's choice when omitted.
        /// </summary>
        [Output("webhookType")]
        public Output<string> WebhookType { get; private set; } = null!;


        /// <summary>
        /// Create a Trigger resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Trigger(string name, TriggerArgs? args = null, CustomResourceOptions? options = null)
            : base("agentops:index/trigger:Trigger", name, args ?? new TriggerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Trigger(string name, Input<string> id, TriggerState? state = null, CustomResourceOptions? options = null)
            : base("agentops:index/trigger:Trigger", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "signingSecret",
                    "token",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Trigger resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Trigger Get(string name, Input<string> id, TriggerState? state = null, CustomResourceOptions? options = null)
        {
            return new Trigger(name, id, state, options);
        }
    }

    public sealed class TriggerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Free-form description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Name of the HTTP header carrying the signature. Server-assigned when omitted.
        /// </summary>
        [Input("header")]
        public Input<string>? Header { get; set; }

        /// <summary>
        /// Whether the trigger is active. Defaults to `True`.
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        /// <summary>
        /// Human-readable trigger name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of a credential used to sign/verify webhook payloads.
        /// </summary>
        [Input("signingCredentialId")]
        public Input<string>? SigningCredentialId { get; set; }

        [Input("signingSecret")]
        private Input<string>? _signingSecret;

        /// <summary>
        /// Inline signing secret. Write-only; never returned by the API.
        /// </summary>
        public Input<string>? SigningSecret
        {
            get => _signingSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _signingSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// ID of the agent or workflow this trigger invokes. Omit (together with `TargetType`) to create a standalone webhook endpoint with no target — e.g. an endpoint an incident pipeline consumes. Changing this forces a new trigger.
        /// </summary>
        [Input("targetId")]
        public Input<string>? TargetId { get; set; }

        /// <summary>
        /// Kind of target (e.g. `Agent`, `Workflow`). Omit together with `TargetId` for a standalone webhook endpoint. Changing this forces a new trigger.
        /// </summary>
        [Input("targetType")]
        public Input<string>? TargetType { get; set; }

        /// <summary>
        /// Webhook payload type. Defaults to the server's choice when omitted.
        /// </summary>
        [Input("webhookType")]
        public Input<string>? WebhookType { get; set; }

        public TriggerArgs()
        {
        }
        public static new TriggerArgs Empty => new TriggerArgs();
    }

    public sealed class TriggerState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Free-form description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Name of the HTTP header carrying the signature. Server-assigned when omitted.
        /// </summary>
        [Input("header")]
        public Input<string>? Header { get; set; }

        /// <summary>
        /// Whether the trigger is active. Defaults to `True`.
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        /// <summary>
        /// Human-readable trigger name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of a credential used to sign/verify webhook payloads.
        /// </summary>
        [Input("signingCredentialId")]
        public Input<string>? SigningCredentialId { get; set; }

        [Input("signingSecret")]
        private Input<string>? _signingSecret;

        /// <summary>
        /// Inline signing secret. Write-only; never returned by the API.
        /// </summary>
        public Input<string>? SigningSecret
        {
            get => _signingSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _signingSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// ID of the agent or workflow this trigger invokes. Omit (together with `TargetType`) to create a standalone webhook endpoint with no target — e.g. an endpoint an incident pipeline consumes. Changing this forces a new trigger.
        /// </summary>
        [Input("targetId")]
        public Input<string>? TargetId { get; set; }

        /// <summary>
        /// Kind of target (e.g. `Agent`, `Workflow`). Omit together with `TargetId` for a standalone webhook endpoint. Changing this forces a new trigger.
        /// </summary>
        [Input("targetType")]
        public Input<string>? TargetType { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Webhook invocation token. Returned only at create and on rotation.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Last-update timestamp.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Webhook payload type. Defaults to the server's choice when omitted.
        /// </summary>
        [Input("webhookType")]
        public Input<string>? WebhookType { get; set; }

        public TriggerState()
        {
        }
        public static new TriggerState Empty => new TriggerState();
    }
}
