// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Outputs
{

    [OutputType]
    public sealed class GetIntegrationCatalogEntryResult
    {
        /// <summary>
        /// Auth configuration key.
        /// </summary>
        public readonly string AuthConfigKey;
        /// <summary>
        /// Authentication mode.
        /// </summary>
        public readonly string AuthMode;
        /// <summary>
        /// Whether the integration is available.
        /// </summary>
        public readonly bool Available;
        /// <summary>
        /// Capabilities the integration provides.
        /// </summary>
        public readonly ImmutableArray<string> Capabilities;
        /// <summary>
        /// Category.
        /// </summary>
        public readonly string Category;
        /// <summary>
        /// Description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Documentation URL.
        /// </summary>
        public readonly string DocsUrl;
        /// <summary>
        /// Logo URL.
        /// </summary>
        public readonly string LogoUrl;
        /// <summary>
        /// Display name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Integration provider key.
        /// </summary>
        public readonly string Provider;

        [OutputConstructor]
        private GetIntegrationCatalogEntryResult(
            string authConfigKey,

            string authMode,

            bool available,

            ImmutableArray<string> capabilities,

            string category,

            string description,

            string docsUrl,

            string logoUrl,

            string name,

            string provider)
        {
            AuthConfigKey = authConfigKey;
            AuthMode = authMode;
            Available = available;
            Capabilities = capabilities;
            Category = category;
            Description = description;
            DocsUrl = docsUrl;
            LogoUrl = logoUrl;
            Name = name;
            Provider = provider;
        }
    }
}
