// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Outputs
{

    [OutputType]
    public sealed class GetResourceTypesResourceTypeResult
    {
        /// <summary>
        /// The resource type key.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Notes describing the resource type.
        /// </summary>
        public readonly string Notes;
        /// <summary>
        /// The scope of the resource type.
        /// </summary>
        public readonly string Scope;

        [OutputConstructor]
        private GetResourceTypesResourceTypeResult(
            string key,

            string notes,

            string scope)
        {
            Key = key;
            Notes = notes;
            Scope = scope;
        }
    }
}
