// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Outputs
{

    [OutputType]
    public sealed class HostedAgentImage
    {
        /// <summary>
        /// Image pull policy.
        /// </summary>
        public readonly string? PullPolicy;
        /// <summary>
        /// Image registry host.
        /// </summary>
        public readonly string? Registry;
        /// <summary>
        /// Image repository.
        /// </summary>
        public readonly string? Repository;
        /// <summary>
        /// Image tag.
        /// </summary>
        public readonly string? Tag;

        [OutputConstructor]
        private HostedAgentImage(
            string? pullPolicy,

            string? registry,

            string? repository,

            string? tag)
        {
            PullPolicy = pullPolicy;
            Registry = registry;
            Repository = repository;
            Tag = tag;
        }
    }
}
