// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Outputs
{

    [OutputType]
    public sealed class IncidentPipelineSpecialistBinding
    {
        /// <summary>
        /// ID of the specialist agent.
        /// </summary>
        public readonly string AgentId;
        /// <summary>
        /// Whether the specialist is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Role the specialist plays in the pipeline.
        /// </summary>
        public readonly string Role;

        [OutputConstructor]
        private IncidentPipelineSpecialistBinding(
            string agentId,

            bool enabled,

            string role)
        {
            AgentId = agentId;
            Enabled = enabled;
            Role = role;
        }
    }
}
