// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Outputs
{

    [OutputType]
    public sealed class ReviewWorkflowRepoStatus
    {
        /// <summary>
        /// GitHub webhook ID, when provisioned.
        /// </summary>
        public readonly int? GithubHookId;
        /// <summary>
        /// GitHub repository name.
        /// </summary>
        public readonly string? RepoName;
        /// <summary>
        /// GitHub repository owner.
        /// </summary>
        public readonly string? RepoOwner;
        /// <summary>
        /// Webhook provisioning error, when failed.
        /// </summary>
        public readonly string? WebhookError;
        /// <summary>
        /// Webhook provisioning status.
        /// </summary>
        public readonly string? WebhookStatus;

        [OutputConstructor]
        private ReviewWorkflowRepoStatus(
            int? githubHookId,

            string? repoName,

            string? repoOwner,

            string? webhookError,

            string? webhookStatus)
        {
            GithubHookId = githubHookId;
            RepoName = repoName;
            RepoOwner = repoOwner;
            WebhookError = webhookError;
            WebhookStatus = webhookStatus;
        }
    }
}
