// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"errors"
	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A notification channel that delivers agent events to an external destination (e.g. Slack). Routes are managed with `ChannelRoute`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"encoding/json"
//
//	"github.com/komodorio/pulumi-agentops/sdk/go/agentops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tmpJSON0, err := json.Marshal(map[string]string{
//				"default_channel": "C0123456789",
//			})
//			if err != nil {
//				return err
//			}
//			json0 := string(tmpJSON0)
//			_, err = agentops.NewChannel(ctx, "alerts", &agentops.ChannelArgs{
//				ChannelProvider: pulumi.String("slack"),
//				Connector:       pulumi.String("bot"),
//				DisplayName:     pulumi.String("prod-alerts"),
//				AppToken:        pulumi.Any(slackBotToken),
//				Config:          pulumi.String(json0),
//				Labels: pulumi.StringMap{
//					"env": pulumi.String("production"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Channels are imported by their id.
//
// ```sh
// $ pulumi import agentops:index/channel:Channel alerts chn_01hxyz
// ```
type Channel struct {
	pulumi.CustomResourceState

	// Account that owns the channel.
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// Provider app/bot token. Write-only; never returned by the API.
	AppToken pulumi.StringPtrOutput `pulumi:"appToken"`
	// Provider-reported capabilities, as a JSON object.
	CapabilitiesJson pulumi.StringOutput `pulumi:"capabilitiesJson"`
	// Channel provider (e.g. `slack`). Named `channelProvider` because `provider` is a reserved Terraform argument. Changing this forces a new channel.
	ChannelProvider pulumi.StringOutput `pulumi:"channelProvider"`
	// Provider-specific configuration, as a JSON object.
	Config pulumi.StringOutput `pulumi:"config"`
	// Connector kind within the provider. Changing this forces a new channel.
	Connector pulumi.StringOutput `pulumi:"connector"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Principal that created the channel.
	CreatedBy pulumi.StringOutput `pulumi:"createdBy"`
	// Human-readable channel name.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// External identifier for the channel in the provider. Changing this forces a new channel.
	ExternalId pulumi.StringOutput `pulumi:"externalId"`
	// ID of the integration connection backing this channel. Changing this forces a new channel.
	IntegrationId pulumi.StringOutput `pulumi:"integrationId"`
	// Arbitrary key/value labels applied to the channel.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Timestamp of the last event delivered through the channel.
	LastEventAt pulumi.StringOutput `pulumi:"lastEventAt"`
	// URL-safe channel slug.
	Slug pulumi.StringOutput `pulumi:"slug"`
	// Delivery status. Set to `paused` to suspend delivery or `active` to resume it.
	Status pulumi.StringOutput `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewChannel registers a new resource with the given unique name, arguments, and options.
func NewChannel(ctx *pulumi.Context,
	name string, args *ChannelArgs, opts ...pulumi.ResourceOption) (*Channel, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ChannelProvider == nil {
		return nil, errors.New("invalid value for required argument 'ChannelProvider'")
	}
	if args.Connector == nil {
		return nil, errors.New("invalid value for required argument 'Connector'")
	}
	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	if args.AppToken != nil {
		args.AppToken = pulumi.ToSecret(args.AppToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"appToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Channel
	err := ctx.RegisterResource("agentops:index/channel:Channel", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetChannel gets an existing Channel resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetChannel(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ChannelState, opts ...pulumi.ResourceOption) (*Channel, error) {
	var resource Channel
	err := ctx.ReadResource("agentops:index/channel:Channel", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Channel resources.
type channelState struct {
	// Account that owns the channel.
	AccountId *string `pulumi:"accountId"`
	// Provider app/bot token. Write-only; never returned by the API.
	AppToken *string `pulumi:"appToken"`
	// Provider-reported capabilities, as a JSON object.
	CapabilitiesJson *string `pulumi:"capabilitiesJson"`
	// Channel provider (e.g. `slack`). Named `channelProvider` because `provider` is a reserved Terraform argument. Changing this forces a new channel.
	ChannelProvider *string `pulumi:"channelProvider"`
	// Provider-specific configuration, as a JSON object.
	Config *string `pulumi:"config"`
	// Connector kind within the provider. Changing this forces a new channel.
	Connector *string `pulumi:"connector"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Principal that created the channel.
	CreatedBy *string `pulumi:"createdBy"`
	// Human-readable channel name.
	DisplayName *string `pulumi:"displayName"`
	// External identifier for the channel in the provider. Changing this forces a new channel.
	ExternalId *string `pulumi:"externalId"`
	// ID of the integration connection backing this channel. Changing this forces a new channel.
	IntegrationId *string `pulumi:"integrationId"`
	// Arbitrary key/value labels applied to the channel.
	Labels map[string]string `pulumi:"labels"`
	// Timestamp of the last event delivered through the channel.
	LastEventAt *string `pulumi:"lastEventAt"`
	// URL-safe channel slug.
	Slug *string `pulumi:"slug"`
	// Delivery status. Set to `paused` to suspend delivery or `active` to resume it.
	Status *string `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type ChannelState struct {
	// Account that owns the channel.
	AccountId pulumi.StringPtrInput
	// Provider app/bot token. Write-only; never returned by the API.
	AppToken pulumi.StringPtrInput
	// Provider-reported capabilities, as a JSON object.
	CapabilitiesJson pulumi.StringPtrInput
	// Channel provider (e.g. `slack`). Named `channelProvider` because `provider` is a reserved Terraform argument. Changing this forces a new channel.
	ChannelProvider pulumi.StringPtrInput
	// Provider-specific configuration, as a JSON object.
	Config pulumi.StringPtrInput
	// Connector kind within the provider. Changing this forces a new channel.
	Connector pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Principal that created the channel.
	CreatedBy pulumi.StringPtrInput
	// Human-readable channel name.
	DisplayName pulumi.StringPtrInput
	// External identifier for the channel in the provider. Changing this forces a new channel.
	ExternalId pulumi.StringPtrInput
	// ID of the integration connection backing this channel. Changing this forces a new channel.
	IntegrationId pulumi.StringPtrInput
	// Arbitrary key/value labels applied to the channel.
	Labels pulumi.StringMapInput
	// Timestamp of the last event delivered through the channel.
	LastEventAt pulumi.StringPtrInput
	// URL-safe channel slug.
	Slug pulumi.StringPtrInput
	// Delivery status. Set to `paused` to suspend delivery or `active` to resume it.
	Status pulumi.StringPtrInput
	// Last-update timestamp.
	UpdatedAt pulumi.StringPtrInput
}

func (ChannelState) ElementType() reflect.Type {
	return reflect.TypeOf((*channelState)(nil)).Elem()
}

type channelArgs struct {
	// Provider app/bot token. Write-only; never returned by the API.
	AppToken *string `pulumi:"appToken"`
	// Channel provider (e.g. `slack`). Named `channelProvider` because `provider` is a reserved Terraform argument. Changing this forces a new channel.
	ChannelProvider string `pulumi:"channelProvider"`
	// Provider-specific configuration, as a JSON object.
	Config *string `pulumi:"config"`
	// Connector kind within the provider. Changing this forces a new channel.
	Connector string `pulumi:"connector"`
	// Human-readable channel name.
	DisplayName string `pulumi:"displayName"`
	// External identifier for the channel in the provider. Changing this forces a new channel.
	ExternalId *string `pulumi:"externalId"`
	// ID of the integration connection backing this channel. Changing this forces a new channel.
	IntegrationId *string `pulumi:"integrationId"`
	// Arbitrary key/value labels applied to the channel.
	Labels map[string]string `pulumi:"labels"`
	// Delivery status. Set to `paused` to suspend delivery or `active` to resume it.
	Status *string `pulumi:"status"`
}

// The set of arguments for constructing a Channel resource.
type ChannelArgs struct {
	// Provider app/bot token. Write-only; never returned by the API.
	AppToken pulumi.StringPtrInput
	// Channel provider (e.g. `slack`). Named `channelProvider` because `provider` is a reserved Terraform argument. Changing this forces a new channel.
	ChannelProvider pulumi.StringInput
	// Provider-specific configuration, as a JSON object.
	Config pulumi.StringPtrInput
	// Connector kind within the provider. Changing this forces a new channel.
	Connector pulumi.StringInput
	// Human-readable channel name.
	DisplayName pulumi.StringInput
	// External identifier for the channel in the provider. Changing this forces a new channel.
	ExternalId pulumi.StringPtrInput
	// ID of the integration connection backing this channel. Changing this forces a new channel.
	IntegrationId pulumi.StringPtrInput
	// Arbitrary key/value labels applied to the channel.
	Labels pulumi.StringMapInput
	// Delivery status. Set to `paused` to suspend delivery or `active` to resume it.
	Status pulumi.StringPtrInput
}

func (ChannelArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*channelArgs)(nil)).Elem()
}

type ChannelInput interface {
	pulumi.Input

	ToChannelOutput() ChannelOutput
	ToChannelOutputWithContext(ctx context.Context) ChannelOutput
}

func (*Channel) ElementType() reflect.Type {
	return reflect.TypeOf((**Channel)(nil)).Elem()
}

func (i *Channel) ToChannelOutput() ChannelOutput {
	return i.ToChannelOutputWithContext(context.Background())
}

func (i *Channel) ToChannelOutputWithContext(ctx context.Context) ChannelOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ChannelOutput)
}

// ChannelArrayInput is an input type that accepts ChannelArray and ChannelArrayOutput values.
// You can construct a concrete instance of `ChannelArrayInput` via:
//
//	ChannelArray{ ChannelArgs{...} }
type ChannelArrayInput interface {
	pulumi.Input

	ToChannelArrayOutput() ChannelArrayOutput
	ToChannelArrayOutputWithContext(context.Context) ChannelArrayOutput
}

type ChannelArray []ChannelInput

func (ChannelArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Channel)(nil)).Elem()
}

func (i ChannelArray) ToChannelArrayOutput() ChannelArrayOutput {
	return i.ToChannelArrayOutputWithContext(context.Background())
}

func (i ChannelArray) ToChannelArrayOutputWithContext(ctx context.Context) ChannelArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ChannelArrayOutput)
}

// ChannelMapInput is an input type that accepts ChannelMap and ChannelMapOutput values.
// You can construct a concrete instance of `ChannelMapInput` via:
//
//	ChannelMap{ "key": ChannelArgs{...} }
type ChannelMapInput interface {
	pulumi.Input

	ToChannelMapOutput() ChannelMapOutput
	ToChannelMapOutputWithContext(context.Context) ChannelMapOutput
}

type ChannelMap map[string]ChannelInput

func (ChannelMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Channel)(nil)).Elem()
}

func (i ChannelMap) ToChannelMapOutput() ChannelMapOutput {
	return i.ToChannelMapOutputWithContext(context.Background())
}

func (i ChannelMap) ToChannelMapOutputWithContext(ctx context.Context) ChannelMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ChannelMapOutput)
}

type ChannelOutput struct{ *pulumi.OutputState }

func (ChannelOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Channel)(nil)).Elem()
}

func (o ChannelOutput) ToChannelOutput() ChannelOutput {
	return o
}

func (o ChannelOutput) ToChannelOutputWithContext(ctx context.Context) ChannelOutput {
	return o
}

// Account that owns the channel.
func (o ChannelOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// Provider app/bot token. Write-only; never returned by the API.
func (o ChannelOutput) AppToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringPtrOutput { return v.AppToken }).(pulumi.StringPtrOutput)
}

// Provider-reported capabilities, as a JSON object.
func (o ChannelOutput) CapabilitiesJson() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.CapabilitiesJson }).(pulumi.StringOutput)
}

// Channel provider (e.g. `slack`). Named `channelProvider` because `provider` is a reserved Terraform argument. Changing this forces a new channel.
func (o ChannelOutput) ChannelProvider() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.ChannelProvider }).(pulumi.StringOutput)
}

// Provider-specific configuration, as a JSON object.
func (o ChannelOutput) Config() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.Config }).(pulumi.StringOutput)
}

// Connector kind within the provider. Changing this forces a new channel.
func (o ChannelOutput) Connector() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.Connector }).(pulumi.StringOutput)
}

// Creation timestamp.
func (o ChannelOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Principal that created the channel.
func (o ChannelOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.CreatedBy }).(pulumi.StringOutput)
}

// Human-readable channel name.
func (o ChannelOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// External identifier for the channel in the provider. Changing this forces a new channel.
func (o ChannelOutput) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.ExternalId }).(pulumi.StringOutput)
}

// ID of the integration connection backing this channel. Changing this forces a new channel.
func (o ChannelOutput) IntegrationId() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.IntegrationId }).(pulumi.StringOutput)
}

// Arbitrary key/value labels applied to the channel.
func (o ChannelOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Timestamp of the last event delivered through the channel.
func (o ChannelOutput) LastEventAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.LastEventAt }).(pulumi.StringOutput)
}

// URL-safe channel slug.
func (o ChannelOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.Slug }).(pulumi.StringOutput)
}

// Delivery status. Set to `paused` to suspend delivery or `active` to resume it.
func (o ChannelOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Last-update timestamp.
func (o ChannelOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Channel) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type ChannelArrayOutput struct{ *pulumi.OutputState }

func (ChannelArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Channel)(nil)).Elem()
}

func (o ChannelArrayOutput) ToChannelArrayOutput() ChannelArrayOutput {
	return o
}

func (o ChannelArrayOutput) ToChannelArrayOutputWithContext(ctx context.Context) ChannelArrayOutput {
	return o
}

func (o ChannelArrayOutput) Index(i pulumi.IntInput) ChannelOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Channel {
		return vs[0].([]*Channel)[vs[1].(int)]
	}).(ChannelOutput)
}

type ChannelMapOutput struct{ *pulumi.OutputState }

func (ChannelMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Channel)(nil)).Elem()
}

func (o ChannelMapOutput) ToChannelMapOutput() ChannelMapOutput {
	return o
}

func (o ChannelMapOutput) ToChannelMapOutputWithContext(ctx context.Context) ChannelMapOutput {
	return o
}

func (o ChannelMapOutput) MapIndex(k pulumi.StringInput) ChannelOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Channel {
		return vs[0].(map[string]*Channel)[vs[1].(string)]
	}).(ChannelOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ChannelInput)(nil)).Elem(), &Channel{})
	pulumi.RegisterInputType(reflect.TypeOf((*ChannelArrayInput)(nil)).Elem(), ChannelArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ChannelMapInput)(nil)).Elem(), ChannelMap{})
	pulumi.RegisterOutputType(ChannelOutput{})
	pulumi.RegisterOutputType(ChannelArrayOutput{})
	pulumi.RegisterOutputType(ChannelMapOutput{})
}
