// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"errors"
	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Binds a credential to an agent. This association has no update endpoint, so changing any argument forces a new binding.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/komodorio/pulumi-agentops/sdk/go/agentops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Bind a credential to an agent so the agent can use it.
//			_, err := agentops.NewCredentialBinding(ctx, "openai_to_agent", &agentops.CredentialBindingArgs{
//				CredentialId: pulumi.Any(openai.Id),
//				AgentId:      pulumi.String("agent_01hxyz"),
//				OnDemand:     pulumi.Bool(false),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Bindings are imported by "<credential_id>/<agent_id>".
//
// ```sh
// $ pulumi import agentops:index/credentialBinding:CredentialBinding openai_to_agent cred_01hxyz/agent_01hxyz
// ```
type CredentialBinding struct {
	pulumi.CustomResourceState

	// ID of the agent to bind the credential to. Changing this forces a new binding.
	AgentId pulumi.StringOutput `pulumi:"agentId"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// ID of the credential to bind. Changing this forces a new binding.
	CredentialId pulumi.StringOutput `pulumi:"credentialId"`
	// Whether the credential is supplied on demand rather than pre-attached. Changing this forces a new binding.
	OnDemand pulumi.BoolOutput `pulumi:"onDemand"`
}

// NewCredentialBinding registers a new resource with the given unique name, arguments, and options.
func NewCredentialBinding(ctx *pulumi.Context,
	name string, args *CredentialBindingArgs, opts ...pulumi.ResourceOption) (*CredentialBinding, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AgentId == nil {
		return nil, errors.New("invalid value for required argument 'AgentId'")
	}
	if args.CredentialId == nil {
		return nil, errors.New("invalid value for required argument 'CredentialId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CredentialBinding
	err := ctx.RegisterResource("agentops:index/credentialBinding:CredentialBinding", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCredentialBinding gets an existing CredentialBinding resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCredentialBinding(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CredentialBindingState, opts ...pulumi.ResourceOption) (*CredentialBinding, error) {
	var resource CredentialBinding
	err := ctx.ReadResource("agentops:index/credentialBinding:CredentialBinding", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CredentialBinding resources.
type credentialBindingState struct {
	// ID of the agent to bind the credential to. Changing this forces a new binding.
	AgentId *string `pulumi:"agentId"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// ID of the credential to bind. Changing this forces a new binding.
	CredentialId *string `pulumi:"credentialId"`
	// Whether the credential is supplied on demand rather than pre-attached. Changing this forces a new binding.
	OnDemand *bool `pulumi:"onDemand"`
}

type CredentialBindingState struct {
	// ID of the agent to bind the credential to. Changing this forces a new binding.
	AgentId pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// ID of the credential to bind. Changing this forces a new binding.
	CredentialId pulumi.StringPtrInput
	// Whether the credential is supplied on demand rather than pre-attached. Changing this forces a new binding.
	OnDemand pulumi.BoolPtrInput
}

func (CredentialBindingState) ElementType() reflect.Type {
	return reflect.TypeOf((*credentialBindingState)(nil)).Elem()
}

type credentialBindingArgs struct {
	// ID of the agent to bind the credential to. Changing this forces a new binding.
	AgentId string `pulumi:"agentId"`
	// ID of the credential to bind. Changing this forces a new binding.
	CredentialId string `pulumi:"credentialId"`
	// Whether the credential is supplied on demand rather than pre-attached. Changing this forces a new binding.
	OnDemand *bool `pulumi:"onDemand"`
}

// The set of arguments for constructing a CredentialBinding resource.
type CredentialBindingArgs struct {
	// ID of the agent to bind the credential to. Changing this forces a new binding.
	AgentId pulumi.StringInput
	// ID of the credential to bind. Changing this forces a new binding.
	CredentialId pulumi.StringInput
	// Whether the credential is supplied on demand rather than pre-attached. Changing this forces a new binding.
	OnDemand pulumi.BoolPtrInput
}

func (CredentialBindingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*credentialBindingArgs)(nil)).Elem()
}

type CredentialBindingInput interface {
	pulumi.Input

	ToCredentialBindingOutput() CredentialBindingOutput
	ToCredentialBindingOutputWithContext(ctx context.Context) CredentialBindingOutput
}

func (*CredentialBinding) ElementType() reflect.Type {
	return reflect.TypeOf((**CredentialBinding)(nil)).Elem()
}

func (i *CredentialBinding) ToCredentialBindingOutput() CredentialBindingOutput {
	return i.ToCredentialBindingOutputWithContext(context.Background())
}

func (i *CredentialBinding) ToCredentialBindingOutputWithContext(ctx context.Context) CredentialBindingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CredentialBindingOutput)
}

// CredentialBindingArrayInput is an input type that accepts CredentialBindingArray and CredentialBindingArrayOutput values.
// You can construct a concrete instance of `CredentialBindingArrayInput` via:
//
//	CredentialBindingArray{ CredentialBindingArgs{...} }
type CredentialBindingArrayInput interface {
	pulumi.Input

	ToCredentialBindingArrayOutput() CredentialBindingArrayOutput
	ToCredentialBindingArrayOutputWithContext(context.Context) CredentialBindingArrayOutput
}

type CredentialBindingArray []CredentialBindingInput

func (CredentialBindingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CredentialBinding)(nil)).Elem()
}

func (i CredentialBindingArray) ToCredentialBindingArrayOutput() CredentialBindingArrayOutput {
	return i.ToCredentialBindingArrayOutputWithContext(context.Background())
}

func (i CredentialBindingArray) ToCredentialBindingArrayOutputWithContext(ctx context.Context) CredentialBindingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CredentialBindingArrayOutput)
}

// CredentialBindingMapInput is an input type that accepts CredentialBindingMap and CredentialBindingMapOutput values.
// You can construct a concrete instance of `CredentialBindingMapInput` via:
//
//	CredentialBindingMap{ "key": CredentialBindingArgs{...} }
type CredentialBindingMapInput interface {
	pulumi.Input

	ToCredentialBindingMapOutput() CredentialBindingMapOutput
	ToCredentialBindingMapOutputWithContext(context.Context) CredentialBindingMapOutput
}

type CredentialBindingMap map[string]CredentialBindingInput

func (CredentialBindingMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CredentialBinding)(nil)).Elem()
}

func (i CredentialBindingMap) ToCredentialBindingMapOutput() CredentialBindingMapOutput {
	return i.ToCredentialBindingMapOutputWithContext(context.Background())
}

func (i CredentialBindingMap) ToCredentialBindingMapOutputWithContext(ctx context.Context) CredentialBindingMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CredentialBindingMapOutput)
}

type CredentialBindingOutput struct{ *pulumi.OutputState }

func (CredentialBindingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CredentialBinding)(nil)).Elem()
}

func (o CredentialBindingOutput) ToCredentialBindingOutput() CredentialBindingOutput {
	return o
}

func (o CredentialBindingOutput) ToCredentialBindingOutputWithContext(ctx context.Context) CredentialBindingOutput {
	return o
}

// ID of the agent to bind the credential to. Changing this forces a new binding.
func (o CredentialBindingOutput) AgentId() pulumi.StringOutput {
	return o.ApplyT(func(v *CredentialBinding) pulumi.StringOutput { return v.AgentId }).(pulumi.StringOutput)
}

// Creation timestamp.
func (o CredentialBindingOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *CredentialBinding) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// ID of the credential to bind. Changing this forces a new binding.
func (o CredentialBindingOutput) CredentialId() pulumi.StringOutput {
	return o.ApplyT(func(v *CredentialBinding) pulumi.StringOutput { return v.CredentialId }).(pulumi.StringOutput)
}

// Whether the credential is supplied on demand rather than pre-attached. Changing this forces a new binding.
func (o CredentialBindingOutput) OnDemand() pulumi.BoolOutput {
	return o.ApplyT(func(v *CredentialBinding) pulumi.BoolOutput { return v.OnDemand }).(pulumi.BoolOutput)
}

type CredentialBindingArrayOutput struct{ *pulumi.OutputState }

func (CredentialBindingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CredentialBinding)(nil)).Elem()
}

func (o CredentialBindingArrayOutput) ToCredentialBindingArrayOutput() CredentialBindingArrayOutput {
	return o
}

func (o CredentialBindingArrayOutput) ToCredentialBindingArrayOutputWithContext(ctx context.Context) CredentialBindingArrayOutput {
	return o
}

func (o CredentialBindingArrayOutput) Index(i pulumi.IntInput) CredentialBindingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CredentialBinding {
		return vs[0].([]*CredentialBinding)[vs[1].(int)]
	}).(CredentialBindingOutput)
}

type CredentialBindingMapOutput struct{ *pulumi.OutputState }

func (CredentialBindingMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CredentialBinding)(nil)).Elem()
}

func (o CredentialBindingMapOutput) ToCredentialBindingMapOutput() CredentialBindingMapOutput {
	return o
}

func (o CredentialBindingMapOutput) ToCredentialBindingMapOutputWithContext(ctx context.Context) CredentialBindingMapOutput {
	return o
}

func (o CredentialBindingMapOutput) MapIndex(k pulumi.StringInput) CredentialBindingOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CredentialBinding {
		return vs[0].(map[string]*CredentialBinding)[vs[1].(string)]
	}).(CredentialBindingOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CredentialBindingInput)(nil)).Elem(), &CredentialBinding{})
	pulumi.RegisterInputType(reflect.TypeOf((*CredentialBindingArrayInput)(nil)).Elem(), CredentialBindingArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CredentialBindingMapInput)(nil)).Elem(), CredentialBindingMap{})
	pulumi.RegisterOutputType(CredentialBindingOutput{})
	pulumi.RegisterOutputType(CredentialBindingArrayOutput{})
	pulumi.RegisterOutputType(CredentialBindingMapOutput{})
}
