// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"errors"
	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A stored credential whose secret value is managed out-of-band. The value is write-only and never returned by the API; changing it replaces the credential's secret in place.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/komodorio/pulumi-agentops/sdk/go/agentops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := agentops.NewCredential(ctx, "openai", &agentops.CredentialArgs{
//				Name:        pulumi.String("openai-api-key"),
//				Value:       pulumi.Any(openaiApiKey),
//				Description: pulumi.String("OpenAI API key for agents"),
//				Labels: pulumi.StringMap{
//					"team": pulumi.String("platform"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Credentials are imported by their id.
//
// ```sh
// $ pulumi import agentops:index/credential:Credential openai cred_01hxyz
// ```
type Credential struct {
	pulumi.CustomResourceState

	// Currently active secret version.
	ActiveVersion pulumi.IntOutput `pulumi:"activeVersion"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Free-form description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Arbitrary key/value labels.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Timestamp of the last value replacement.
	LastReplacedAt pulumi.StringOutput `pulumi:"lastReplacedAt"`
	// Timestamp the credential was last used.
	LastUsedAt pulumi.StringOutput `pulumi:"lastUsedAt"`
	// Human-readable credential name. Changing this forces a new credential.
	Name pulumi.StringOutput `pulumi:"name"`
	// Owner of the credential.
	Owner pulumi.StringPtrOutput `pulumi:"owner"`
	// Credential status. Server-assigned when omitted.
	Status pulumi.StringOutput `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The secret value. Write-only; never returned by the API. Changing it replaces the stored secret.
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewCredential registers a new resource with the given unique name, arguments, and options.
func NewCredential(ctx *pulumi.Context,
	name string, args *CredentialArgs, opts ...pulumi.ResourceOption) (*Credential, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	if args.Value != nil {
		args.Value = pulumi.ToSecret(args.Value).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"value",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Credential
	err := ctx.RegisterResource("agentops:index/credential:Credential", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCredential gets an existing Credential resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCredential(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CredentialState, opts ...pulumi.ResourceOption) (*Credential, error) {
	var resource Credential
	err := ctx.ReadResource("agentops:index/credential:Credential", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Credential resources.
type credentialState struct {
	// Currently active secret version.
	ActiveVersion *int `pulumi:"activeVersion"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Free-form description.
	Description *string `pulumi:"description"`
	// Arbitrary key/value labels.
	Labels map[string]string `pulumi:"labels"`
	// Timestamp of the last value replacement.
	LastReplacedAt *string `pulumi:"lastReplacedAt"`
	// Timestamp the credential was last used.
	LastUsedAt *string `pulumi:"lastUsedAt"`
	// Human-readable credential name. Changing this forces a new credential.
	Name *string `pulumi:"name"`
	// Owner of the credential.
	Owner *string `pulumi:"owner"`
	// Credential status. Server-assigned when omitted.
	Status *string `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
	// The secret value. Write-only; never returned by the API. Changing it replaces the stored secret.
	Value *string `pulumi:"value"`
}

type CredentialState struct {
	// Currently active secret version.
	ActiveVersion pulumi.IntPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Free-form description.
	Description pulumi.StringPtrInput
	// Arbitrary key/value labels.
	Labels pulumi.StringMapInput
	// Timestamp of the last value replacement.
	LastReplacedAt pulumi.StringPtrInput
	// Timestamp the credential was last used.
	LastUsedAt pulumi.StringPtrInput
	// Human-readable credential name. Changing this forces a new credential.
	Name pulumi.StringPtrInput
	// Owner of the credential.
	Owner pulumi.StringPtrInput
	// Credential status. Server-assigned when omitted.
	Status pulumi.StringPtrInput
	// Last-update timestamp.
	UpdatedAt pulumi.StringPtrInput
	// The secret value. Write-only; never returned by the API. Changing it replaces the stored secret.
	Value pulumi.StringPtrInput
}

func (CredentialState) ElementType() reflect.Type {
	return reflect.TypeOf((*credentialState)(nil)).Elem()
}

type credentialArgs struct {
	// Free-form description.
	Description *string `pulumi:"description"`
	// Arbitrary key/value labels.
	Labels map[string]string `pulumi:"labels"`
	// Human-readable credential name. Changing this forces a new credential.
	Name *string `pulumi:"name"`
	// Owner of the credential.
	Owner *string `pulumi:"owner"`
	// Credential status. Server-assigned when omitted.
	Status *string `pulumi:"status"`
	// The secret value. Write-only; never returned by the API. Changing it replaces the stored secret.
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a Credential resource.
type CredentialArgs struct {
	// Free-form description.
	Description pulumi.StringPtrInput
	// Arbitrary key/value labels.
	Labels pulumi.StringMapInput
	// Human-readable credential name. Changing this forces a new credential.
	Name pulumi.StringPtrInput
	// Owner of the credential.
	Owner pulumi.StringPtrInput
	// Credential status. Server-assigned when omitted.
	Status pulumi.StringPtrInput
	// The secret value. Write-only; never returned by the API. Changing it replaces the stored secret.
	Value pulumi.StringInput
}

func (CredentialArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*credentialArgs)(nil)).Elem()
}

type CredentialInput interface {
	pulumi.Input

	ToCredentialOutput() CredentialOutput
	ToCredentialOutputWithContext(ctx context.Context) CredentialOutput
}

func (*Credential) ElementType() reflect.Type {
	return reflect.TypeOf((**Credential)(nil)).Elem()
}

func (i *Credential) ToCredentialOutput() CredentialOutput {
	return i.ToCredentialOutputWithContext(context.Background())
}

func (i *Credential) ToCredentialOutputWithContext(ctx context.Context) CredentialOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CredentialOutput)
}

// CredentialArrayInput is an input type that accepts CredentialArray and CredentialArrayOutput values.
// You can construct a concrete instance of `CredentialArrayInput` via:
//
//	CredentialArray{ CredentialArgs{...} }
type CredentialArrayInput interface {
	pulumi.Input

	ToCredentialArrayOutput() CredentialArrayOutput
	ToCredentialArrayOutputWithContext(context.Context) CredentialArrayOutput
}

type CredentialArray []CredentialInput

func (CredentialArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Credential)(nil)).Elem()
}

func (i CredentialArray) ToCredentialArrayOutput() CredentialArrayOutput {
	return i.ToCredentialArrayOutputWithContext(context.Background())
}

func (i CredentialArray) ToCredentialArrayOutputWithContext(ctx context.Context) CredentialArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CredentialArrayOutput)
}

// CredentialMapInput is an input type that accepts CredentialMap and CredentialMapOutput values.
// You can construct a concrete instance of `CredentialMapInput` via:
//
//	CredentialMap{ "key": CredentialArgs{...} }
type CredentialMapInput interface {
	pulumi.Input

	ToCredentialMapOutput() CredentialMapOutput
	ToCredentialMapOutputWithContext(context.Context) CredentialMapOutput
}

type CredentialMap map[string]CredentialInput

func (CredentialMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Credential)(nil)).Elem()
}

func (i CredentialMap) ToCredentialMapOutput() CredentialMapOutput {
	return i.ToCredentialMapOutputWithContext(context.Background())
}

func (i CredentialMap) ToCredentialMapOutputWithContext(ctx context.Context) CredentialMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CredentialMapOutput)
}

type CredentialOutput struct{ *pulumi.OutputState }

func (CredentialOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Credential)(nil)).Elem()
}

func (o CredentialOutput) ToCredentialOutput() CredentialOutput {
	return o
}

func (o CredentialOutput) ToCredentialOutputWithContext(ctx context.Context) CredentialOutput {
	return o
}

// Currently active secret version.
func (o CredentialOutput) ActiveVersion() pulumi.IntOutput {
	return o.ApplyT(func(v *Credential) pulumi.IntOutput { return v.ActiveVersion }).(pulumi.IntOutput)
}

// Creation timestamp.
func (o CredentialOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Free-form description.
func (o CredentialOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Arbitrary key/value labels.
func (o CredentialOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Timestamp of the last value replacement.
func (o CredentialOutput) LastReplacedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringOutput { return v.LastReplacedAt }).(pulumi.StringOutput)
}

// Timestamp the credential was last used.
func (o CredentialOutput) LastUsedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringOutput { return v.LastUsedAt }).(pulumi.StringOutput)
}

// Human-readable credential name. Changing this forces a new credential.
func (o CredentialOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Owner of the credential.
func (o CredentialOutput) Owner() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringPtrOutput { return v.Owner }).(pulumi.StringPtrOutput)
}

// Credential status. Server-assigned when omitted.
func (o CredentialOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Last-update timestamp.
func (o CredentialOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The secret value. Write-only; never returned by the API. Changing it replaces the stored secret.
func (o CredentialOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *Credential) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

type CredentialArrayOutput struct{ *pulumi.OutputState }

func (CredentialArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Credential)(nil)).Elem()
}

func (o CredentialArrayOutput) ToCredentialArrayOutput() CredentialArrayOutput {
	return o
}

func (o CredentialArrayOutput) ToCredentialArrayOutputWithContext(ctx context.Context) CredentialArrayOutput {
	return o
}

func (o CredentialArrayOutput) Index(i pulumi.IntInput) CredentialOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Credential {
		return vs[0].([]*Credential)[vs[1].(int)]
	}).(CredentialOutput)
}

type CredentialMapOutput struct{ *pulumi.OutputState }

func (CredentialMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Credential)(nil)).Elem()
}

func (o CredentialMapOutput) ToCredentialMapOutput() CredentialMapOutput {
	return o
}

func (o CredentialMapOutput) ToCredentialMapOutputWithContext(ctx context.Context) CredentialMapOutput {
	return o
}

func (o CredentialMapOutput) MapIndex(k pulumi.StringInput) CredentialOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Credential {
		return vs[0].(map[string]*Credential)[vs[1].(string)]
	}).(CredentialOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CredentialInput)(nil)).Elem(), &Credential{})
	pulumi.RegisterInputType(reflect.TypeOf((*CredentialArrayInput)(nil)).Elem(), CredentialArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CredentialMapInput)(nil)).Elem(), CredentialMap{})
	pulumi.RegisterOutputType(CredentialOutput{})
	pulumi.RegisterOutputType(CredentialArrayOutput{})
	pulumi.RegisterOutputType(CredentialMapOutput{})
}
