// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The catalog of hosted worker agents available to this account.
//
// ## Example Usage
func GetWorkerCatalog(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetWorkerCatalogResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetWorkerCatalogResult
	err := ctx.Invoke("agentops:index/getWorkerCatalog:getWorkerCatalog", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getWorkerCatalog.
type GetWorkerCatalogResult struct {
	// Available worker catalog entries.
	Entries []GetWorkerCatalogEntry `pulumi:"entries"`
}

func GetWorkerCatalogOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetWorkerCatalogResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("agentops:index/getWorkerCatalog:getWorkerCatalog", nil, GetWorkerCatalogResultOutput{}, options).(GetWorkerCatalogResultOutput)
}

// A collection of values returned by getWorkerCatalog.
type GetWorkerCatalogResultOutput struct{ *pulumi.OutputState }

func (GetWorkerCatalogResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWorkerCatalogResult)(nil)).Elem()
}

func (o GetWorkerCatalogResultOutput) ToGetWorkerCatalogResultOutput() GetWorkerCatalogResultOutput {
	return o
}

func (o GetWorkerCatalogResultOutput) ToGetWorkerCatalogResultOutputWithContext(ctx context.Context) GetWorkerCatalogResultOutput {
	return o
}

// Available worker catalog entries.
func (o GetWorkerCatalogResultOutput) Entries() GetWorkerCatalogEntryArrayOutput {
	return o.ApplyT(func(v GetWorkerCatalogResult) []GetWorkerCatalogEntry { return v.Entries }).(GetWorkerCatalogEntryArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetWorkerCatalogResultOutput{})
}
