// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"errors"
	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An authorization grant: binds a subject to a capability or role over a resource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"encoding/json"
//
//	"github.com/komodorio/pulumi-agentops/sdk/go/agentops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tmpJSON0, err := json.Marshal(map[string]string{
//				"id":   "prn_01hxyz",
//				"kind": "principal",
//			})
//			if err != nil {
//				return err
//			}
//			json0 := string(tmpJSON0)
//			_, err = agentops.NewGrant(ctx, "sre_deployer", &agentops.GrantArgs{
//				GrantKind:    pulumi.String("role"),
//				RoleId:       pulumi.Any(deployer.Id),
//				ResourceType: pulumi.String("agent"),
//				ResourceId:   pulumi.String("*"),
//				Subject:      pulumi.String(json0),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Grants are imported by their id.
//
// ```sh
// $ pulumi import agentops:index/grant:Grant sre_deployer grant_01hxyz
// ```
type Grant struct {
	pulumi.CustomResourceState

	// Capability granted (when grantKind is "capability").
	Capability pulumi.StringOutput `pulumi:"capability"`
	// Timestamp the grant was created (server-derived).
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Free-form grant description.
	Description pulumi.StringOutput `pulumi:"description"`
	// Optional expiry timestamp for the grant.
	ExpiresAt pulumi.StringOutput `pulumi:"expiresAt"`
	// Kind of grant, one of "capability" or "role".
	GrantKind pulumi.StringOutput `pulumi:"grantKind"`
	// Policy the grant references (when applicable).
	PolicyId pulumi.StringOutput `pulumi:"policyId"`
	// Identifier of the resource the grant applies to.
	ResourceId pulumi.StringOutput `pulumi:"resourceId"`
	// Type of the resource the grant applies to.
	ResourceType pulumi.StringOutput `pulumi:"resourceType"`
	// Role granted (when grantKind is "role").
	RoleId pulumi.StringOutput `pulumi:"roleId"`
	// Optional attribute selector, encoded as JSON.
	Selector pulumi.StringOutput `pulumi:"selector"`
	// Subject the grant is bound to, encoded as JSON (id and kind).
	Subject pulumi.StringOutput `pulumi:"subject"`
}

// NewGrant registers a new resource with the given unique name, arguments, and options.
func NewGrant(ctx *pulumi.Context,
	name string, args *GrantArgs, opts ...pulumi.ResourceOption) (*Grant, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.GrantKind == nil {
		return nil, errors.New("invalid value for required argument 'GrantKind'")
	}
	if args.ResourceId == nil {
		return nil, errors.New("invalid value for required argument 'ResourceId'")
	}
	if args.ResourceType == nil {
		return nil, errors.New("invalid value for required argument 'ResourceType'")
	}
	if args.Subject == nil {
		return nil, errors.New("invalid value for required argument 'Subject'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Grant
	err := ctx.RegisterResource("agentops:index/grant:Grant", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGrant gets an existing Grant resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGrant(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GrantState, opts ...pulumi.ResourceOption) (*Grant, error) {
	var resource Grant
	err := ctx.ReadResource("agentops:index/grant:Grant", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Grant resources.
type grantState struct {
	// Capability granted (when grantKind is "capability").
	Capability *string `pulumi:"capability"`
	// Timestamp the grant was created (server-derived).
	CreatedAt *string `pulumi:"createdAt"`
	// Free-form grant description.
	Description *string `pulumi:"description"`
	// Optional expiry timestamp for the grant.
	ExpiresAt *string `pulumi:"expiresAt"`
	// Kind of grant, one of "capability" or "role".
	GrantKind *string `pulumi:"grantKind"`
	// Policy the grant references (when applicable).
	PolicyId *string `pulumi:"policyId"`
	// Identifier of the resource the grant applies to.
	ResourceId *string `pulumi:"resourceId"`
	// Type of the resource the grant applies to.
	ResourceType *string `pulumi:"resourceType"`
	// Role granted (when grantKind is "role").
	RoleId *string `pulumi:"roleId"`
	// Optional attribute selector, encoded as JSON.
	Selector *string `pulumi:"selector"`
	// Subject the grant is bound to, encoded as JSON (id and kind).
	Subject *string `pulumi:"subject"`
}

type GrantState struct {
	// Capability granted (when grantKind is "capability").
	Capability pulumi.StringPtrInput
	// Timestamp the grant was created (server-derived).
	CreatedAt pulumi.StringPtrInput
	// Free-form grant description.
	Description pulumi.StringPtrInput
	// Optional expiry timestamp for the grant.
	ExpiresAt pulumi.StringPtrInput
	// Kind of grant, one of "capability" or "role".
	GrantKind pulumi.StringPtrInput
	// Policy the grant references (when applicable).
	PolicyId pulumi.StringPtrInput
	// Identifier of the resource the grant applies to.
	ResourceId pulumi.StringPtrInput
	// Type of the resource the grant applies to.
	ResourceType pulumi.StringPtrInput
	// Role granted (when grantKind is "role").
	RoleId pulumi.StringPtrInput
	// Optional attribute selector, encoded as JSON.
	Selector pulumi.StringPtrInput
	// Subject the grant is bound to, encoded as JSON (id and kind).
	Subject pulumi.StringPtrInput
}

func (GrantState) ElementType() reflect.Type {
	return reflect.TypeOf((*grantState)(nil)).Elem()
}

type grantArgs struct {
	// Capability granted (when grantKind is "capability").
	Capability *string `pulumi:"capability"`
	// Free-form grant description.
	Description *string `pulumi:"description"`
	// Optional expiry timestamp for the grant.
	ExpiresAt *string `pulumi:"expiresAt"`
	// Kind of grant, one of "capability" or "role".
	GrantKind string `pulumi:"grantKind"`
	// Policy the grant references (when applicable).
	PolicyId *string `pulumi:"policyId"`
	// Identifier of the resource the grant applies to.
	ResourceId string `pulumi:"resourceId"`
	// Type of the resource the grant applies to.
	ResourceType string `pulumi:"resourceType"`
	// Role granted (when grantKind is "role").
	RoleId *string `pulumi:"roleId"`
	// Optional attribute selector, encoded as JSON.
	Selector *string `pulumi:"selector"`
	// Subject the grant is bound to, encoded as JSON (id and kind).
	Subject string `pulumi:"subject"`
}

// The set of arguments for constructing a Grant resource.
type GrantArgs struct {
	// Capability granted (when grantKind is "capability").
	Capability pulumi.StringPtrInput
	// Free-form grant description.
	Description pulumi.StringPtrInput
	// Optional expiry timestamp for the grant.
	ExpiresAt pulumi.StringPtrInput
	// Kind of grant, one of "capability" or "role".
	GrantKind pulumi.StringInput
	// Policy the grant references (when applicable).
	PolicyId pulumi.StringPtrInput
	// Identifier of the resource the grant applies to.
	ResourceId pulumi.StringInput
	// Type of the resource the grant applies to.
	ResourceType pulumi.StringInput
	// Role granted (when grantKind is "role").
	RoleId pulumi.StringPtrInput
	// Optional attribute selector, encoded as JSON.
	Selector pulumi.StringPtrInput
	// Subject the grant is bound to, encoded as JSON (id and kind).
	Subject pulumi.StringInput
}

func (GrantArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*grantArgs)(nil)).Elem()
}

type GrantInput interface {
	pulumi.Input

	ToGrantOutput() GrantOutput
	ToGrantOutputWithContext(ctx context.Context) GrantOutput
}

func (*Grant) ElementType() reflect.Type {
	return reflect.TypeOf((**Grant)(nil)).Elem()
}

func (i *Grant) ToGrantOutput() GrantOutput {
	return i.ToGrantOutputWithContext(context.Background())
}

func (i *Grant) ToGrantOutputWithContext(ctx context.Context) GrantOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GrantOutput)
}

// GrantArrayInput is an input type that accepts GrantArray and GrantArrayOutput values.
// You can construct a concrete instance of `GrantArrayInput` via:
//
//	GrantArray{ GrantArgs{...} }
type GrantArrayInput interface {
	pulumi.Input

	ToGrantArrayOutput() GrantArrayOutput
	ToGrantArrayOutputWithContext(context.Context) GrantArrayOutput
}

type GrantArray []GrantInput

func (GrantArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Grant)(nil)).Elem()
}

func (i GrantArray) ToGrantArrayOutput() GrantArrayOutput {
	return i.ToGrantArrayOutputWithContext(context.Background())
}

func (i GrantArray) ToGrantArrayOutputWithContext(ctx context.Context) GrantArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GrantArrayOutput)
}

// GrantMapInput is an input type that accepts GrantMap and GrantMapOutput values.
// You can construct a concrete instance of `GrantMapInput` via:
//
//	GrantMap{ "key": GrantArgs{...} }
type GrantMapInput interface {
	pulumi.Input

	ToGrantMapOutput() GrantMapOutput
	ToGrantMapOutputWithContext(context.Context) GrantMapOutput
}

type GrantMap map[string]GrantInput

func (GrantMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Grant)(nil)).Elem()
}

func (i GrantMap) ToGrantMapOutput() GrantMapOutput {
	return i.ToGrantMapOutputWithContext(context.Background())
}

func (i GrantMap) ToGrantMapOutputWithContext(ctx context.Context) GrantMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GrantMapOutput)
}

type GrantOutput struct{ *pulumi.OutputState }

func (GrantOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Grant)(nil)).Elem()
}

func (o GrantOutput) ToGrantOutput() GrantOutput {
	return o
}

func (o GrantOutput) ToGrantOutputWithContext(ctx context.Context) GrantOutput {
	return o
}

// Capability granted (when grantKind is "capability").
func (o GrantOutput) Capability() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.Capability }).(pulumi.StringOutput)
}

// Timestamp the grant was created (server-derived).
func (o GrantOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Free-form grant description.
func (o GrantOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Optional expiry timestamp for the grant.
func (o GrantOutput) ExpiresAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.ExpiresAt }).(pulumi.StringOutput)
}

// Kind of grant, one of "capability" or "role".
func (o GrantOutput) GrantKind() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.GrantKind }).(pulumi.StringOutput)
}

// Policy the grant references (when applicable).
func (o GrantOutput) PolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.PolicyId }).(pulumi.StringOutput)
}

// Identifier of the resource the grant applies to.
func (o GrantOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

// Type of the resource the grant applies to.
func (o GrantOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.ResourceType }).(pulumi.StringOutput)
}

// Role granted (when grantKind is "role").
func (o GrantOutput) RoleId() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.RoleId }).(pulumi.StringOutput)
}

// Optional attribute selector, encoded as JSON.
func (o GrantOutput) Selector() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.Selector }).(pulumi.StringOutput)
}

// Subject the grant is bound to, encoded as JSON (id and kind).
func (o GrantOutput) Subject() pulumi.StringOutput {
	return o.ApplyT(func(v *Grant) pulumi.StringOutput { return v.Subject }).(pulumi.StringOutput)
}

type GrantArrayOutput struct{ *pulumi.OutputState }

func (GrantArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Grant)(nil)).Elem()
}

func (o GrantArrayOutput) ToGrantArrayOutput() GrantArrayOutput {
	return o
}

func (o GrantArrayOutput) ToGrantArrayOutputWithContext(ctx context.Context) GrantArrayOutput {
	return o
}

func (o GrantArrayOutput) Index(i pulumi.IntInput) GrantOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Grant {
		return vs[0].([]*Grant)[vs[1].(int)]
	}).(GrantOutput)
}

type GrantMapOutput struct{ *pulumi.OutputState }

func (GrantMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Grant)(nil)).Elem()
}

func (o GrantMapOutput) ToGrantMapOutput() GrantMapOutput {
	return o
}

func (o GrantMapOutput) ToGrantMapOutputWithContext(ctx context.Context) GrantMapOutput {
	return o
}

func (o GrantMapOutput) MapIndex(k pulumi.StringInput) GrantOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Grant {
		return vs[0].(map[string]*Grant)[vs[1].(string)]
	}).(GrantOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GrantInput)(nil)).Elem(), &Grant{})
	pulumi.RegisterInputType(reflect.TypeOf((*GrantArrayInput)(nil)).Elem(), GrantArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GrantMapInput)(nil)).Elem(), GrantMap{})
	pulumi.RegisterOutputType(GrantOutput{})
	pulumi.RegisterOutputType(GrantArrayOutput{})
	pulumi.RegisterOutputType(GrantMapOutput{})
}
