// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A knowledge base that stores documents made searchable by agents.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/komodorio/pulumi-agentops/sdk/go/agentops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := agentops.NewKnowledgeBase(ctx, "runbooks", &agentops.KnowledgeBaseArgs{
//				Name:        pulumi.String("runbooks"),
//				Description: pulumi.String("Operational runbooks indexed for agents"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Knowledge bases are imported by their id.
//
// ```sh
// $ pulumi import agentops:index/knowledgeBase:KnowledgeBase runbooks kb_01hxyz
// ```
type KnowledgeBase struct {
	pulumi.CustomResourceState

	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Free-form description.
	Description pulumi.StringOutput `pulumi:"description"`
	// Number of documents stored in the knowledge base.
	DocCount pulumi.IntOutput `pulumi:"docCount"`
	// Number of documents that have been indexed.
	IndexedCount pulumi.IntOutput `pulumi:"indexedCount"`
	// Arbitrary key/value labels attached to the knowledge base.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Human-readable knowledge base name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Last-update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewKnowledgeBase registers a new resource with the given unique name, arguments, and options.
func NewKnowledgeBase(ctx *pulumi.Context,
	name string, args *KnowledgeBaseArgs, opts ...pulumi.ResourceOption) (*KnowledgeBase, error) {
	if args == nil {
		args = &KnowledgeBaseArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource KnowledgeBase
	err := ctx.RegisterResource("agentops:index/knowledgeBase:KnowledgeBase", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKnowledgeBase gets an existing KnowledgeBase resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKnowledgeBase(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KnowledgeBaseState, opts ...pulumi.ResourceOption) (*KnowledgeBase, error) {
	var resource KnowledgeBase
	err := ctx.ReadResource("agentops:index/knowledgeBase:KnowledgeBase", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering KnowledgeBase resources.
type knowledgeBaseState struct {
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Free-form description.
	Description *string `pulumi:"description"`
	// Number of documents stored in the knowledge base.
	DocCount *int `pulumi:"docCount"`
	// Number of documents that have been indexed.
	IndexedCount *int `pulumi:"indexedCount"`
	// Arbitrary key/value labels attached to the knowledge base.
	Labels map[string]string `pulumi:"labels"`
	// Human-readable knowledge base name.
	Name *string `pulumi:"name"`
	// Last-update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type KnowledgeBaseState struct {
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Free-form description.
	Description pulumi.StringPtrInput
	// Number of documents stored in the knowledge base.
	DocCount pulumi.IntPtrInput
	// Number of documents that have been indexed.
	IndexedCount pulumi.IntPtrInput
	// Arbitrary key/value labels attached to the knowledge base.
	Labels pulumi.StringMapInput
	// Human-readable knowledge base name.
	Name pulumi.StringPtrInput
	// Last-update timestamp.
	UpdatedAt pulumi.StringPtrInput
}

func (KnowledgeBaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*knowledgeBaseState)(nil)).Elem()
}

type knowledgeBaseArgs struct {
	// Free-form description.
	Description *string `pulumi:"description"`
	// Arbitrary key/value labels attached to the knowledge base.
	Labels map[string]string `pulumi:"labels"`
	// Human-readable knowledge base name.
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a KnowledgeBase resource.
type KnowledgeBaseArgs struct {
	// Free-form description.
	Description pulumi.StringPtrInput
	// Arbitrary key/value labels attached to the knowledge base.
	Labels pulumi.StringMapInput
	// Human-readable knowledge base name.
	Name pulumi.StringPtrInput
}

func (KnowledgeBaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*knowledgeBaseArgs)(nil)).Elem()
}

type KnowledgeBaseInput interface {
	pulumi.Input

	ToKnowledgeBaseOutput() KnowledgeBaseOutput
	ToKnowledgeBaseOutputWithContext(ctx context.Context) KnowledgeBaseOutput
}

func (*KnowledgeBase) ElementType() reflect.Type {
	return reflect.TypeOf((**KnowledgeBase)(nil)).Elem()
}

func (i *KnowledgeBase) ToKnowledgeBaseOutput() KnowledgeBaseOutput {
	return i.ToKnowledgeBaseOutputWithContext(context.Background())
}

func (i *KnowledgeBase) ToKnowledgeBaseOutputWithContext(ctx context.Context) KnowledgeBaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KnowledgeBaseOutput)
}

// KnowledgeBaseArrayInput is an input type that accepts KnowledgeBaseArray and KnowledgeBaseArrayOutput values.
// You can construct a concrete instance of `KnowledgeBaseArrayInput` via:
//
//	KnowledgeBaseArray{ KnowledgeBaseArgs{...} }
type KnowledgeBaseArrayInput interface {
	pulumi.Input

	ToKnowledgeBaseArrayOutput() KnowledgeBaseArrayOutput
	ToKnowledgeBaseArrayOutputWithContext(context.Context) KnowledgeBaseArrayOutput
}

type KnowledgeBaseArray []KnowledgeBaseInput

func (KnowledgeBaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KnowledgeBase)(nil)).Elem()
}

func (i KnowledgeBaseArray) ToKnowledgeBaseArrayOutput() KnowledgeBaseArrayOutput {
	return i.ToKnowledgeBaseArrayOutputWithContext(context.Background())
}

func (i KnowledgeBaseArray) ToKnowledgeBaseArrayOutputWithContext(ctx context.Context) KnowledgeBaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KnowledgeBaseArrayOutput)
}

// KnowledgeBaseMapInput is an input type that accepts KnowledgeBaseMap and KnowledgeBaseMapOutput values.
// You can construct a concrete instance of `KnowledgeBaseMapInput` via:
//
//	KnowledgeBaseMap{ "key": KnowledgeBaseArgs{...} }
type KnowledgeBaseMapInput interface {
	pulumi.Input

	ToKnowledgeBaseMapOutput() KnowledgeBaseMapOutput
	ToKnowledgeBaseMapOutputWithContext(context.Context) KnowledgeBaseMapOutput
}

type KnowledgeBaseMap map[string]KnowledgeBaseInput

func (KnowledgeBaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KnowledgeBase)(nil)).Elem()
}

func (i KnowledgeBaseMap) ToKnowledgeBaseMapOutput() KnowledgeBaseMapOutput {
	return i.ToKnowledgeBaseMapOutputWithContext(context.Background())
}

func (i KnowledgeBaseMap) ToKnowledgeBaseMapOutputWithContext(ctx context.Context) KnowledgeBaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KnowledgeBaseMapOutput)
}

type KnowledgeBaseOutput struct{ *pulumi.OutputState }

func (KnowledgeBaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KnowledgeBase)(nil)).Elem()
}

func (o KnowledgeBaseOutput) ToKnowledgeBaseOutput() KnowledgeBaseOutput {
	return o
}

func (o KnowledgeBaseOutput) ToKnowledgeBaseOutputWithContext(ctx context.Context) KnowledgeBaseOutput {
	return o
}

// Creation timestamp.
func (o KnowledgeBaseOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *KnowledgeBase) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Free-form description.
func (o KnowledgeBaseOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *KnowledgeBase) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Number of documents stored in the knowledge base.
func (o KnowledgeBaseOutput) DocCount() pulumi.IntOutput {
	return o.ApplyT(func(v *KnowledgeBase) pulumi.IntOutput { return v.DocCount }).(pulumi.IntOutput)
}

// Number of documents that have been indexed.
func (o KnowledgeBaseOutput) IndexedCount() pulumi.IntOutput {
	return o.ApplyT(func(v *KnowledgeBase) pulumi.IntOutput { return v.IndexedCount }).(pulumi.IntOutput)
}

// Arbitrary key/value labels attached to the knowledge base.
func (o KnowledgeBaseOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *KnowledgeBase) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Human-readable knowledge base name.
func (o KnowledgeBaseOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *KnowledgeBase) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Last-update timestamp.
func (o KnowledgeBaseOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *KnowledgeBase) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type KnowledgeBaseArrayOutput struct{ *pulumi.OutputState }

func (KnowledgeBaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KnowledgeBase)(nil)).Elem()
}

func (o KnowledgeBaseArrayOutput) ToKnowledgeBaseArrayOutput() KnowledgeBaseArrayOutput {
	return o
}

func (o KnowledgeBaseArrayOutput) ToKnowledgeBaseArrayOutputWithContext(ctx context.Context) KnowledgeBaseArrayOutput {
	return o
}

func (o KnowledgeBaseArrayOutput) Index(i pulumi.IntInput) KnowledgeBaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *KnowledgeBase {
		return vs[0].([]*KnowledgeBase)[vs[1].(int)]
	}).(KnowledgeBaseOutput)
}

type KnowledgeBaseMapOutput struct{ *pulumi.OutputState }

func (KnowledgeBaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KnowledgeBase)(nil)).Elem()
}

func (o KnowledgeBaseMapOutput) ToKnowledgeBaseMapOutput() KnowledgeBaseMapOutput {
	return o
}

func (o KnowledgeBaseMapOutput) ToKnowledgeBaseMapOutputWithContext(ctx context.Context) KnowledgeBaseMapOutput {
	return o
}

func (o KnowledgeBaseMapOutput) MapIndex(k pulumi.StringInput) KnowledgeBaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *KnowledgeBase {
		return vs[0].(map[string]*KnowledgeBase)[vs[1].(string)]
	}).(KnowledgeBaseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KnowledgeBaseInput)(nil)).Elem(), &KnowledgeBase{})
	pulumi.RegisterInputType(reflect.TypeOf((*KnowledgeBaseArrayInput)(nil)).Elem(), KnowledgeBaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KnowledgeBaseMapInput)(nil)).Elem(), KnowledgeBaseMap{})
	pulumi.RegisterOutputType(KnowledgeBaseOutput{})
	pulumi.RegisterOutputType(KnowledgeBaseArrayOutput{})
	pulumi.RegisterOutputType(KnowledgeBaseMapOutput{})
}
