// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"errors"
	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A code-review workflow that runs reviewer agents against pull requests in one or more GitHub repositories.
//
// ## Example Usage
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Review workflows are imported by their id.
//
// ```sh
// $ pulumi import agentops:index/reviewWorkflow:ReviewWorkflow backend rvw_01hxyz
// ```
type ReviewWorkflow struct {
	pulumi.CustomResourceState

	// Only review pull requests targeting this base branch. Reviews all branches when omitted. Changing it forces a new workflow.
	BaseBranchFilter pulumi.StringPtrOutput `pulumi:"baseBranchFilter"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Manual webhook setup instructions for repositories the server could not configure automatically.
	ManualSetups ReviewWorkflowManualSetupArrayOutput `pulumi:"manualSetups"`
	// Human-readable workflow name. Server-assigned when omitted. Changing it forces a new workflow.
	Name pulumi.StringOutput `pulumi:"name"`
	// Number of repositories configured on the workflow.
	RepoCount pulumi.IntOutput `pulumi:"repoCount"`
	// Observed webhook status for each configured repository.
	RepoStatuses ReviewWorkflowRepoStatusArrayOutput `pulumi:"repoStatuses"`
	// GitHub repositories this workflow reviews. Changing them forces a new workflow.
	Repos ReviewWorkflowRepoArrayOutput `pulumi:"repos"`
	// IDs of the reviewer agents that run against matching pull requests. Changing them forces a new workflow.
	ReviewerAgentIds pulumi.StringArrayOutput `pulumi:"reviewerAgentIds"`
	// Lifecycle status. Newly created workflows start as `draft`; set to `active` or `paused` to publish or suspend the workflow. One of `draft`, `active`, `paused`.
	Status pulumi.StringOutput `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Webhook URL GitHub posts pull-request events to.
	WebhookUrl pulumi.StringOutput `pulumi:"webhookUrl"`
}

// NewReviewWorkflow registers a new resource with the given unique name, arguments, and options.
func NewReviewWorkflow(ctx *pulumi.Context,
	name string, args *ReviewWorkflowArgs, opts ...pulumi.ResourceOption) (*ReviewWorkflow, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ReviewerAgentIds == nil {
		return nil, errors.New("invalid value for required argument 'ReviewerAgentIds'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ReviewWorkflow
	err := ctx.RegisterResource("agentops:index/reviewWorkflow:ReviewWorkflow", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetReviewWorkflow gets an existing ReviewWorkflow resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetReviewWorkflow(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ReviewWorkflowState, opts ...pulumi.ResourceOption) (*ReviewWorkflow, error) {
	var resource ReviewWorkflow
	err := ctx.ReadResource("agentops:index/reviewWorkflow:ReviewWorkflow", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ReviewWorkflow resources.
type reviewWorkflowState struct {
	// Only review pull requests targeting this base branch. Reviews all branches when omitted. Changing it forces a new workflow.
	BaseBranchFilter *string `pulumi:"baseBranchFilter"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Manual webhook setup instructions for repositories the server could not configure automatically.
	ManualSetups []ReviewWorkflowManualSetup `pulumi:"manualSetups"`
	// Human-readable workflow name. Server-assigned when omitted. Changing it forces a new workflow.
	Name *string `pulumi:"name"`
	// Number of repositories configured on the workflow.
	RepoCount *int `pulumi:"repoCount"`
	// Observed webhook status for each configured repository.
	RepoStatuses []ReviewWorkflowRepoStatus `pulumi:"repoStatuses"`
	// GitHub repositories this workflow reviews. Changing them forces a new workflow.
	Repos []ReviewWorkflowRepo `pulumi:"repos"`
	// IDs of the reviewer agents that run against matching pull requests. Changing them forces a new workflow.
	ReviewerAgentIds []string `pulumi:"reviewerAgentIds"`
	// Lifecycle status. Newly created workflows start as `draft`; set to `active` or `paused` to publish or suspend the workflow. One of `draft`, `active`, `paused`.
	Status *string `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Webhook URL GitHub posts pull-request events to.
	WebhookUrl *string `pulumi:"webhookUrl"`
}

type ReviewWorkflowState struct {
	// Only review pull requests targeting this base branch. Reviews all branches when omitted. Changing it forces a new workflow.
	BaseBranchFilter pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Manual webhook setup instructions for repositories the server could not configure automatically.
	ManualSetups ReviewWorkflowManualSetupArrayInput
	// Human-readable workflow name. Server-assigned when omitted. Changing it forces a new workflow.
	Name pulumi.StringPtrInput
	// Number of repositories configured on the workflow.
	RepoCount pulumi.IntPtrInput
	// Observed webhook status for each configured repository.
	RepoStatuses ReviewWorkflowRepoStatusArrayInput
	// GitHub repositories this workflow reviews. Changing them forces a new workflow.
	Repos ReviewWorkflowRepoArrayInput
	// IDs of the reviewer agents that run against matching pull requests. Changing them forces a new workflow.
	ReviewerAgentIds pulumi.StringArrayInput
	// Lifecycle status. Newly created workflows start as `draft`; set to `active` or `paused` to publish or suspend the workflow. One of `draft`, `active`, `paused`.
	Status pulumi.StringPtrInput
	// Last-update timestamp.
	UpdatedAt pulumi.StringPtrInput
	// Webhook URL GitHub posts pull-request events to.
	WebhookUrl pulumi.StringPtrInput
}

func (ReviewWorkflowState) ElementType() reflect.Type {
	return reflect.TypeOf((*reviewWorkflowState)(nil)).Elem()
}

type reviewWorkflowArgs struct {
	// Only review pull requests targeting this base branch. Reviews all branches when omitted. Changing it forces a new workflow.
	BaseBranchFilter *string `pulumi:"baseBranchFilter"`
	// Human-readable workflow name. Server-assigned when omitted. Changing it forces a new workflow.
	Name *string `pulumi:"name"`
	// GitHub repositories this workflow reviews. Changing them forces a new workflow.
	Repos []ReviewWorkflowRepo `pulumi:"repos"`
	// IDs of the reviewer agents that run against matching pull requests. Changing them forces a new workflow.
	ReviewerAgentIds []string `pulumi:"reviewerAgentIds"`
	// Lifecycle status. Newly created workflows start as `draft`; set to `active` or `paused` to publish or suspend the workflow. One of `draft`, `active`, `paused`.
	Status *string `pulumi:"status"`
}

// The set of arguments for constructing a ReviewWorkflow resource.
type ReviewWorkflowArgs struct {
	// Only review pull requests targeting this base branch. Reviews all branches when omitted. Changing it forces a new workflow.
	BaseBranchFilter pulumi.StringPtrInput
	// Human-readable workflow name. Server-assigned when omitted. Changing it forces a new workflow.
	Name pulumi.StringPtrInput
	// GitHub repositories this workflow reviews. Changing them forces a new workflow.
	Repos ReviewWorkflowRepoArrayInput
	// IDs of the reviewer agents that run against matching pull requests. Changing them forces a new workflow.
	ReviewerAgentIds pulumi.StringArrayInput
	// Lifecycle status. Newly created workflows start as `draft`; set to `active` or `paused` to publish or suspend the workflow. One of `draft`, `active`, `paused`.
	Status pulumi.StringPtrInput
}

func (ReviewWorkflowArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*reviewWorkflowArgs)(nil)).Elem()
}

type ReviewWorkflowInput interface {
	pulumi.Input

	ToReviewWorkflowOutput() ReviewWorkflowOutput
	ToReviewWorkflowOutputWithContext(ctx context.Context) ReviewWorkflowOutput
}

func (*ReviewWorkflow) ElementType() reflect.Type {
	return reflect.TypeOf((**ReviewWorkflow)(nil)).Elem()
}

func (i *ReviewWorkflow) ToReviewWorkflowOutput() ReviewWorkflowOutput {
	return i.ToReviewWorkflowOutputWithContext(context.Background())
}

func (i *ReviewWorkflow) ToReviewWorkflowOutputWithContext(ctx context.Context) ReviewWorkflowOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReviewWorkflowOutput)
}

// ReviewWorkflowArrayInput is an input type that accepts ReviewWorkflowArray and ReviewWorkflowArrayOutput values.
// You can construct a concrete instance of `ReviewWorkflowArrayInput` via:
//
//	ReviewWorkflowArray{ ReviewWorkflowArgs{...} }
type ReviewWorkflowArrayInput interface {
	pulumi.Input

	ToReviewWorkflowArrayOutput() ReviewWorkflowArrayOutput
	ToReviewWorkflowArrayOutputWithContext(context.Context) ReviewWorkflowArrayOutput
}

type ReviewWorkflowArray []ReviewWorkflowInput

func (ReviewWorkflowArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReviewWorkflow)(nil)).Elem()
}

func (i ReviewWorkflowArray) ToReviewWorkflowArrayOutput() ReviewWorkflowArrayOutput {
	return i.ToReviewWorkflowArrayOutputWithContext(context.Background())
}

func (i ReviewWorkflowArray) ToReviewWorkflowArrayOutputWithContext(ctx context.Context) ReviewWorkflowArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReviewWorkflowArrayOutput)
}

// ReviewWorkflowMapInput is an input type that accepts ReviewWorkflowMap and ReviewWorkflowMapOutput values.
// You can construct a concrete instance of `ReviewWorkflowMapInput` via:
//
//	ReviewWorkflowMap{ "key": ReviewWorkflowArgs{...} }
type ReviewWorkflowMapInput interface {
	pulumi.Input

	ToReviewWorkflowMapOutput() ReviewWorkflowMapOutput
	ToReviewWorkflowMapOutputWithContext(context.Context) ReviewWorkflowMapOutput
}

type ReviewWorkflowMap map[string]ReviewWorkflowInput

func (ReviewWorkflowMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReviewWorkflow)(nil)).Elem()
}

func (i ReviewWorkflowMap) ToReviewWorkflowMapOutput() ReviewWorkflowMapOutput {
	return i.ToReviewWorkflowMapOutputWithContext(context.Background())
}

func (i ReviewWorkflowMap) ToReviewWorkflowMapOutputWithContext(ctx context.Context) ReviewWorkflowMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ReviewWorkflowMapOutput)
}

type ReviewWorkflowOutput struct{ *pulumi.OutputState }

func (ReviewWorkflowOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ReviewWorkflow)(nil)).Elem()
}

func (o ReviewWorkflowOutput) ToReviewWorkflowOutput() ReviewWorkflowOutput {
	return o
}

func (o ReviewWorkflowOutput) ToReviewWorkflowOutputWithContext(ctx context.Context) ReviewWorkflowOutput {
	return o
}

// Only review pull requests targeting this base branch. Reviews all branches when omitted. Changing it forces a new workflow.
func (o ReviewWorkflowOutput) BaseBranchFilter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.StringPtrOutput { return v.BaseBranchFilter }).(pulumi.StringPtrOutput)
}

// Creation timestamp.
func (o ReviewWorkflowOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Manual webhook setup instructions for repositories the server could not configure automatically.
func (o ReviewWorkflowOutput) ManualSetups() ReviewWorkflowManualSetupArrayOutput {
	return o.ApplyT(func(v *ReviewWorkflow) ReviewWorkflowManualSetupArrayOutput { return v.ManualSetups }).(ReviewWorkflowManualSetupArrayOutput)
}

// Human-readable workflow name. Server-assigned when omitted. Changing it forces a new workflow.
func (o ReviewWorkflowOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Number of repositories configured on the workflow.
func (o ReviewWorkflowOutput) RepoCount() pulumi.IntOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.IntOutput { return v.RepoCount }).(pulumi.IntOutput)
}

// Observed webhook status for each configured repository.
func (o ReviewWorkflowOutput) RepoStatuses() ReviewWorkflowRepoStatusArrayOutput {
	return o.ApplyT(func(v *ReviewWorkflow) ReviewWorkflowRepoStatusArrayOutput { return v.RepoStatuses }).(ReviewWorkflowRepoStatusArrayOutput)
}

// GitHub repositories this workflow reviews. Changing them forces a new workflow.
func (o ReviewWorkflowOutput) Repos() ReviewWorkflowRepoArrayOutput {
	return o.ApplyT(func(v *ReviewWorkflow) ReviewWorkflowRepoArrayOutput { return v.Repos }).(ReviewWorkflowRepoArrayOutput)
}

// IDs of the reviewer agents that run against matching pull requests. Changing them forces a new workflow.
func (o ReviewWorkflowOutput) ReviewerAgentIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.StringArrayOutput { return v.ReviewerAgentIds }).(pulumi.StringArrayOutput)
}

// Lifecycle status. Newly created workflows start as `draft`; set to `active` or `paused` to publish or suspend the workflow. One of `draft`, `active`, `paused`.
func (o ReviewWorkflowOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Last-update timestamp.
func (o ReviewWorkflowOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Webhook URL GitHub posts pull-request events to.
func (o ReviewWorkflowOutput) WebhookUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *ReviewWorkflow) pulumi.StringOutput { return v.WebhookUrl }).(pulumi.StringOutput)
}

type ReviewWorkflowArrayOutput struct{ *pulumi.OutputState }

func (ReviewWorkflowArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ReviewWorkflow)(nil)).Elem()
}

func (o ReviewWorkflowArrayOutput) ToReviewWorkflowArrayOutput() ReviewWorkflowArrayOutput {
	return o
}

func (o ReviewWorkflowArrayOutput) ToReviewWorkflowArrayOutputWithContext(ctx context.Context) ReviewWorkflowArrayOutput {
	return o
}

func (o ReviewWorkflowArrayOutput) Index(i pulumi.IntInput) ReviewWorkflowOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ReviewWorkflow {
		return vs[0].([]*ReviewWorkflow)[vs[1].(int)]
	}).(ReviewWorkflowOutput)
}

type ReviewWorkflowMapOutput struct{ *pulumi.OutputState }

func (ReviewWorkflowMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ReviewWorkflow)(nil)).Elem()
}

func (o ReviewWorkflowMapOutput) ToReviewWorkflowMapOutput() ReviewWorkflowMapOutput {
	return o
}

func (o ReviewWorkflowMapOutput) ToReviewWorkflowMapOutputWithContext(ctx context.Context) ReviewWorkflowMapOutput {
	return o
}

func (o ReviewWorkflowMapOutput) MapIndex(k pulumi.StringInput) ReviewWorkflowOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ReviewWorkflow {
		return vs[0].(map[string]*ReviewWorkflow)[vs[1].(string)]
	}).(ReviewWorkflowOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ReviewWorkflowInput)(nil)).Elem(), &ReviewWorkflow{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReviewWorkflowArrayInput)(nil)).Elem(), ReviewWorkflowArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ReviewWorkflowMapInput)(nil)).Elem(), ReviewWorkflowMap{})
	pulumi.RegisterOutputType(ReviewWorkflowOutput{})
	pulumi.RegisterOutputType(ReviewWorkflowArrayOutput{})
	pulumi.RegisterOutputType(ReviewWorkflowMapOutput{})
}
