// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"errors"
	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A cron schedule that periodically invokes an agent.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"encoding/json"
//
//	"github.com/komodorio/pulumi-agentops/sdk/go/agentops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			tmpJSON0, err := json.Marshal(map[string]string{
//				"mode": "full",
//			})
//			if err != nil {
//				return err
//			}
//			json0 := string(tmpJSON0)
//			_, err = agentops.NewSchedule(ctx, "nightly", &agentops.ScheduleArgs{
//				AgentId:  pulumi.String("agent_01hxyz"),
//				CronExpr: pulumi.String("0 2 * * *"),
//				Timezone: pulumi.String("UTC"),
//				Input:    pulumi.String(json0),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Schedules are imported by their id.
//
// ```sh
// $ pulumi import agentops:index/schedule:Schedule nightly sch_01hxyz
// ```
type Schedule struct {
	pulumi.CustomResourceState

	// ID of the agent this schedule invokes. Changing this forces a new schedule.
	AgentId pulumi.StringOutput `pulumi:"agentId"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Cron expression describing when the schedule fires.
	CronExpr pulumi.StringOutput `pulumi:"cronExpr"`
	// Free-form description.
	Description pulumi.StringOutput `pulumi:"description"`
	// Whether the schedule can be edited.
	Editable pulumi.BoolOutput `pulumi:"editable"`
	// Input payload passed to the agent, as a JSON object.
	Input pulumi.StringOutput `pulumi:"input"`
	// Whether the schedule is active. Defaults to `true`.
	IsEnabled pulumi.BoolOutput `pulumi:"isEnabled"`
	// Timestamp of the last time the schedule fired.
	LastFiredAt pulumi.StringOutput `pulumi:"lastFiredAt"`
	// Human-readable schedule name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Origin of the schedule.
	Source pulumi.StringOutput `pulumi:"source"`
	// Identifier of the schedule's source.
	SourceId pulumi.StringOutput `pulumi:"sourceId"`
	// IANA timezone in which the cron expression is evaluated. Server-assigned when omitted.
	Timezone pulumi.StringOutput `pulumi:"timezone"`
	// Type of trigger backing this schedule.
	TriggerType pulumi.StringOutput `pulumi:"triggerType"`
	// Last-update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewSchedule registers a new resource with the given unique name, arguments, and options.
func NewSchedule(ctx *pulumi.Context,
	name string, args *ScheduleArgs, opts ...pulumi.ResourceOption) (*Schedule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AgentId == nil {
		return nil, errors.New("invalid value for required argument 'AgentId'")
	}
	if args.CronExpr == nil {
		return nil, errors.New("invalid value for required argument 'CronExpr'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Schedule
	err := ctx.RegisterResource("agentops:index/schedule:Schedule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSchedule gets an existing Schedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ScheduleState, opts ...pulumi.ResourceOption) (*Schedule, error) {
	var resource Schedule
	err := ctx.ReadResource("agentops:index/schedule:Schedule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Schedule resources.
type scheduleState struct {
	// ID of the agent this schedule invokes. Changing this forces a new schedule.
	AgentId *string `pulumi:"agentId"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Cron expression describing when the schedule fires.
	CronExpr *string `pulumi:"cronExpr"`
	// Free-form description.
	Description *string `pulumi:"description"`
	// Whether the schedule can be edited.
	Editable *bool `pulumi:"editable"`
	// Input payload passed to the agent, as a JSON object.
	Input *string `pulumi:"input"`
	// Whether the schedule is active. Defaults to `true`.
	IsEnabled *bool `pulumi:"isEnabled"`
	// Timestamp of the last time the schedule fired.
	LastFiredAt *string `pulumi:"lastFiredAt"`
	// Human-readable schedule name.
	Name *string `pulumi:"name"`
	// Origin of the schedule.
	Source *string `pulumi:"source"`
	// Identifier of the schedule's source.
	SourceId *string `pulumi:"sourceId"`
	// IANA timezone in which the cron expression is evaluated. Server-assigned when omitted.
	Timezone *string `pulumi:"timezone"`
	// Type of trigger backing this schedule.
	TriggerType *string `pulumi:"triggerType"`
	// Last-update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type ScheduleState struct {
	// ID of the agent this schedule invokes. Changing this forces a new schedule.
	AgentId pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Cron expression describing when the schedule fires.
	CronExpr pulumi.StringPtrInput
	// Free-form description.
	Description pulumi.StringPtrInput
	// Whether the schedule can be edited.
	Editable pulumi.BoolPtrInput
	// Input payload passed to the agent, as a JSON object.
	Input pulumi.StringPtrInput
	// Whether the schedule is active. Defaults to `true`.
	IsEnabled pulumi.BoolPtrInput
	// Timestamp of the last time the schedule fired.
	LastFiredAt pulumi.StringPtrInput
	// Human-readable schedule name.
	Name pulumi.StringPtrInput
	// Origin of the schedule.
	Source pulumi.StringPtrInput
	// Identifier of the schedule's source.
	SourceId pulumi.StringPtrInput
	// IANA timezone in which the cron expression is evaluated. Server-assigned when omitted.
	Timezone pulumi.StringPtrInput
	// Type of trigger backing this schedule.
	TriggerType pulumi.StringPtrInput
	// Last-update timestamp.
	UpdatedAt pulumi.StringPtrInput
}

func (ScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleState)(nil)).Elem()
}

type scheduleArgs struct {
	// ID of the agent this schedule invokes. Changing this forces a new schedule.
	AgentId string `pulumi:"agentId"`
	// Cron expression describing when the schedule fires.
	CronExpr string `pulumi:"cronExpr"`
	// Input payload passed to the agent, as a JSON object.
	Input *string `pulumi:"input"`
	// Whether the schedule is active. Defaults to `true`.
	IsEnabled *bool `pulumi:"isEnabled"`
	// IANA timezone in which the cron expression is evaluated. Server-assigned when omitted.
	Timezone *string `pulumi:"timezone"`
}

// The set of arguments for constructing a Schedule resource.
type ScheduleArgs struct {
	// ID of the agent this schedule invokes. Changing this forces a new schedule.
	AgentId pulumi.StringInput
	// Cron expression describing when the schedule fires.
	CronExpr pulumi.StringInput
	// Input payload passed to the agent, as a JSON object.
	Input pulumi.StringPtrInput
	// Whether the schedule is active. Defaults to `true`.
	IsEnabled pulumi.BoolPtrInput
	// IANA timezone in which the cron expression is evaluated. Server-assigned when omitted.
	Timezone pulumi.StringPtrInput
}

func (ScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*scheduleArgs)(nil)).Elem()
}

type ScheduleInput interface {
	pulumi.Input

	ToScheduleOutput() ScheduleOutput
	ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput
}

func (*Schedule) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (i *Schedule) ToScheduleOutput() ScheduleOutput {
	return i.ToScheduleOutputWithContext(context.Background())
}

func (i *Schedule) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleOutput)
}

// ScheduleArrayInput is an input type that accepts ScheduleArray and ScheduleArrayOutput values.
// You can construct a concrete instance of `ScheduleArrayInput` via:
//
//	ScheduleArray{ ScheduleArgs{...} }
type ScheduleArrayInput interface {
	pulumi.Input

	ToScheduleArrayOutput() ScheduleArrayOutput
	ToScheduleArrayOutputWithContext(context.Context) ScheduleArrayOutput
}

type ScheduleArray []ScheduleInput

func (ScheduleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schedule)(nil)).Elem()
}

func (i ScheduleArray) ToScheduleArrayOutput() ScheduleArrayOutput {
	return i.ToScheduleArrayOutputWithContext(context.Background())
}

func (i ScheduleArray) ToScheduleArrayOutputWithContext(ctx context.Context) ScheduleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleArrayOutput)
}

// ScheduleMapInput is an input type that accepts ScheduleMap and ScheduleMapOutput values.
// You can construct a concrete instance of `ScheduleMapInput` via:
//
//	ScheduleMap{ "key": ScheduleArgs{...} }
type ScheduleMapInput interface {
	pulumi.Input

	ToScheduleMapOutput() ScheduleMapOutput
	ToScheduleMapOutputWithContext(context.Context) ScheduleMapOutput
}

type ScheduleMap map[string]ScheduleInput

func (ScheduleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schedule)(nil)).Elem()
}

func (i ScheduleMap) ToScheduleMapOutput() ScheduleMapOutput {
	return i.ToScheduleMapOutputWithContext(context.Background())
}

func (i ScheduleMap) ToScheduleMapOutputWithContext(ctx context.Context) ScheduleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScheduleMapOutput)
}

type ScheduleOutput struct{ *pulumi.OutputState }

func (ScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Schedule)(nil)).Elem()
}

func (o ScheduleOutput) ToScheduleOutput() ScheduleOutput {
	return o
}

func (o ScheduleOutput) ToScheduleOutputWithContext(ctx context.Context) ScheduleOutput {
	return o
}

// ID of the agent this schedule invokes. Changing this forces a new schedule.
func (o ScheduleOutput) AgentId() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.AgentId }).(pulumi.StringOutput)
}

// Creation timestamp.
func (o ScheduleOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Cron expression describing when the schedule fires.
func (o ScheduleOutput) CronExpr() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.CronExpr }).(pulumi.StringOutput)
}

// Free-form description.
func (o ScheduleOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Whether the schedule can be edited.
func (o ScheduleOutput) Editable() pulumi.BoolOutput {
	return o.ApplyT(func(v *Schedule) pulumi.BoolOutput { return v.Editable }).(pulumi.BoolOutput)
}

// Input payload passed to the agent, as a JSON object.
func (o ScheduleOutput) Input() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Input }).(pulumi.StringOutput)
}

// Whether the schedule is active. Defaults to `true`.
func (o ScheduleOutput) IsEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Schedule) pulumi.BoolOutput { return v.IsEnabled }).(pulumi.BoolOutput)
}

// Timestamp of the last time the schedule fired.
func (o ScheduleOutput) LastFiredAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.LastFiredAt }).(pulumi.StringOutput)
}

// Human-readable schedule name.
func (o ScheduleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Origin of the schedule.
func (o ScheduleOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

// Identifier of the schedule's source.
func (o ScheduleOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.SourceId }).(pulumi.StringOutput)
}

// IANA timezone in which the cron expression is evaluated. Server-assigned when omitted.
func (o ScheduleOutput) Timezone() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.Timezone }).(pulumi.StringOutput)
}

// Type of trigger backing this schedule.
func (o ScheduleOutput) TriggerType() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.TriggerType }).(pulumi.StringOutput)
}

// Last-update timestamp.
func (o ScheduleOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Schedule) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type ScheduleArrayOutput struct{ *pulumi.OutputState }

func (ScheduleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Schedule)(nil)).Elem()
}

func (o ScheduleArrayOutput) ToScheduleArrayOutput() ScheduleArrayOutput {
	return o
}

func (o ScheduleArrayOutput) ToScheduleArrayOutputWithContext(ctx context.Context) ScheduleArrayOutput {
	return o
}

func (o ScheduleArrayOutput) Index(i pulumi.IntInput) ScheduleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Schedule {
		return vs[0].([]*Schedule)[vs[1].(int)]
	}).(ScheduleOutput)
}

type ScheduleMapOutput struct{ *pulumi.OutputState }

func (ScheduleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Schedule)(nil)).Elem()
}

func (o ScheduleMapOutput) ToScheduleMapOutput() ScheduleMapOutput {
	return o
}

func (o ScheduleMapOutput) ToScheduleMapOutputWithContext(ctx context.Context) ScheduleMapOutput {
	return o
}

func (o ScheduleMapOutput) MapIndex(k pulumi.StringInput) ScheduleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Schedule {
		return vs[0].(map[string]*Schedule)[vs[1].(string)]
	}).(ScheduleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleInput)(nil)).Elem(), &Schedule{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleArrayInput)(nil)).Elem(), ScheduleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScheduleMapInput)(nil)).Elem(), ScheduleMap{})
	pulumi.RegisterOutputType(ScheduleOutput{})
	pulumi.RegisterOutputType(ScheduleArrayOutput{})
	pulumi.RegisterOutputType(ScheduleMapOutput{})
}
