// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package agentops

import (
	"context"
	"reflect"

	"errors"
	"github.com/komodorio/pulumi-agentops/sdk/go/agentops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deploys a curated worker from the worker catalog. The server pins the image and derives the customer and credentials from the catalog entry and your account, so you only name the instance — the result is a managed hosted agent. Destroying one archives it first where the account requires that, and waits for the archive to finish before deleting. Deploy-time inputs are write-only (the API does not return them), so out-of-band changes to them are not detected, and changing any of them forces a new deployment. This resource does not support import: the originating `catalogId` and the write-only inputs cannot be recovered from the API.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/komodorio/pulumi-agentops/sdk/go/agentops"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Deploy a curated worker from the catalog. The server pins the image and derives
//			// the customer and credentials, so you only name the instance. Browse available
//			// entries (and their IDs / required credentials) via the agentops_worker_catalog
//			// data source.
//			_, err := agentops.GetWorkerCatalog(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = agentops.NewWorkerCatalogDeployment(ctx, "k8s_troubleshooter", &agentops.WorkerCatalogDeploymentArgs{
//				CatalogId:     pulumi.String("k8s-troubleshooter"),
//				AgentId:       pulumi.String("prod-k8s-troubleshooter"),
//				DisplayName:   pulumi.String("Prod K8s Troubleshooter"),
//				CredentialRef: pulumi.String("anthropic-api-key"),
//				IntegrationConnections: pulumi.StringMap{
//					"aws": pulumi.String("conn_01hxyz"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type WorkerCatalogDeployment struct {
	pulumi.CustomResourceState

	// Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
	AgentId pulumi.StringOutput `pulumi:"agentId"`
	// ID of the worker catalog entry to deploy. Changing this forces a new deployment.
	CatalogId pulumi.StringOutput `pulumi:"catalogId"`
	// Creation timestamp.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
	CredentialRef pulumi.StringPtrOutput `pulumi:"credentialRef"`
	// Customer/tenant the worker was deployed under, derived by the server.
	Customer pulumi.StringOutput `pulumi:"customer"`
	// Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
	DisplayName pulumi.StringPtrOutput `pulumi:"displayName"`
	// Resolved runtime identity of the deployed worker.
	Identity pulumi.StringOutput `pulumi:"identity"`
	// Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
	IntegrationConnections pulumi.StringMapOutput `pulumi:"integrationConnections"`
	// SHA of the most recent commit to the generated repository.
	LastCommitSha pulumi.StringOutput `pulumi:"lastCommitSha"`
	// ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
	McpGroupId pulumi.StringPtrOutput `pulumi:"mcpGroupId"`
	// Branch of the generated agent repository.
	RepoBranch pulumi.StringOutput `pulumi:"repoBranch"`
	// Name of the generated agent repository.
	RepoName pulumi.StringOutput `pulumi:"repoName"`
	// Owner of the generated agent repository.
	RepoOwner pulumi.StringOutput `pulumi:"repoOwner"`
	// Path within the generated agent repository.
	RepoPath pulumi.StringOutput `pulumi:"repoPath"`
	// Runtime agent ID the deployment registers as.
	RuntimeAgentId pulumi.StringOutput `pulumi:"runtimeAgentId"`
	// Deployment status (`online`, `offline`, `draft`, `deploying`, `deployFailed`).
	Status pulumi.StringOutput `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Resolved deployment values, as a JSON object.
	Values pulumi.StringOutput `pulumi:"values"`
	// Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
	WaitForOnline pulumi.BoolPtrOutput `pulumi:"waitForOnline"`
	// Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
	WaitTimeout pulumi.StringPtrOutput `pulumi:"waitTimeout"`
}

// NewWorkerCatalogDeployment registers a new resource with the given unique name, arguments, and options.
func NewWorkerCatalogDeployment(ctx *pulumi.Context,
	name string, args *WorkerCatalogDeploymentArgs, opts ...pulumi.ResourceOption) (*WorkerCatalogDeployment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CatalogId == nil {
		return nil, errors.New("invalid value for required argument 'CatalogId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WorkerCatalogDeployment
	err := ctx.RegisterResource("agentops:index/workerCatalogDeployment:WorkerCatalogDeployment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWorkerCatalogDeployment gets an existing WorkerCatalogDeployment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWorkerCatalogDeployment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WorkerCatalogDeploymentState, opts ...pulumi.ResourceOption) (*WorkerCatalogDeployment, error) {
	var resource WorkerCatalogDeployment
	err := ctx.ReadResource("agentops:index/workerCatalogDeployment:WorkerCatalogDeployment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WorkerCatalogDeployment resources.
type workerCatalogDeploymentState struct {
	// Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
	AgentId *string `pulumi:"agentId"`
	// ID of the worker catalog entry to deploy. Changing this forces a new deployment.
	CatalogId *string `pulumi:"catalogId"`
	// Creation timestamp.
	CreatedAt *string `pulumi:"createdAt"`
	// Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
	CredentialRef *string `pulumi:"credentialRef"`
	// Customer/tenant the worker was deployed under, derived by the server.
	Customer *string `pulumi:"customer"`
	// Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
	DisplayName *string `pulumi:"displayName"`
	// Resolved runtime identity of the deployed worker.
	Identity *string `pulumi:"identity"`
	// Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
	IntegrationConnections map[string]string `pulumi:"integrationConnections"`
	// SHA of the most recent commit to the generated repository.
	LastCommitSha *string `pulumi:"lastCommitSha"`
	// ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
	McpGroupId *string `pulumi:"mcpGroupId"`
	// Branch of the generated agent repository.
	RepoBranch *string `pulumi:"repoBranch"`
	// Name of the generated agent repository.
	RepoName *string `pulumi:"repoName"`
	// Owner of the generated agent repository.
	RepoOwner *string `pulumi:"repoOwner"`
	// Path within the generated agent repository.
	RepoPath *string `pulumi:"repoPath"`
	// Runtime agent ID the deployment registers as.
	RuntimeAgentId *string `pulumi:"runtimeAgentId"`
	// Deployment status (`online`, `offline`, `draft`, `deploying`, `deployFailed`).
	Status *string `pulumi:"status"`
	// Last-update timestamp.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Resolved deployment values, as a JSON object.
	Values *string `pulumi:"values"`
	// Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
	WaitForOnline *bool `pulumi:"waitForOnline"`
	// Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
	WaitTimeout *string `pulumi:"waitTimeout"`
}

type WorkerCatalogDeploymentState struct {
	// Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
	AgentId pulumi.StringPtrInput
	// ID of the worker catalog entry to deploy. Changing this forces a new deployment.
	CatalogId pulumi.StringPtrInput
	// Creation timestamp.
	CreatedAt pulumi.StringPtrInput
	// Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
	CredentialRef pulumi.StringPtrInput
	// Customer/tenant the worker was deployed under, derived by the server.
	Customer pulumi.StringPtrInput
	// Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
	DisplayName pulumi.StringPtrInput
	// Resolved runtime identity of the deployed worker.
	Identity pulumi.StringPtrInput
	// Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
	IntegrationConnections pulumi.StringMapInput
	// SHA of the most recent commit to the generated repository.
	LastCommitSha pulumi.StringPtrInput
	// ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
	McpGroupId pulumi.StringPtrInput
	// Branch of the generated agent repository.
	RepoBranch pulumi.StringPtrInput
	// Name of the generated agent repository.
	RepoName pulumi.StringPtrInput
	// Owner of the generated agent repository.
	RepoOwner pulumi.StringPtrInput
	// Path within the generated agent repository.
	RepoPath pulumi.StringPtrInput
	// Runtime agent ID the deployment registers as.
	RuntimeAgentId pulumi.StringPtrInput
	// Deployment status (`online`, `offline`, `draft`, `deploying`, `deployFailed`).
	Status pulumi.StringPtrInput
	// Last-update timestamp.
	UpdatedAt pulumi.StringPtrInput
	// Resolved deployment values, as a JSON object.
	Values pulumi.StringPtrInput
	// Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
	WaitForOnline pulumi.BoolPtrInput
	// Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
	WaitTimeout pulumi.StringPtrInput
}

func (WorkerCatalogDeploymentState) ElementType() reflect.Type {
	return reflect.TypeOf((*workerCatalogDeploymentState)(nil)).Elem()
}

type workerCatalogDeploymentArgs struct {
	// Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
	AgentId *string `pulumi:"agentId"`
	// ID of the worker catalog entry to deploy. Changing this forces a new deployment.
	CatalogId string `pulumi:"catalogId"`
	// Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
	CredentialRef *string `pulumi:"credentialRef"`
	// Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
	DisplayName *string `pulumi:"displayName"`
	// Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
	IntegrationConnections map[string]string `pulumi:"integrationConnections"`
	// ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
	McpGroupId *string `pulumi:"mcpGroupId"`
	// Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
	WaitForOnline *bool `pulumi:"waitForOnline"`
	// Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
	WaitTimeout *string `pulumi:"waitTimeout"`
}

// The set of arguments for constructing a WorkerCatalogDeployment resource.
type WorkerCatalogDeploymentArgs struct {
	// Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
	AgentId pulumi.StringPtrInput
	// ID of the worker catalog entry to deploy. Changing this forces a new deployment.
	CatalogId pulumi.StringInput
	// Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
	CredentialRef pulumi.StringPtrInput
	// Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
	DisplayName pulumi.StringPtrInput
	// Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
	IntegrationConnections pulumi.StringMapInput
	// ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
	McpGroupId pulumi.StringPtrInput
	// Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
	WaitForOnline pulumi.BoolPtrInput
	// Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
	WaitTimeout pulumi.StringPtrInput
}

func (WorkerCatalogDeploymentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*workerCatalogDeploymentArgs)(nil)).Elem()
}

type WorkerCatalogDeploymentInput interface {
	pulumi.Input

	ToWorkerCatalogDeploymentOutput() WorkerCatalogDeploymentOutput
	ToWorkerCatalogDeploymentOutputWithContext(ctx context.Context) WorkerCatalogDeploymentOutput
}

func (*WorkerCatalogDeployment) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkerCatalogDeployment)(nil)).Elem()
}

func (i *WorkerCatalogDeployment) ToWorkerCatalogDeploymentOutput() WorkerCatalogDeploymentOutput {
	return i.ToWorkerCatalogDeploymentOutputWithContext(context.Background())
}

func (i *WorkerCatalogDeployment) ToWorkerCatalogDeploymentOutputWithContext(ctx context.Context) WorkerCatalogDeploymentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkerCatalogDeploymentOutput)
}

// WorkerCatalogDeploymentArrayInput is an input type that accepts WorkerCatalogDeploymentArray and WorkerCatalogDeploymentArrayOutput values.
// You can construct a concrete instance of `WorkerCatalogDeploymentArrayInput` via:
//
//	WorkerCatalogDeploymentArray{ WorkerCatalogDeploymentArgs{...} }
type WorkerCatalogDeploymentArrayInput interface {
	pulumi.Input

	ToWorkerCatalogDeploymentArrayOutput() WorkerCatalogDeploymentArrayOutput
	ToWorkerCatalogDeploymentArrayOutputWithContext(context.Context) WorkerCatalogDeploymentArrayOutput
}

type WorkerCatalogDeploymentArray []WorkerCatalogDeploymentInput

func (WorkerCatalogDeploymentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkerCatalogDeployment)(nil)).Elem()
}

func (i WorkerCatalogDeploymentArray) ToWorkerCatalogDeploymentArrayOutput() WorkerCatalogDeploymentArrayOutput {
	return i.ToWorkerCatalogDeploymentArrayOutputWithContext(context.Background())
}

func (i WorkerCatalogDeploymentArray) ToWorkerCatalogDeploymentArrayOutputWithContext(ctx context.Context) WorkerCatalogDeploymentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkerCatalogDeploymentArrayOutput)
}

// WorkerCatalogDeploymentMapInput is an input type that accepts WorkerCatalogDeploymentMap and WorkerCatalogDeploymentMapOutput values.
// You can construct a concrete instance of `WorkerCatalogDeploymentMapInput` via:
//
//	WorkerCatalogDeploymentMap{ "key": WorkerCatalogDeploymentArgs{...} }
type WorkerCatalogDeploymentMapInput interface {
	pulumi.Input

	ToWorkerCatalogDeploymentMapOutput() WorkerCatalogDeploymentMapOutput
	ToWorkerCatalogDeploymentMapOutputWithContext(context.Context) WorkerCatalogDeploymentMapOutput
}

type WorkerCatalogDeploymentMap map[string]WorkerCatalogDeploymentInput

func (WorkerCatalogDeploymentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkerCatalogDeployment)(nil)).Elem()
}

func (i WorkerCatalogDeploymentMap) ToWorkerCatalogDeploymentMapOutput() WorkerCatalogDeploymentMapOutput {
	return i.ToWorkerCatalogDeploymentMapOutputWithContext(context.Background())
}

func (i WorkerCatalogDeploymentMap) ToWorkerCatalogDeploymentMapOutputWithContext(ctx context.Context) WorkerCatalogDeploymentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WorkerCatalogDeploymentMapOutput)
}

type WorkerCatalogDeploymentOutput struct{ *pulumi.OutputState }

func (WorkerCatalogDeploymentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WorkerCatalogDeployment)(nil)).Elem()
}

func (o WorkerCatalogDeploymentOutput) ToWorkerCatalogDeploymentOutput() WorkerCatalogDeploymentOutput {
	return o
}

func (o WorkerCatalogDeploymentOutput) ToWorkerCatalogDeploymentOutputWithContext(ctx context.Context) WorkerCatalogDeploymentOutput {
	return o
}

// Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
func (o WorkerCatalogDeploymentOutput) AgentId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.AgentId }).(pulumi.StringOutput)
}

// ID of the worker catalog entry to deploy. Changing this forces a new deployment.
func (o WorkerCatalogDeploymentOutput) CatalogId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.CatalogId }).(pulumi.StringOutput)
}

// Creation timestamp.
func (o WorkerCatalogDeploymentOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
func (o WorkerCatalogDeploymentOutput) CredentialRef() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringPtrOutput { return v.CredentialRef }).(pulumi.StringPtrOutput)
}

// Customer/tenant the worker was deployed under, derived by the server.
func (o WorkerCatalogDeploymentOutput) Customer() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.Customer }).(pulumi.StringOutput)
}

// Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
func (o WorkerCatalogDeploymentOutput) DisplayName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringPtrOutput { return v.DisplayName }).(pulumi.StringPtrOutput)
}

// Resolved runtime identity of the deployed worker.
func (o WorkerCatalogDeploymentOutput) Identity() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.Identity }).(pulumi.StringOutput)
}

// Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
func (o WorkerCatalogDeploymentOutput) IntegrationConnections() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringMapOutput { return v.IntegrationConnections }).(pulumi.StringMapOutput)
}

// SHA of the most recent commit to the generated repository.
func (o WorkerCatalogDeploymentOutput) LastCommitSha() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.LastCommitSha }).(pulumi.StringOutput)
}

// ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
func (o WorkerCatalogDeploymentOutput) McpGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringPtrOutput { return v.McpGroupId }).(pulumi.StringPtrOutput)
}

// Branch of the generated agent repository.
func (o WorkerCatalogDeploymentOutput) RepoBranch() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.RepoBranch }).(pulumi.StringOutput)
}

// Name of the generated agent repository.
func (o WorkerCatalogDeploymentOutput) RepoName() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.RepoName }).(pulumi.StringOutput)
}

// Owner of the generated agent repository.
func (o WorkerCatalogDeploymentOutput) RepoOwner() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.RepoOwner }).(pulumi.StringOutput)
}

// Path within the generated agent repository.
func (o WorkerCatalogDeploymentOutput) RepoPath() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.RepoPath }).(pulumi.StringOutput)
}

// Runtime agent ID the deployment registers as.
func (o WorkerCatalogDeploymentOutput) RuntimeAgentId() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.RuntimeAgentId }).(pulumi.StringOutput)
}

// Deployment status (`online`, `offline`, `draft`, `deploying`, `deployFailed`).
func (o WorkerCatalogDeploymentOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Last-update timestamp.
func (o WorkerCatalogDeploymentOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Resolved deployment values, as a JSON object.
func (o WorkerCatalogDeploymentOutput) Values() pulumi.StringOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringOutput { return v.Values }).(pulumi.StringOutput)
}

// Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
func (o WorkerCatalogDeploymentOutput) WaitForOnline() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.BoolPtrOutput { return v.WaitForOnline }).(pulumi.BoolPtrOutput)
}

// Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
func (o WorkerCatalogDeploymentOutput) WaitTimeout() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WorkerCatalogDeployment) pulumi.StringPtrOutput { return v.WaitTimeout }).(pulumi.StringPtrOutput)
}

type WorkerCatalogDeploymentArrayOutput struct{ *pulumi.OutputState }

func (WorkerCatalogDeploymentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WorkerCatalogDeployment)(nil)).Elem()
}

func (o WorkerCatalogDeploymentArrayOutput) ToWorkerCatalogDeploymentArrayOutput() WorkerCatalogDeploymentArrayOutput {
	return o
}

func (o WorkerCatalogDeploymentArrayOutput) ToWorkerCatalogDeploymentArrayOutputWithContext(ctx context.Context) WorkerCatalogDeploymentArrayOutput {
	return o
}

func (o WorkerCatalogDeploymentArrayOutput) Index(i pulumi.IntInput) WorkerCatalogDeploymentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WorkerCatalogDeployment {
		return vs[0].([]*WorkerCatalogDeployment)[vs[1].(int)]
	}).(WorkerCatalogDeploymentOutput)
}

type WorkerCatalogDeploymentMapOutput struct{ *pulumi.OutputState }

func (WorkerCatalogDeploymentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WorkerCatalogDeployment)(nil)).Elem()
}

func (o WorkerCatalogDeploymentMapOutput) ToWorkerCatalogDeploymentMapOutput() WorkerCatalogDeploymentMapOutput {
	return o
}

func (o WorkerCatalogDeploymentMapOutput) ToWorkerCatalogDeploymentMapOutputWithContext(ctx context.Context) WorkerCatalogDeploymentMapOutput {
	return o
}

func (o WorkerCatalogDeploymentMapOutput) MapIndex(k pulumi.StringInput) WorkerCatalogDeploymentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WorkerCatalogDeployment {
		return vs[0].(map[string]*WorkerCatalogDeployment)[vs[1].(string)]
	}).(WorkerCatalogDeploymentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WorkerCatalogDeploymentInput)(nil)).Elem(), &WorkerCatalogDeployment{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkerCatalogDeploymentArrayInput)(nil)).Elem(), WorkerCatalogDeploymentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WorkerCatalogDeploymentMapInput)(nil)).Elem(), WorkerCatalogDeploymentMap{})
	pulumi.RegisterOutputType(WorkerCatalogDeploymentOutput{})
	pulumi.RegisterOutputType(WorkerCatalogDeploymentArrayOutput{})
	pulumi.RegisterOutputType(WorkerCatalogDeploymentMapOutput{})
}
