# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetReviewersResult',
    'AwaitableGetReviewersResult',
    'get_reviewers',
    'get_reviewers_output',
]

@pulumi.output_type
class GetReviewersResult:
    """
    A collection of values returned by getReviewers.
    """
    def __init__(__self__, reviewers=None):
        if reviewers and not isinstance(reviewers, list):
            raise TypeError("Expected argument 'reviewers' to be a list")
        pulumi.set(__self__, "reviewers", reviewers)

    @_builtins.property
    @pulumi.getter
    def reviewers(self) -> Sequence['outputs.GetReviewersReviewerResult']:
        """
        Available reviewer agents.
        """
        return pulumi.get(self, "reviewers")


class AwaitableGetReviewersResult(GetReviewersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetReviewersResult(
            reviewers=self.reviewers)


def get_reviewers(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetReviewersResult:
    """
    The reviewer agents available to this account, including built-in reviewers, for use in `agentops_review_workflow.reviewer_agent_ids`.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_agentops as agentops

    all = agentops.get_reviewers()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('agentops:index/getReviewers:getReviewers', __args__, opts=opts, typ=GetReviewersResult).value

    return AwaitableGetReviewersResult(
        reviewers=pulumi.get(__ret__, 'reviewers'))
def get_reviewers_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetReviewersResult]:
    """
    The reviewer agents available to this account, including built-in reviewers, for use in `agentops_review_workflow.reviewer_agent_ids`.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_agentops as agentops

    all = agentops.get_reviewers()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('agentops:index/getReviewers:getReviewers', __args__, opts=opts, typ=GetReviewersResult)
    return __ret__.apply(lambda __response__: GetReviewersResult(
        reviewers=pulumi.get(__response__, 'reviewers')))
