# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCapabilitiesResult',
    'AwaitableGetCapabilitiesResult',
    'get_capabilities',
    'get_capabilities_output',
]

@pulumi.output_type
class GetCapabilitiesResult:
    """
    A collection of values returned by getCapabilities.
    """
    def __init__(__self__, capabilities=None):
        if capabilities and not isinstance(capabilities, list):
            raise TypeError("Expected argument 'capabilities' to be a list")
        pulumi.set(__self__, "capabilities", capabilities)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> Sequence['outputs.GetCapabilitiesCapabilityResult']:
        """
        Available authorization capabilities.
        """
        return pulumi.get(self, "capabilities")


class AwaitableGetCapabilitiesResult(GetCapabilitiesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCapabilitiesResult(
            capabilities=self.capabilities)


def get_capabilities(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCapabilitiesResult:
    """
    The authorization capabilities available to this account.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_agentops as agentops

    # All authorization capabilities known to the account.
    all = agentops.get_capabilities()
    pulumi.export("capabilityKeys", [c.key for c in all.capabilities])
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('agentops:index/getCapabilities:getCapabilities', __args__, opts=opts, typ=GetCapabilitiesResult).value

    return AwaitableGetCapabilitiesResult(
        capabilities=pulumi.get(__ret__, 'capabilities'))
def get_capabilities_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCapabilitiesResult]:
    """
    The authorization capabilities available to this account.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_agentops as agentops

    # All authorization capabilities known to the account.
    all = agentops.get_capabilities()
    pulumi.export("capabilityKeys", [c.key for c in all.capabilities])
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('agentops:index/getCapabilities:getCapabilities', __args__, opts=opts, typ=GetCapabilitiesResult)
    return __ret__.apply(lambda __response__: GetCapabilitiesResult(
        capabilities=pulumi.get(__response__, 'capabilities')))
