# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['HostedAgentArgs', 'HostedAgent']

@pulumi.input_type
class HostedAgentArgs:
    def __init__(__self__, *,
                 agent_id: pulumi.Input[_builtins.str],
                 credential_ref: pulumi.Input[_builtins.str],
                 instructions: pulumi.Input[_builtins.str],
                 agents: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentAgentArgs']]]] = None,
                 capabilities: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]] = None,
                 commit_message: pulumi.Input[Optional[_builtins.str]] = None,
                 customer: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 image: pulumi.Input[Optional['HostedAgentImageArgs']] = None,
                 mcp_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mcp_servers: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]]] = None,
                 model: pulumi.Input[Optional[_builtins.str]] = None,
                 skills: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentSkillArgs']]]] = None,
                 wait_for_online: pulumi.Input[Optional[_builtins.bool]] = None,
                 wait_timeout: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a HostedAgent resource.

        :param pulumi.Input[_builtins.str] agent_id: Stable agent identifier within the customer. Changing this forces a new hosted agent.
        :param pulumi.Input[_builtins.str] credential_ref: Reference to the credential the agent runs with. Write-only.
        :param pulumi.Input[_builtins.str] instructions: System instructions for the agent. Write-only.
        :param pulumi.Input[Sequence[pulumi.Input['HostedAgentAgentArgs']]] agents: Subagents bundled into the agent. Write-only.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.bool]]] capabilities: Capability toggles for the agent. Write-only.
        :param pulumi.Input[_builtins.str] commit_message: Commit message recorded when the agent's generated repo is updated. Write-only.
        :param pulumi.Input[_builtins.str] customer: Customer/tenant the agent is hosted for. Optional: the server derives it from your account when omitted. Changing this forces a new hosted agent.
        :param pulumi.Input[_builtins.str] display_name: Human-readable name. Write-only.
        :param pulumi.Input['HostedAgentImageArgs'] image: Container image overrides for the agent runtime. Write-only.
        :param pulumi.Input[_builtins.str] mcp_group_id: ID of an MCP gateway group to attach. Write-only.
        :param pulumi.Input[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]] mcp_servers: Named MCP servers the agent can reach. Write-only.
        :param pulumi.Input[_builtins.str] model: Model the agent uses. Write-only.
        :param pulumi.Input[Sequence[pulumi.Input['HostedAgentSkillArgs']]] skills: Skills bundled into the agent. Write-only.
        :param pulumi.Input[_builtins.bool] wait_for_online: Whether create/update should block until the hosted agent reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted — useful for agents that are intentionally left in `draft`/scaled to zero and will never heartbeat. While the agent is not yet online, a failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout. Updating an agent that is already online returns as soon as it reports `online`, which the revision already running does, so the new revision's rollout is not waited on.
        :param pulumi.Input[_builtins.str] wait_timeout: Maximum time to wait for the agent to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `wait_for_online` is `true`.
        """
        pulumi.set(__self__, "agent_id", agent_id)
        pulumi.set(__self__, "credential_ref", credential_ref)
        pulumi.set(__self__, "instructions", instructions)
        if agents is not None:
            pulumi.set(__self__, "agents", agents)
        if capabilities is not None:
            pulumi.set(__self__, "capabilities", capabilities)
        if commit_message is not None:
            pulumi.set(__self__, "commit_message", commit_message)
        if customer is not None:
            pulumi.set(__self__, "customer", customer)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if image is not None:
            pulumi.set(__self__, "image", image)
        if mcp_group_id is not None:
            pulumi.set(__self__, "mcp_group_id", mcp_group_id)
        if mcp_servers is not None:
            pulumi.set(__self__, "mcp_servers", mcp_servers)
        if model is not None:
            pulumi.set(__self__, "model", model)
        if skills is not None:
            pulumi.set(__self__, "skills", skills)
        if wait_for_online is not None:
            pulumi.set(__self__, "wait_for_online", wait_for_online)
        if wait_timeout is not None:
            pulumi.set(__self__, "wait_timeout", wait_timeout)

    @_builtins.property
    @pulumi.getter(name="agentId")
    def agent_id(self) -> pulumi.Input[_builtins.str]:
        """
        Stable agent identifier within the customer. Changing this forces a new hosted agent.
        """
        return pulumi.get(self, "agent_id")

    @agent_id.setter
    def agent_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "agent_id", value)

    @_builtins.property
    @pulumi.getter(name="credentialRef")
    def credential_ref(self) -> pulumi.Input[_builtins.str]:
        """
        Reference to the credential the agent runs with. Write-only.
        """
        return pulumi.get(self, "credential_ref")

    @credential_ref.setter
    def credential_ref(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "credential_ref", value)

    @_builtins.property
    @pulumi.getter
    def instructions(self) -> pulumi.Input[_builtins.str]:
        """
        System instructions for the agent. Write-only.
        """
        return pulumi.get(self, "instructions")

    @instructions.setter
    def instructions(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "instructions", value)

    @_builtins.property
    @pulumi.getter
    def agents(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentAgentArgs']]]]:
        """
        Subagents bundled into the agent. Write-only.
        """
        return pulumi.get(self, "agents")

    @agents.setter
    def agents(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentAgentArgs']]]]):
        pulumi.set(self, "agents", value)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]]:
        """
        Capability toggles for the agent. Write-only.
        """
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter(name="commitMessage")
    def commit_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Commit message recorded when the agent's generated repo is updated. Write-only.
        """
        return pulumi.get(self, "commit_message")

    @commit_message.setter
    def commit_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "commit_message", value)

    @_builtins.property
    @pulumi.getter
    def customer(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Customer/tenant the agent is hosted for. Optional: the server derives it from your account when omitted. Changing this forces a new hosted agent.
        """
        return pulumi.get(self, "customer")

    @customer.setter
    def customer(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "customer", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable name. Write-only.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Input[Optional['HostedAgentImageArgs']]:
        """
        Container image overrides for the agent runtime. Write-only.
        """
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: pulumi.Input[Optional['HostedAgentImageArgs']]):
        pulumi.set(self, "image", value)

    @_builtins.property
    @pulumi.getter(name="mcpGroupId")
    def mcp_group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of an MCP gateway group to attach. Write-only.
        """
        return pulumi.get(self, "mcp_group_id")

    @mcp_group_id.setter
    def mcp_group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "mcp_group_id", value)

    @_builtins.property
    @pulumi.getter(name="mcpServers")
    def mcp_servers(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]]]:
        """
        Named MCP servers the agent can reach. Write-only.
        """
        return pulumi.get(self, "mcp_servers")

    @mcp_servers.setter
    def mcp_servers(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]]]):
        pulumi.set(self, "mcp_servers", value)

    @_builtins.property
    @pulumi.getter
    def model(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Model the agent uses. Write-only.
        """
        return pulumi.get(self, "model")

    @model.setter
    def model(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "model", value)

    @_builtins.property
    @pulumi.getter
    def skills(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentSkillArgs']]]]:
        """
        Skills bundled into the agent. Write-only.
        """
        return pulumi.get(self, "skills")

    @skills.setter
    def skills(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentSkillArgs']]]]):
        pulumi.set(self, "skills", value)

    @_builtins.property
    @pulumi.getter(name="waitForOnline")
    def wait_for_online(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether create/update should block until the hosted agent reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted — useful for agents that are intentionally left in `draft`/scaled to zero and will never heartbeat. While the agent is not yet online, a failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout. Updating an agent that is already online returns as soon as it reports `online`, which the revision already running does, so the new revision's rollout is not waited on.
        """
        return pulumi.get(self, "wait_for_online")

    @wait_for_online.setter
    def wait_for_online(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "wait_for_online", value)

    @_builtins.property
    @pulumi.getter(name="waitTimeout")
    def wait_timeout(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Maximum time to wait for the agent to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `wait_for_online` is `true`.
        """
        return pulumi.get(self, "wait_timeout")

    @wait_timeout.setter
    def wait_timeout(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "wait_timeout", value)


@pulumi.input_type
class _HostedAgentState:
    def __init__(__self__, *,
                 agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 agents: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentAgentArgs']]]] = None,
                 capabilities: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]] = None,
                 commit_message: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 credential_ref: pulumi.Input[Optional[_builtins.str]] = None,
                 customer: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 identity: pulumi.Input[Optional[_builtins.str]] = None,
                 image: pulumi.Input[Optional['HostedAgentImageArgs']] = None,
                 instructions: pulumi.Input[Optional[_builtins.str]] = None,
                 last_commit_sha: pulumi.Input[Optional[_builtins.str]] = None,
                 mcp_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mcp_servers: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]]] = None,
                 model: pulumi.Input[Optional[_builtins.str]] = None,
                 repo_branch: pulumi.Input[Optional[_builtins.str]] = None,
                 repo_name: pulumi.Input[Optional[_builtins.str]] = None,
                 repo_owner: pulumi.Input[Optional[_builtins.str]] = None,
                 repo_path: pulumi.Input[Optional[_builtins.str]] = None,
                 runtime_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 skills: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentSkillArgs']]]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None,
                 values: pulumi.Input[Optional[_builtins.str]] = None,
                 wait_for_online: pulumi.Input[Optional[_builtins.bool]] = None,
                 wait_timeout: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering HostedAgent resources.

        :param pulumi.Input[_builtins.str] agent_id: Stable agent identifier within the customer. Changing this forces a new hosted agent.
        :param pulumi.Input[Sequence[pulumi.Input['HostedAgentAgentArgs']]] agents: Subagents bundled into the agent. Write-only.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.bool]]] capabilities: Capability toggles for the agent. Write-only.
        :param pulumi.Input[_builtins.str] commit_message: Commit message recorded when the agent's generated repo is updated. Write-only.
        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] credential_ref: Reference to the credential the agent runs with. Write-only.
        :param pulumi.Input[_builtins.str] customer: Customer/tenant the agent is hosted for. Optional: the server derives it from your account when omitted. Changing this forces a new hosted agent.
        :param pulumi.Input[_builtins.str] display_name: Human-readable name. Write-only.
        :param pulumi.Input[_builtins.str] identity: Resolved runtime identity of the hosted agent.
        :param pulumi.Input['HostedAgentImageArgs'] image: Container image overrides for the agent runtime. Write-only.
        :param pulumi.Input[_builtins.str] instructions: System instructions for the agent. Write-only.
        :param pulumi.Input[_builtins.str] last_commit_sha: SHA of the most recent commit to the generated repository.
        :param pulumi.Input[_builtins.str] mcp_group_id: ID of an MCP gateway group to attach. Write-only.
        :param pulumi.Input[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]] mcp_servers: Named MCP servers the agent can reach. Write-only.
        :param pulumi.Input[_builtins.str] model: Model the agent uses. Write-only.
        :param pulumi.Input[_builtins.str] repo_branch: Branch of the generated agent repository.
        :param pulumi.Input[_builtins.str] repo_name: Name of the generated agent repository.
        :param pulumi.Input[_builtins.str] repo_owner: Owner of the generated agent repository.
        :param pulumi.Input[_builtins.str] repo_path: Path within the generated agent repository.
        :param pulumi.Input[_builtins.str] runtime_agent_id: Runtime agent ID the deployment registers as.
        :param pulumi.Input[Sequence[pulumi.Input['HostedAgentSkillArgs']]] skills: Skills bundled into the agent. Write-only.
        :param pulumi.Input[_builtins.str] status: Deployment status (`online`, `offline`, `draft`, `deploying`, `deploy_failed`).
        :param pulumi.Input[_builtins.str] updated_at: Last-update timestamp.
        :param pulumi.Input[_builtins.str] values: Resolved deployment values, as a JSON object.
        :param pulumi.Input[_builtins.bool] wait_for_online: Whether create/update should block until the hosted agent reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted — useful for agents that are intentionally left in `draft`/scaled to zero and will never heartbeat. While the agent is not yet online, a failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout. Updating an agent that is already online returns as soon as it reports `online`, which the revision already running does, so the new revision's rollout is not waited on.
        :param pulumi.Input[_builtins.str] wait_timeout: Maximum time to wait for the agent to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `wait_for_online` is `true`.
        """
        if agent_id is not None:
            pulumi.set(__self__, "agent_id", agent_id)
        if agents is not None:
            pulumi.set(__self__, "agents", agents)
        if capabilities is not None:
            pulumi.set(__self__, "capabilities", capabilities)
        if commit_message is not None:
            pulumi.set(__self__, "commit_message", commit_message)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if credential_ref is not None:
            pulumi.set(__self__, "credential_ref", credential_ref)
        if customer is not None:
            pulumi.set(__self__, "customer", customer)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if identity is not None:
            pulumi.set(__self__, "identity", identity)
        if image is not None:
            pulumi.set(__self__, "image", image)
        if instructions is not None:
            pulumi.set(__self__, "instructions", instructions)
        if last_commit_sha is not None:
            pulumi.set(__self__, "last_commit_sha", last_commit_sha)
        if mcp_group_id is not None:
            pulumi.set(__self__, "mcp_group_id", mcp_group_id)
        if mcp_servers is not None:
            pulumi.set(__self__, "mcp_servers", mcp_servers)
        if model is not None:
            pulumi.set(__self__, "model", model)
        if repo_branch is not None:
            pulumi.set(__self__, "repo_branch", repo_branch)
        if repo_name is not None:
            pulumi.set(__self__, "repo_name", repo_name)
        if repo_owner is not None:
            pulumi.set(__self__, "repo_owner", repo_owner)
        if repo_path is not None:
            pulumi.set(__self__, "repo_path", repo_path)
        if runtime_agent_id is not None:
            pulumi.set(__self__, "runtime_agent_id", runtime_agent_id)
        if skills is not None:
            pulumi.set(__self__, "skills", skills)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)
        if values is not None:
            pulumi.set(__self__, "values", values)
        if wait_for_online is not None:
            pulumi.set(__self__, "wait_for_online", wait_for_online)
        if wait_timeout is not None:
            pulumi.set(__self__, "wait_timeout", wait_timeout)

    @_builtins.property
    @pulumi.getter(name="agentId")
    def agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Stable agent identifier within the customer. Changing this forces a new hosted agent.
        """
        return pulumi.get(self, "agent_id")

    @agent_id.setter
    def agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "agent_id", value)

    @_builtins.property
    @pulumi.getter
    def agents(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentAgentArgs']]]]:
        """
        Subagents bundled into the agent. Write-only.
        """
        return pulumi.get(self, "agents")

    @agents.setter
    def agents(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentAgentArgs']]]]):
        pulumi.set(self, "agents", value)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]]:
        """
        Capability toggles for the agent. Write-only.
        """
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter(name="commitMessage")
    def commit_message(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Commit message recorded when the agent's generated repo is updated. Write-only.
        """
        return pulumi.get(self, "commit_message")

    @commit_message.setter
    def commit_message(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "commit_message", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="credentialRef")
    def credential_ref(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Reference to the credential the agent runs with. Write-only.
        """
        return pulumi.get(self, "credential_ref")

    @credential_ref.setter
    def credential_ref(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "credential_ref", value)

    @_builtins.property
    @pulumi.getter
    def customer(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Customer/tenant the agent is hosted for. Optional: the server derives it from your account when omitted. Changing this forces a new hosted agent.
        """
        return pulumi.get(self, "customer")

    @customer.setter
    def customer(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "customer", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable name. Write-only.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def identity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Resolved runtime identity of the hosted agent.
        """
        return pulumi.get(self, "identity")

    @identity.setter
    def identity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "identity", value)

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Input[Optional['HostedAgentImageArgs']]:
        """
        Container image overrides for the agent runtime. Write-only.
        """
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: pulumi.Input[Optional['HostedAgentImageArgs']]):
        pulumi.set(self, "image", value)

    @_builtins.property
    @pulumi.getter
    def instructions(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        System instructions for the agent. Write-only.
        """
        return pulumi.get(self, "instructions")

    @instructions.setter
    def instructions(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "instructions", value)

    @_builtins.property
    @pulumi.getter(name="lastCommitSha")
    def last_commit_sha(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SHA of the most recent commit to the generated repository.
        """
        return pulumi.get(self, "last_commit_sha")

    @last_commit_sha.setter
    def last_commit_sha(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_commit_sha", value)

    @_builtins.property
    @pulumi.getter(name="mcpGroupId")
    def mcp_group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of an MCP gateway group to attach. Write-only.
        """
        return pulumi.get(self, "mcp_group_id")

    @mcp_group_id.setter
    def mcp_group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "mcp_group_id", value)

    @_builtins.property
    @pulumi.getter(name="mcpServers")
    def mcp_servers(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]]]:
        """
        Named MCP servers the agent can reach. Write-only.
        """
        return pulumi.get(self, "mcp_servers")

    @mcp_servers.setter
    def mcp_servers(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentMcpServerArgs']]]]):
        pulumi.set(self, "mcp_servers", value)

    @_builtins.property
    @pulumi.getter
    def model(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Model the agent uses. Write-only.
        """
        return pulumi.get(self, "model")

    @model.setter
    def model(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "model", value)

    @_builtins.property
    @pulumi.getter(name="repoBranch")
    def repo_branch(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Branch of the generated agent repository.
        """
        return pulumi.get(self, "repo_branch")

    @repo_branch.setter
    def repo_branch(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "repo_branch", value)

    @_builtins.property
    @pulumi.getter(name="repoName")
    def repo_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the generated agent repository.
        """
        return pulumi.get(self, "repo_name")

    @repo_name.setter
    def repo_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "repo_name", value)

    @_builtins.property
    @pulumi.getter(name="repoOwner")
    def repo_owner(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Owner of the generated agent repository.
        """
        return pulumi.get(self, "repo_owner")

    @repo_owner.setter
    def repo_owner(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "repo_owner", value)

    @_builtins.property
    @pulumi.getter(name="repoPath")
    def repo_path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Path within the generated agent repository.
        """
        return pulumi.get(self, "repo_path")

    @repo_path.setter
    def repo_path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "repo_path", value)

    @_builtins.property
    @pulumi.getter(name="runtimeAgentId")
    def runtime_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Runtime agent ID the deployment registers as.
        """
        return pulumi.get(self, "runtime_agent_id")

    @runtime_agent_id.setter
    def runtime_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "runtime_agent_id", value)

    @_builtins.property
    @pulumi.getter
    def skills(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentSkillArgs']]]]:
        """
        Skills bundled into the agent. Write-only.
        """
        return pulumi.get(self, "skills")

    @skills.setter
    def skills(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['HostedAgentSkillArgs']]]]):
        pulumi.set(self, "skills", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Deployment status (`online`, `offline`, `draft`, `deploying`, `deploy_failed`).
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Last-update timestamp.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)

    @_builtins.property
    @pulumi.getter
    def values(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Resolved deployment values, as a JSON object.
        """
        return pulumi.get(self, "values")

    @values.setter
    def values(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "values", value)

    @_builtins.property
    @pulumi.getter(name="waitForOnline")
    def wait_for_online(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether create/update should block until the hosted agent reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted — useful for agents that are intentionally left in `draft`/scaled to zero and will never heartbeat. While the agent is not yet online, a failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout. Updating an agent that is already online returns as soon as it reports `online`, which the revision already running does, so the new revision's rollout is not waited on.
        """
        return pulumi.get(self, "wait_for_online")

    @wait_for_online.setter
    def wait_for_online(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "wait_for_online", value)

    @_builtins.property
    @pulumi.getter(name="waitTimeout")
    def wait_timeout(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Maximum time to wait for the agent to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `wait_for_online` is `true`.
        """
        return pulumi.get(self, "wait_timeout")

    @wait_timeout.setter
    def wait_timeout(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "wait_timeout", value)


@pulumi.type_token("agentops:index/hostedAgent:HostedAgent")
class HostedAgent(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 agents: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentAgentArgs', 'HostedAgentAgentArgsDict']]]]] = None,
                 capabilities: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]] = None,
                 commit_message: pulumi.Input[Optional[_builtins.str]] = None,
                 credential_ref: pulumi.Input[Optional[_builtins.str]] = None,
                 customer: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 image: pulumi.Input[Optional[Union['HostedAgentImageArgs', 'HostedAgentImageArgsDict']]] = None,
                 instructions: pulumi.Input[Optional[_builtins.str]] = None,
                 mcp_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mcp_servers: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentMcpServerArgs', 'HostedAgentMcpServerArgsDict']]]]] = None,
                 model: pulumi.Input[Optional[_builtins.str]] = None,
                 skills: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentSkillArgs', 'HostedAgentSkillArgsDict']]]]] = None,
                 wait_for_online: pulumi.Input[Optional[_builtins.bool]] = None,
                 wait_timeout: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A Komodor-hosted agent: a managed agent deployment built from instructions, skills and an optional container image. Deployment-spec fields are write-only — the API does not return them, so out-of-band changes to them are not detected. Destroying an agent that deployed successfully archives it first where the account requires that, and waits for the archive to finish before deleting.

        ## Import

        The `pulumi import` command can be used, for example:

        Hosted agents are imported as "customer/agent_id". Write-only spec fields
        (instructions, model, skills, ...) must be supplied in configuration afterwards.

        ```sh
        $ pulumi import agentops:index/hostedAgent:HostedAgent triage acme/incident-triage
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] agent_id: Stable agent identifier within the customer. Changing this forces a new hosted agent.
        :param pulumi.Input[Sequence[pulumi.Input[Union['HostedAgentAgentArgs', 'HostedAgentAgentArgsDict']]]] agents: Subagents bundled into the agent. Write-only.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.bool]]] capabilities: Capability toggles for the agent. Write-only.
        :param pulumi.Input[_builtins.str] commit_message: Commit message recorded when the agent's generated repo is updated. Write-only.
        :param pulumi.Input[_builtins.str] credential_ref: Reference to the credential the agent runs with. Write-only.
        :param pulumi.Input[_builtins.str] customer: Customer/tenant the agent is hosted for. Optional: the server derives it from your account when omitted. Changing this forces a new hosted agent.
        :param pulumi.Input[_builtins.str] display_name: Human-readable name. Write-only.
        :param pulumi.Input[Union['HostedAgentImageArgs', 'HostedAgentImageArgsDict']] image: Container image overrides for the agent runtime. Write-only.
        :param pulumi.Input[_builtins.str] instructions: System instructions for the agent. Write-only.
        :param pulumi.Input[_builtins.str] mcp_group_id: ID of an MCP gateway group to attach. Write-only.
        :param pulumi.Input[Sequence[pulumi.Input[Union['HostedAgentMcpServerArgs', 'HostedAgentMcpServerArgsDict']]]] mcp_servers: Named MCP servers the agent can reach. Write-only.
        :param pulumi.Input[_builtins.str] model: Model the agent uses. Write-only.
        :param pulumi.Input[Sequence[pulumi.Input[Union['HostedAgentSkillArgs', 'HostedAgentSkillArgsDict']]]] skills: Skills bundled into the agent. Write-only.
        :param pulumi.Input[_builtins.bool] wait_for_online: Whether create/update should block until the hosted agent reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted — useful for agents that are intentionally left in `draft`/scaled to zero and will never heartbeat. While the agent is not yet online, a failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout. Updating an agent that is already online returns as soon as it reports `online`, which the revision already running does, so the new revision's rollout is not waited on.
        :param pulumi.Input[_builtins.str] wait_timeout: Maximum time to wait for the agent to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `wait_for_online` is `true`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: HostedAgentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Komodor-hosted agent: a managed agent deployment built from instructions, skills and an optional container image. Deployment-spec fields are write-only — the API does not return them, so out-of-band changes to them are not detected. Destroying an agent that deployed successfully archives it first where the account requires that, and waits for the archive to finish before deleting.

        ## Import

        The `pulumi import` command can be used, for example:

        Hosted agents are imported as "customer/agent_id". Write-only spec fields
        (instructions, model, skills, ...) must be supplied in configuration afterwards.

        ```sh
        $ pulumi import agentops:index/hostedAgent:HostedAgent triage acme/incident-triage
        ```


        :param str resource_name: The name of the resource.
        :param HostedAgentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(HostedAgentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 agents: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentAgentArgs', 'HostedAgentAgentArgsDict']]]]] = None,
                 capabilities: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]] = None,
                 commit_message: pulumi.Input[Optional[_builtins.str]] = None,
                 credential_ref: pulumi.Input[Optional[_builtins.str]] = None,
                 customer: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 image: pulumi.Input[Optional[Union['HostedAgentImageArgs', 'HostedAgentImageArgsDict']]] = None,
                 instructions: pulumi.Input[Optional[_builtins.str]] = None,
                 mcp_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 mcp_servers: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentMcpServerArgs', 'HostedAgentMcpServerArgsDict']]]]] = None,
                 model: pulumi.Input[Optional[_builtins.str]] = None,
                 skills: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentSkillArgs', 'HostedAgentSkillArgsDict']]]]] = None,
                 wait_for_online: pulumi.Input[Optional[_builtins.bool]] = None,
                 wait_timeout: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = HostedAgentArgs.__new__(HostedAgentArgs)

            if agent_id is None and not opts.urn:
                raise TypeError("Missing required property 'agent_id'")
            __props__.__dict__["agent_id"] = agent_id
            __props__.__dict__["agents"] = agents
            __props__.__dict__["capabilities"] = capabilities
            __props__.__dict__["commit_message"] = commit_message
            if credential_ref is None and not opts.urn:
                raise TypeError("Missing required property 'credential_ref'")
            __props__.__dict__["credential_ref"] = credential_ref
            __props__.__dict__["customer"] = customer
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["image"] = image
            if instructions is None and not opts.urn:
                raise TypeError("Missing required property 'instructions'")
            __props__.__dict__["instructions"] = instructions
            __props__.__dict__["mcp_group_id"] = mcp_group_id
            __props__.__dict__["mcp_servers"] = mcp_servers
            __props__.__dict__["model"] = model
            __props__.__dict__["skills"] = skills
            __props__.__dict__["wait_for_online"] = wait_for_online
            __props__.__dict__["wait_timeout"] = wait_timeout
            __props__.__dict__["created_at"] = None
            __props__.__dict__["identity"] = None
            __props__.__dict__["last_commit_sha"] = None
            __props__.__dict__["repo_branch"] = None
            __props__.__dict__["repo_name"] = None
            __props__.__dict__["repo_owner"] = None
            __props__.__dict__["repo_path"] = None
            __props__.__dict__["runtime_agent_id"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["values"] = None
        super(HostedAgent, __self__).__init__(
            'agentops:index/hostedAgent:HostedAgent',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            agent_id: pulumi.Input[Optional[_builtins.str]] = None,
            agents: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentAgentArgs', 'HostedAgentAgentArgsDict']]]]] = None,
            capabilities: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.bool]]]] = None,
            commit_message: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            credential_ref: pulumi.Input[Optional[_builtins.str]] = None,
            customer: pulumi.Input[Optional[_builtins.str]] = None,
            display_name: pulumi.Input[Optional[_builtins.str]] = None,
            identity: pulumi.Input[Optional[_builtins.str]] = None,
            image: pulumi.Input[Optional[Union['HostedAgentImageArgs', 'HostedAgentImageArgsDict']]] = None,
            instructions: pulumi.Input[Optional[_builtins.str]] = None,
            last_commit_sha: pulumi.Input[Optional[_builtins.str]] = None,
            mcp_group_id: pulumi.Input[Optional[_builtins.str]] = None,
            mcp_servers: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentMcpServerArgs', 'HostedAgentMcpServerArgsDict']]]]] = None,
            model: pulumi.Input[Optional[_builtins.str]] = None,
            repo_branch: pulumi.Input[Optional[_builtins.str]] = None,
            repo_name: pulumi.Input[Optional[_builtins.str]] = None,
            repo_owner: pulumi.Input[Optional[_builtins.str]] = None,
            repo_path: pulumi.Input[Optional[_builtins.str]] = None,
            runtime_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
            skills: pulumi.Input[Optional[Sequence[pulumi.Input[Union['HostedAgentSkillArgs', 'HostedAgentSkillArgsDict']]]]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None,
            values: pulumi.Input[Optional[_builtins.str]] = None,
            wait_for_online: pulumi.Input[Optional[_builtins.bool]] = None,
            wait_timeout: pulumi.Input[Optional[_builtins.str]] = None) -> 'HostedAgent':
        """
        Get an existing HostedAgent resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] agent_id: Stable agent identifier within the customer. Changing this forces a new hosted agent.
        :param pulumi.Input[Sequence[pulumi.Input[Union['HostedAgentAgentArgs', 'HostedAgentAgentArgsDict']]]] agents: Subagents bundled into the agent. Write-only.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.bool]]] capabilities: Capability toggles for the agent. Write-only.
        :param pulumi.Input[_builtins.str] commit_message: Commit message recorded when the agent's generated repo is updated. Write-only.
        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] credential_ref: Reference to the credential the agent runs with. Write-only.
        :param pulumi.Input[_builtins.str] customer: Customer/tenant the agent is hosted for. Optional: the server derives it from your account when omitted. Changing this forces a new hosted agent.
        :param pulumi.Input[_builtins.str] display_name: Human-readable name. Write-only.
        :param pulumi.Input[_builtins.str] identity: Resolved runtime identity of the hosted agent.
        :param pulumi.Input[Union['HostedAgentImageArgs', 'HostedAgentImageArgsDict']] image: Container image overrides for the agent runtime. Write-only.
        :param pulumi.Input[_builtins.str] instructions: System instructions for the agent. Write-only.
        :param pulumi.Input[_builtins.str] last_commit_sha: SHA of the most recent commit to the generated repository.
        :param pulumi.Input[_builtins.str] mcp_group_id: ID of an MCP gateway group to attach. Write-only.
        :param pulumi.Input[Sequence[pulumi.Input[Union['HostedAgentMcpServerArgs', 'HostedAgentMcpServerArgsDict']]]] mcp_servers: Named MCP servers the agent can reach. Write-only.
        :param pulumi.Input[_builtins.str] model: Model the agent uses. Write-only.
        :param pulumi.Input[_builtins.str] repo_branch: Branch of the generated agent repository.
        :param pulumi.Input[_builtins.str] repo_name: Name of the generated agent repository.
        :param pulumi.Input[_builtins.str] repo_owner: Owner of the generated agent repository.
        :param pulumi.Input[_builtins.str] repo_path: Path within the generated agent repository.
        :param pulumi.Input[_builtins.str] runtime_agent_id: Runtime agent ID the deployment registers as.
        :param pulumi.Input[Sequence[pulumi.Input[Union['HostedAgentSkillArgs', 'HostedAgentSkillArgsDict']]]] skills: Skills bundled into the agent. Write-only.
        :param pulumi.Input[_builtins.str] status: Deployment status (`online`, `offline`, `draft`, `deploying`, `deploy_failed`).
        :param pulumi.Input[_builtins.str] updated_at: Last-update timestamp.
        :param pulumi.Input[_builtins.str] values: Resolved deployment values, as a JSON object.
        :param pulumi.Input[_builtins.bool] wait_for_online: Whether create/update should block until the hosted agent reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted — useful for agents that are intentionally left in `draft`/scaled to zero and will never heartbeat. While the agent is not yet online, a failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout. Updating an agent that is already online returns as soon as it reports `online`, which the revision already running does, so the new revision's rollout is not waited on.
        :param pulumi.Input[_builtins.str] wait_timeout: Maximum time to wait for the agent to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `wait_for_online` is `true`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _HostedAgentState.__new__(_HostedAgentState)

        __props__.__dict__["agent_id"] = agent_id
        __props__.__dict__["agents"] = agents
        __props__.__dict__["capabilities"] = capabilities
        __props__.__dict__["commit_message"] = commit_message
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["credential_ref"] = credential_ref
        __props__.__dict__["customer"] = customer
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["identity"] = identity
        __props__.__dict__["image"] = image
        __props__.__dict__["instructions"] = instructions
        __props__.__dict__["last_commit_sha"] = last_commit_sha
        __props__.__dict__["mcp_group_id"] = mcp_group_id
        __props__.__dict__["mcp_servers"] = mcp_servers
        __props__.__dict__["model"] = model
        __props__.__dict__["repo_branch"] = repo_branch
        __props__.__dict__["repo_name"] = repo_name
        __props__.__dict__["repo_owner"] = repo_owner
        __props__.__dict__["repo_path"] = repo_path
        __props__.__dict__["runtime_agent_id"] = runtime_agent_id
        __props__.__dict__["skills"] = skills
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        __props__.__dict__["values"] = values
        __props__.__dict__["wait_for_online"] = wait_for_online
        __props__.__dict__["wait_timeout"] = wait_timeout
        return HostedAgent(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="agentId")
    def agent_id(self) -> pulumi.Output[_builtins.str]:
        """
        Stable agent identifier within the customer. Changing this forces a new hosted agent.
        """
        return pulumi.get(self, "agent_id")

    @_builtins.property
    @pulumi.getter
    def agents(self) -> pulumi.Output[Optional[Sequence['outputs.HostedAgentAgent']]]:
        """
        Subagents bundled into the agent. Write-only.
        """
        return pulumi.get(self, "agents")

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Output[Optional[Mapping[str, _builtins.bool]]]:
        """
        Capability toggles for the agent. Write-only.
        """
        return pulumi.get(self, "capabilities")

    @_builtins.property
    @pulumi.getter(name="commitMessage")
    def commit_message(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Commit message recorded when the agent's generated repo is updated. Write-only.
        """
        return pulumi.get(self, "commit_message")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="credentialRef")
    def credential_ref(self) -> pulumi.Output[_builtins.str]:
        """
        Reference to the credential the agent runs with. Write-only.
        """
        return pulumi.get(self, "credential_ref")

    @_builtins.property
    @pulumi.getter
    def customer(self) -> pulumi.Output[_builtins.str]:
        """
        Customer/tenant the agent is hosted for. Optional: the server derives it from your account when omitted. Changing this forces a new hosted agent.
        """
        return pulumi.get(self, "customer")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Human-readable name. Write-only.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def identity(self) -> pulumi.Output[_builtins.str]:
        """
        Resolved runtime identity of the hosted agent.
        """
        return pulumi.get(self, "identity")

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Output[Optional['outputs.HostedAgentImage']]:
        """
        Container image overrides for the agent runtime. Write-only.
        """
        return pulumi.get(self, "image")

    @_builtins.property
    @pulumi.getter
    def instructions(self) -> pulumi.Output[_builtins.str]:
        """
        System instructions for the agent. Write-only.
        """
        return pulumi.get(self, "instructions")

    @_builtins.property
    @pulumi.getter(name="lastCommitSha")
    def last_commit_sha(self) -> pulumi.Output[_builtins.str]:
        """
        SHA of the most recent commit to the generated repository.
        """
        return pulumi.get(self, "last_commit_sha")

    @_builtins.property
    @pulumi.getter(name="mcpGroupId")
    def mcp_group_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        ID of an MCP gateway group to attach. Write-only.
        """
        return pulumi.get(self, "mcp_group_id")

    @_builtins.property
    @pulumi.getter(name="mcpServers")
    def mcp_servers(self) -> pulumi.Output[Optional[Sequence['outputs.HostedAgentMcpServer']]]:
        """
        Named MCP servers the agent can reach. Write-only.
        """
        return pulumi.get(self, "mcp_servers")

    @_builtins.property
    @pulumi.getter
    def model(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Model the agent uses. Write-only.
        """
        return pulumi.get(self, "model")

    @_builtins.property
    @pulumi.getter(name="repoBranch")
    def repo_branch(self) -> pulumi.Output[_builtins.str]:
        """
        Branch of the generated agent repository.
        """
        return pulumi.get(self, "repo_branch")

    @_builtins.property
    @pulumi.getter(name="repoName")
    def repo_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the generated agent repository.
        """
        return pulumi.get(self, "repo_name")

    @_builtins.property
    @pulumi.getter(name="repoOwner")
    def repo_owner(self) -> pulumi.Output[_builtins.str]:
        """
        Owner of the generated agent repository.
        """
        return pulumi.get(self, "repo_owner")

    @_builtins.property
    @pulumi.getter(name="repoPath")
    def repo_path(self) -> pulumi.Output[_builtins.str]:
        """
        Path within the generated agent repository.
        """
        return pulumi.get(self, "repo_path")

    @_builtins.property
    @pulumi.getter(name="runtimeAgentId")
    def runtime_agent_id(self) -> pulumi.Output[_builtins.str]:
        """
        Runtime agent ID the deployment registers as.
        """
        return pulumi.get(self, "runtime_agent_id")

    @_builtins.property
    @pulumi.getter
    def skills(self) -> pulumi.Output[Optional[Sequence['outputs.HostedAgentSkill']]]:
        """
        Skills bundled into the agent. Write-only.
        """
        return pulumi.get(self, "skills")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Deployment status (`online`, `offline`, `draft`, `deploying`, `deploy_failed`).
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Last-update timestamp.
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def values(self) -> pulumi.Output[_builtins.str]:
        """
        Resolved deployment values, as a JSON object.
        """
        return pulumi.get(self, "values")

    @_builtins.property
    @pulumi.getter(name="waitForOnline")
    def wait_for_online(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether create/update should block until the hosted agent reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted — useful for agents that are intentionally left in `draft`/scaled to zero and will never heartbeat. While the agent is not yet online, a failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout. Updating an agent that is already online returns as soon as it reports `online`, which the revision already running does, so the new revision's rollout is not waited on.
        """
        return pulumi.get(self, "wait_for_online")

    @_builtins.property
    @pulumi.getter(name="waitTimeout")
    def wait_timeout(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Maximum time to wait for the agent to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `wait_for_online` is `true`.
        """
        return pulumi.get(self, "wait_timeout")

