# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['IntegrationConnectionArgs', 'IntegrationConnection']

@pulumi.input_type
class IntegrationConnectionArgs:
    def __init__(__self__, *,
                 display_name: pulumi.Input[_builtins.str],
                 provider_key: pulumi.Input[_builtins.str],
                 credentials: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 metadata: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a IntegrationConnection resource.

        :param pulumi.Input[_builtins.str] display_name: Human-readable connection name. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] provider_key: Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] credentials: Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] metadata: Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
        """
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "provider_key", provider_key)
        if credentials is not None:
            pulumi.set(__self__, "credentials", credentials)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str]:
        """
        Human-readable connection name. Changing this forces a new connection.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="providerKey")
    def provider_key(self) -> pulumi.Input[_builtins.str]:
        """
        Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
        """
        return pulumi.get(self, "provider_key")

    @provider_key.setter
    def provider_key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "provider_key", value)

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
        """
        return pulumi.get(self, "credentials")

    @credentials.setter
    def credentials(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "credentials", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "metadata", value)


@pulumi.input_type
class _IntegrationConnectionState:
    def __init__(__self__, *,
                 auth_config_key: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 created_by: pulumi.Input[Optional[_builtins.str]] = None,
                 credentials: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 credentials_type: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 external_connection_id: pulumi.Input[Optional[_builtins.str]] = None,
                 last_used_at: pulumi.Input[Optional[_builtins.str]] = None,
                 last_validated_at: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional[_builtins.str]] = None,
                 provider_key: pulumi.Input[Optional[_builtins.str]] = None,
                 scopes: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering IntegrationConnection resources.

        :param pulumi.Input[_builtins.str] auth_config_key: Auth configuration key assigned to the connection.
        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] created_by: Identifier of the principal that created the connection.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] credentials: Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] credentials_type: Type of credentials backing the connection.
        :param pulumi.Input[_builtins.str] display_name: Human-readable connection name. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] external_connection_id: Provider-side connection identifier.
        :param pulumi.Input[_builtins.str] last_used_at: Timestamp the connection was last used.
        :param pulumi.Input[_builtins.str] last_validated_at: Timestamp the connection was last validated.
        :param pulumi.Input[_builtins.str] metadata: Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] provider_key: Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] scopes: Scopes granted to the connection.
        :param pulumi.Input[_builtins.str] status: Connection status.
        :param pulumi.Input[_builtins.str] updated_at: Last-update timestamp.
        """
        if auth_config_key is not None:
            pulumi.set(__self__, "auth_config_key", auth_config_key)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if created_by is not None:
            pulumi.set(__self__, "created_by", created_by)
        if credentials is not None:
            pulumi.set(__self__, "credentials", credentials)
        if credentials_type is not None:
            pulumi.set(__self__, "credentials_type", credentials_type)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if external_connection_id is not None:
            pulumi.set(__self__, "external_connection_id", external_connection_id)
        if last_used_at is not None:
            pulumi.set(__self__, "last_used_at", last_used_at)
        if last_validated_at is not None:
            pulumi.set(__self__, "last_validated_at", last_validated_at)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if provider_key is not None:
            pulumi.set(__self__, "provider_key", provider_key)
        if scopes is not None:
            pulumi.set(__self__, "scopes", scopes)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="authConfigKey")
    def auth_config_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Auth configuration key assigned to the connection.
        """
        return pulumi.get(self, "auth_config_key")

    @auth_config_key.setter
    def auth_config_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "auth_config_key", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identifier of the principal that created the connection.
        """
        return pulumi.get(self, "created_by")

    @created_by.setter
    def created_by(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_by", value)

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
        """
        return pulumi.get(self, "credentials")

    @credentials.setter
    def credentials(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "credentials", value)

    @_builtins.property
    @pulumi.getter(name="credentialsType")
    def credentials_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Type of credentials backing the connection.
        """
        return pulumi.get(self, "credentials_type")

    @credentials_type.setter
    def credentials_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "credentials_type", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable connection name. Changing this forces a new connection.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="externalConnectionId")
    def external_connection_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Provider-side connection identifier.
        """
        return pulumi.get(self, "external_connection_id")

    @external_connection_id.setter
    def external_connection_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "external_connection_id", value)

    @_builtins.property
    @pulumi.getter(name="lastUsedAt")
    def last_used_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timestamp the connection was last used.
        """
        return pulumi.get(self, "last_used_at")

    @last_used_at.setter
    def last_used_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_used_at", value)

    @_builtins.property
    @pulumi.getter(name="lastValidatedAt")
    def last_validated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timestamp the connection was last validated.
        """
        return pulumi.get(self, "last_validated_at")

    @last_validated_at.setter
    def last_validated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_validated_at", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter(name="providerKey")
    def provider_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
        """
        return pulumi.get(self, "provider_key")

    @provider_key.setter
    def provider_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "provider_key", value)

    @_builtins.property
    @pulumi.getter
    def scopes(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Scopes granted to the connection.
        """
        return pulumi.get(self, "scopes")

    @scopes.setter
    def scopes(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "scopes", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Connection status.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Last-update timestamp.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("agentops:index/integrationConnection:IntegrationConnection")
class IntegrationConnection(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 credentials: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional[_builtins.str]] = None,
                 provider_key: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        An AgentOps integration connection. Connections cannot be updated in place: changing any argument forces a new connection. Credentials are write-only and never returned by the API.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_agentops as agentops

        github = agentops.IntegrationConnection("github",
            provider_key="github",
            display_name="GitHub (org)",
            credentials={
                "token": github_token,
            },
            metadata=json.dumps({
                "org": "komodorio",
            }))
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Integration connections are imported by their id.

        ```sh
        $ pulumi import agentops:index/integrationConnection:IntegrationConnection github conn_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] credentials: Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] display_name: Human-readable connection name. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] metadata: Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] provider_key: Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IntegrationConnectionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An AgentOps integration connection. Connections cannot be updated in place: changing any argument forces a new connection. Credentials are write-only and never returned by the API.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_agentops as agentops

        github = agentops.IntegrationConnection("github",
            provider_key="github",
            display_name="GitHub (org)",
            credentials={
                "token": github_token,
            },
            metadata=json.dumps({
                "org": "komodorio",
            }))
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Integration connections are imported by their id.

        ```sh
        $ pulumi import agentops:index/integrationConnection:IntegrationConnection github conn_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param IntegrationConnectionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IntegrationConnectionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 credentials: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata: pulumi.Input[Optional[_builtins.str]] = None,
                 provider_key: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IntegrationConnectionArgs.__new__(IntegrationConnectionArgs)

            __props__.__dict__["credentials"] = None if credentials is None else pulumi.Output.secret(credentials)
            if display_name is None and not opts.urn:
                raise TypeError("Missing required property 'display_name'")
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["metadata"] = metadata
            if provider_key is None and not opts.urn:
                raise TypeError("Missing required property 'provider_key'")
            __props__.__dict__["provider_key"] = provider_key
            __props__.__dict__["auth_config_key"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["created_by"] = None
            __props__.__dict__["credentials_type"] = None
            __props__.__dict__["external_connection_id"] = None
            __props__.__dict__["last_used_at"] = None
            __props__.__dict__["last_validated_at"] = None
            __props__.__dict__["scopes"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["updated_at"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["credentials"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(IntegrationConnection, __self__).__init__(
            'agentops:index/integrationConnection:IntegrationConnection',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auth_config_key: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            created_by: pulumi.Input[Optional[_builtins.str]] = None,
            credentials: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            credentials_type: pulumi.Input[Optional[_builtins.str]] = None,
            display_name: pulumi.Input[Optional[_builtins.str]] = None,
            external_connection_id: pulumi.Input[Optional[_builtins.str]] = None,
            last_used_at: pulumi.Input[Optional[_builtins.str]] = None,
            last_validated_at: pulumi.Input[Optional[_builtins.str]] = None,
            metadata: pulumi.Input[Optional[_builtins.str]] = None,
            provider_key: pulumi.Input[Optional[_builtins.str]] = None,
            scopes: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None) -> 'IntegrationConnection':
        """
        Get an existing IntegrationConnection resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] auth_config_key: Auth configuration key assigned to the connection.
        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] created_by: Identifier of the principal that created the connection.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] credentials: Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] credentials_type: Type of credentials backing the connection.
        :param pulumi.Input[_builtins.str] display_name: Human-readable connection name. Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] external_connection_id: Provider-side connection identifier.
        :param pulumi.Input[_builtins.str] last_used_at: Timestamp the connection was last used.
        :param pulumi.Input[_builtins.str] last_validated_at: Timestamp the connection was last validated.
        :param pulumi.Input[_builtins.str] metadata: Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
        :param pulumi.Input[_builtins.str] provider_key: Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] scopes: Scopes granted to the connection.
        :param pulumi.Input[_builtins.str] status: Connection status.
        :param pulumi.Input[_builtins.str] updated_at: Last-update timestamp.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IntegrationConnectionState.__new__(_IntegrationConnectionState)

        __props__.__dict__["auth_config_key"] = auth_config_key
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["created_by"] = created_by
        __props__.__dict__["credentials"] = credentials
        __props__.__dict__["credentials_type"] = credentials_type
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["external_connection_id"] = external_connection_id
        __props__.__dict__["last_used_at"] = last_used_at
        __props__.__dict__["last_validated_at"] = last_validated_at
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["provider_key"] = provider_key
        __props__.__dict__["scopes"] = scopes
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        return IntegrationConnection(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="authConfigKey")
    def auth_config_key(self) -> pulumi.Output[_builtins.str]:
        """
        Auth configuration key assigned to the connection.
        """
        return pulumi.get(self, "auth_config_key")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier of the principal that created the connection.
        """
        return pulumi.get(self, "created_by")

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
        """
        return pulumi.get(self, "credentials")

    @_builtins.property
    @pulumi.getter(name="credentialsType")
    def credentials_type(self) -> pulumi.Output[_builtins.str]:
        """
        Type of credentials backing the connection.
        """
        return pulumi.get(self, "credentials_type")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable connection name. Changing this forces a new connection.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="externalConnectionId")
    def external_connection_id(self) -> pulumi.Output[_builtins.str]:
        """
        Provider-side connection identifier.
        """
        return pulumi.get(self, "external_connection_id")

    @_builtins.property
    @pulumi.getter(name="lastUsedAt")
    def last_used_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp the connection was last used.
        """
        return pulumi.get(self, "last_used_at")

    @_builtins.property
    @pulumi.getter(name="lastValidatedAt")
    def last_validated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp the connection was last validated.
        """
        return pulumi.get(self, "last_validated_at")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[_builtins.str]:
        """
        Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter(name="providerKey")
    def provider_key(self) -> pulumi.Output[_builtins.str]:
        """
        Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
        """
        return pulumi.get(self, "provider_key")

    @_builtins.property
    @pulumi.getter
    def scopes(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Scopes granted to the connection.
        """
        return pulumi.get(self, "scopes")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Connection status.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Last-update timestamp.
        """
        return pulumi.get(self, "updated_at")

