# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['MemberArgs', 'Member']

@pulumi.input_type
class MemberArgs:
    def __init__(__self__, *,
                 email: pulumi.Input[_builtins.str],
                 full_name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Member resource.

        :param pulumi.Input[_builtins.str] email: Email address of the member to invite.
        :param pulumi.Input[_builtins.str] full_name: Full name of the member.
        """
        pulumi.set(__self__, "email", email)
        if full_name is not None:
            pulumi.set(__self__, "full_name", full_name)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[_builtins.str]:
        """
        Email address of the member to invite.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="fullName")
    def full_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Full name of the member.
        """
        return pulumi.get(self, "full_name")

    @full_name.setter
    def full_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "full_name", value)


@pulumi.input_type
class _MemberState:
    def __init__(__self__, *,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 full_name: pulumi.Input[Optional[_builtins.str]] = None,
                 last_login_at: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 user_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Member resources.

        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] display_name: Human-readable member name.
        :param pulumi.Input[_builtins.str] email: Email address of the member to invite.
        :param pulumi.Input[_builtins.str] full_name: Full name of the member.
        :param pulumi.Input[_builtins.str] last_login_at: Timestamp of the member's last login.
        :param pulumi.Input[_builtins.str] status: Member status.
        :param pulumi.Input[_builtins.str] user_id: User identifier associated with the member.
        """
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if full_name is not None:
            pulumi.set(__self__, "full_name", full_name)
        if last_login_at is not None:
            pulumi.set(__self__, "last_login_at", last_login_at)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if user_id is not None:
            pulumi.set(__self__, "user_id", user_id)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable member name.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Email address of the member to invite.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="fullName")
    def full_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Full name of the member.
        """
        return pulumi.get(self, "full_name")

    @full_name.setter
    def full_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "full_name", value)

    @_builtins.property
    @pulumi.getter(name="lastLoginAt")
    def last_login_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timestamp of the member's last login.
        """
        return pulumi.get(self, "last_login_at")

    @last_login_at.setter
    def last_login_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_login_at", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Member status.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        User identifier associated with the member.
        """
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user_id", value)


@pulumi.type_token("agentops:index/member:Member")
class Member(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 full_name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        An AgentOps member. Members cannot be updated in place; changing any argument forces a new member.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_agentops as agentops

        dev = agentops.Member("dev",
            email="dev@example.com",
            full_name="Dev One")
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Members are imported by their principal id.

        ```sh
        $ pulumi import agentops:index/member:Member dev mbr_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] email: Email address of the member to invite.
        :param pulumi.Input[_builtins.str] full_name: Full name of the member.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: MemberArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An AgentOps member. Members cannot be updated in place; changing any argument forces a new member.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_agentops as agentops

        dev = agentops.Member("dev",
            email="dev@example.com",
            full_name="Dev One")
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Members are imported by their principal id.

        ```sh
        $ pulumi import agentops:index/member:Member dev mbr_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param MemberArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(MemberArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 full_name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = MemberArgs.__new__(MemberArgs)

            if email is None and not opts.urn:
                raise TypeError("Missing required property 'email'")
            __props__.__dict__["email"] = email
            __props__.__dict__["full_name"] = full_name
            __props__.__dict__["created_at"] = None
            __props__.__dict__["display_name"] = None
            __props__.__dict__["last_login_at"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["user_id"] = None
        super(Member, __self__).__init__(
            'agentops:index/member:Member',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            display_name: pulumi.Input[Optional[_builtins.str]] = None,
            email: pulumi.Input[Optional[_builtins.str]] = None,
            full_name: pulumi.Input[Optional[_builtins.str]] = None,
            last_login_at: pulumi.Input[Optional[_builtins.str]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            user_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'Member':
        """
        Get an existing Member resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] display_name: Human-readable member name.
        :param pulumi.Input[_builtins.str] email: Email address of the member to invite.
        :param pulumi.Input[_builtins.str] full_name: Full name of the member.
        :param pulumi.Input[_builtins.str] last_login_at: Timestamp of the member's last login.
        :param pulumi.Input[_builtins.str] status: Member status.
        :param pulumi.Input[_builtins.str] user_id: User identifier associated with the member.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _MemberState.__new__(_MemberState)

        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["email"] = email
        __props__.__dict__["full_name"] = full_name
        __props__.__dict__["last_login_at"] = last_login_at
        __props__.__dict__["status"] = status
        __props__.__dict__["user_id"] = user_id
        return Member(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable member name.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Output[_builtins.str]:
        """
        Email address of the member to invite.
        """
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter(name="fullName")
    def full_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Full name of the member.
        """
        return pulumi.get(self, "full_name")

    @_builtins.property
    @pulumi.getter(name="lastLoginAt")
    def last_login_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of the member's last login.
        """
        return pulumi.get(self, "last_login_at")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Member status.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.str]:
        """
        User identifier associated with the member.
        """
        return pulumi.get(self, "user_id")

