# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'HostedAgentAgent',
    'HostedAgentImage',
    'HostedAgentMcpServer',
    'HostedAgentSkill',
    'IncidentPipelineAlertSource',
    'IncidentPipelineDeliveryConfig',
    'IncidentPipelineDeliveryConfigSlack',
    'IncidentPipelineOrchestratorBinding',
    'IncidentPipelineRoutingRule',
    'IncidentPipelineSpecialistBinding',
    'OutpostAllowlist',
    'ReviewWorkflowManualSetup',
    'ReviewWorkflowRepo',
    'ReviewWorkflowRepoStatus',
    'GetCapabilitiesCapabilityResult',
    'GetIntegrationCatalogEntryResult',
    'GetResourceTypesResourceTypeResult',
    'GetReviewersReviewerResult',
    'GetSkillsSkillResult',
    'GetWorkerCatalogEntryResult',
]

@pulumi.output_type
class HostedAgentAgent(dict):
    def __init__(__self__, *,
                 content: _builtins.str,
                 id: _builtins.str):
        """
        :param _builtins.str content: Subagent content.
        :param _builtins.str id: Subagent identifier.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        Subagent content.
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Subagent identifier.
        """
        return pulumi.get(self, "id")


@pulumi.output_type
class HostedAgentImage(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "pullPolicy":
            suggest = "pull_policy"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in HostedAgentImage. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        HostedAgentImage.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        HostedAgentImage.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 pull_policy: Optional[_builtins.str] = None,
                 registry: Optional[_builtins.str] = None,
                 repository: Optional[_builtins.str] = None,
                 tag: Optional[_builtins.str] = None):
        """
        :param _builtins.str pull_policy: Image pull policy.
        :param _builtins.str registry: Image registry host.
        :param _builtins.str repository: Image repository.
        :param _builtins.str tag: Image tag.
        """
        if pull_policy is not None:
            pulumi.set(__self__, "pull_policy", pull_policy)
        if registry is not None:
            pulumi.set(__self__, "registry", registry)
        if repository is not None:
            pulumi.set(__self__, "repository", repository)
        if tag is not None:
            pulumi.set(__self__, "tag", tag)

    @_builtins.property
    @pulumi.getter(name="pullPolicy")
    def pull_policy(self) -> Optional[_builtins.str]:
        """
        Image pull policy.
        """
        return pulumi.get(self, "pull_policy")

    @_builtins.property
    @pulumi.getter
    def registry(self) -> Optional[_builtins.str]:
        """
        Image registry host.
        """
        return pulumi.get(self, "registry")

    @_builtins.property
    @pulumi.getter
    def repository(self) -> Optional[_builtins.str]:
        """
        Image repository.
        """
        return pulumi.get(self, "repository")

    @_builtins.property
    @pulumi.getter
    def tag(self) -> Optional[_builtins.str]:
        """
        Image tag.
        """
        return pulumi.get(self, "tag")


@pulumi.output_type
class HostedAgentMcpServer(dict):
    def __init__(__self__, *,
                 name: _builtins.str):
        """
        :param _builtins.str name: MCP server name.
        """
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        MCP server name.
        """
        return pulumi.get(self, "name")


@pulumi.output_type
class HostedAgentSkill(dict):
    def __init__(__self__, *,
                 content: _builtins.str,
                 id: _builtins.str):
        """
        :param _builtins.str content: Skill content.
        :param _builtins.str id: Skill identifier.
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def content(self) -> _builtins.str:
        """
        Skill content.
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Skill identifier.
        """
        return pulumi.get(self, "id")


@pulumi.output_type
class IncidentPipelineAlertSource(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "monitorMode":
            suggest = "monitor_mode"
        elif key == "externalMonitorId":
            suggest = "external_monitor_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IncidentPipelineAlertSource. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IncidentPipelineAlertSource.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IncidentPipelineAlertSource.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 monitor_mode: _builtins.str,
                 provider: _builtins.str,
                 external_monitor_id: Optional[_builtins.str] = None):
        """
        :param _builtins.str monitor_mode: How the pipeline binds to the provider's monitor. One of `create_catchall`, `link_existing`.
        :param _builtins.str provider: Alert provider. One of `datadog`, `grafana`, `alertmanager`, `pagerduty`, `opsgenie`, `generic`.
        :param _builtins.str external_monitor_id: External monitor identifier to link when `monitor_mode = link_existing`.
        """
        pulumi.set(__self__, "monitor_mode", monitor_mode)
        pulumi.set(__self__, "provider", provider)
        if external_monitor_id is not None:
            pulumi.set(__self__, "external_monitor_id", external_monitor_id)

    @_builtins.property
    @pulumi.getter(name="monitorMode")
    def monitor_mode(self) -> _builtins.str:
        """
        How the pipeline binds to the provider's monitor. One of `create_catchall`, `link_existing`.
        """
        return pulumi.get(self, "monitor_mode")

    @_builtins.property
    @pulumi.getter
    def provider(self) -> _builtins.str:
        """
        Alert provider. One of `datadog`, `grafana`, `alertmanager`, `pagerduty`, `opsgenie`, `generic`.
        """
        return pulumi.get(self, "provider")

    @_builtins.property
    @pulumi.getter(name="externalMonitorId")
    def external_monitor_id(self) -> Optional[_builtins.str]:
        """
        External monitor identifier to link when `monitor_mode = link_existing`.
        """
        return pulumi.get(self, "external_monitor_id")


@pulumi.output_type
class IncidentPipelineDeliveryConfig(dict):
    def __init__(__self__, *,
                 slack: Optional['outputs.IncidentPipelineDeliveryConfigSlack'] = None):
        """
        :param 'IncidentPipelineDeliveryConfigSlackArgs' slack: Slack delivery target.
        """
        if slack is not None:
            pulumi.set(__self__, "slack", slack)

    @_builtins.property
    @pulumi.getter
    def slack(self) -> Optional['outputs.IncidentPipelineDeliveryConfigSlack']:
        """
        Slack delivery target.
        """
        return pulumi.get(self, "slack")


@pulumi.output_type
class IncidentPipelineDeliveryConfigSlack(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "channelId":
            suggest = "channel_id"
        elif key == "channelName":
            suggest = "channel_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IncidentPipelineDeliveryConfigSlack. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IncidentPipelineDeliveryConfigSlack.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IncidentPipelineDeliveryConfigSlack.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 channel_id: _builtins.str,
                 channel_name: Optional[_builtins.str] = None,
                 enabled: Optional[_builtins.bool] = None):
        """
        :param _builtins.str channel_id: Slack channel ID to post to.
        :param _builtins.str channel_name: Slack channel name. Resolved by the server when omitted.
        :param _builtins.bool enabled: Whether Slack delivery is enabled.
        """
        pulumi.set(__self__, "channel_id", channel_id)
        if channel_name is not None:
            pulumi.set(__self__, "channel_name", channel_name)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> _builtins.str:
        """
        Slack channel ID to post to.
        """
        return pulumi.get(self, "channel_id")

    @_builtins.property
    @pulumi.getter(name="channelName")
    def channel_name(self) -> Optional[_builtins.str]:
        """
        Slack channel name. Resolved by the server when omitted.
        """
        return pulumi.get(self, "channel_name")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        Whether Slack delivery is enabled.
        """
        return pulumi.get(self, "enabled")


@pulumi.output_type
class IncidentPipelineOrchestratorBinding(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "agentId":
            suggest = "agent_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IncidentPipelineOrchestratorBinding. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IncidentPipelineOrchestratorBinding.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IncidentPipelineOrchestratorBinding.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 agent_id: _builtins.str):
        """
        :param _builtins.str agent_id: ID of the orchestrator agent.
        """
        pulumi.set(__self__, "agent_id", agent_id)

    @_builtins.property
    @pulumi.getter(name="agentId")
    def agent_id(self) -> _builtins.str:
        """
        ID of the orchestrator agent.
        """
        return pulumi.get(self, "agent_id")


@pulumi.output_type
class IncidentPipelineRoutingRule(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "missingFieldDefault":
            suggest = "missing_field_default"
        elif key == "routeAll":
            suggest = "route_all"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IncidentPipelineRoutingRule. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IncidentPipelineRoutingRule.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IncidentPipelineRoutingRule.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 environment: Optional[_builtins.str] = None,
                 missing_field_default: Optional[_builtins.bool] = None,
                 route_all: Optional[_builtins.bool] = None,
                 service: Optional[_builtins.str] = None,
                 severity: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param _builtins.str environment: Only route incidents from this environment.
        :param _builtins.bool missing_field_default: Whether an incident missing a filtered field is routed.
        :param _builtins.bool route_all: Route every incident, ignoring the filters below.
        :param _builtins.str service: Only route incidents for this service.
        :param _builtins.str severity: Only route incidents at this severity.
        :param Mapping[str, _builtins.str] tags: Only route incidents matching these tag key/value pairs.
        """
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if missing_field_default is not None:
            pulumi.set(__self__, "missing_field_default", missing_field_default)
        if route_all is not None:
            pulumi.set(__self__, "route_all", route_all)
        if service is not None:
            pulumi.set(__self__, "service", service)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> Optional[_builtins.str]:
        """
        Only route incidents from this environment.
        """
        return pulumi.get(self, "environment")

    @_builtins.property
    @pulumi.getter(name="missingFieldDefault")
    def missing_field_default(self) -> Optional[_builtins.bool]:
        """
        Whether an incident missing a filtered field is routed.
        """
        return pulumi.get(self, "missing_field_default")

    @_builtins.property
    @pulumi.getter(name="routeAll")
    def route_all(self) -> Optional[_builtins.bool]:
        """
        Route every incident, ignoring the filters below.
        """
        return pulumi.get(self, "route_all")

    @_builtins.property
    @pulumi.getter
    def service(self) -> Optional[_builtins.str]:
        """
        Only route incidents for this service.
        """
        return pulumi.get(self, "service")

    @_builtins.property
    @pulumi.getter
    def severity(self) -> Optional[_builtins.str]:
        """
        Only route incidents at this severity.
        """
        return pulumi.get(self, "severity")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Only route incidents matching these tag key/value pairs.
        """
        return pulumi.get(self, "tags")


@pulumi.output_type
class IncidentPipelineSpecialistBinding(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "agentId":
            suggest = "agent_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in IncidentPipelineSpecialistBinding. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        IncidentPipelineSpecialistBinding.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        IncidentPipelineSpecialistBinding.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 agent_id: _builtins.str,
                 enabled: _builtins.bool,
                 role: _builtins.str):
        """
        :param _builtins.str agent_id: ID of the specialist agent.
        :param _builtins.bool enabled: Whether the specialist is enabled.
        :param _builtins.str role: Role the specialist plays in the pipeline.
        """
        pulumi.set(__self__, "agent_id", agent_id)
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "role", role)

    @_builtins.property
    @pulumi.getter(name="agentId")
    def agent_id(self) -> _builtins.str:
        """
        ID of the specialist agent.
        """
        return pulumi.get(self, "agent_id")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Whether the specialist is enabled.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def role(self) -> _builtins.str:
        """
        Role the specialist plays in the pipeline.
        """
        return pulumi.get(self, "role")


@pulumi.output_type
class OutpostAllowlist(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "pathPrefix":
            suggest = "path_prefix"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in OutpostAllowlist. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        OutpostAllowlist.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        OutpostAllowlist.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 host: _builtins.str,
                 port: _builtins.int,
                 scheme: _builtins.str,
                 path_prefix: Optional[_builtins.str] = None):
        """
        :param _builtins.str host: Hostname or IP address.
        :param _builtins.int port: Port number.
        :param _builtins.str scheme: URL scheme (`http` or `https`).
        :param _builtins.str path_prefix: Optional path prefix.
        """
        pulumi.set(__self__, "host", host)
        pulumi.set(__self__, "port", port)
        pulumi.set(__self__, "scheme", scheme)
        if path_prefix is not None:
            pulumi.set(__self__, "path_prefix", path_prefix)

    @_builtins.property
    @pulumi.getter
    def host(self) -> _builtins.str:
        """
        Hostname or IP address.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def port(self) -> _builtins.int:
        """
        Port number.
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter
    def scheme(self) -> _builtins.str:
        """
        URL scheme (`http` or `https`).
        """
        return pulumi.get(self, "scheme")

    @_builtins.property
    @pulumi.getter(name="pathPrefix")
    def path_prefix(self) -> Optional[_builtins.str]:
        """
        Optional path prefix.
        """
        return pulumi.get(self, "path_prefix")


@pulumi.output_type
class ReviewWorkflowManualSetup(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "contentType":
            suggest = "content_type"
        elif key == "repoName":
            suggest = "repo_name"
        elif key == "repoOwner":
            suggest = "repo_owner"
        elif key == "webhookUrl":
            suggest = "webhook_url"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ReviewWorkflowManualSetup. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ReviewWorkflowManualSetup.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ReviewWorkflowManualSetup.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 content_type: Optional[_builtins.str] = None,
                 events: Optional[Sequence[_builtins.str]] = None,
                 repo_name: Optional[_builtins.str] = None,
                 repo_owner: Optional[_builtins.str] = None,
                 secret: Optional[_builtins.str] = None,
                 webhook_url: Optional[_builtins.str] = None):
        """
        :param _builtins.str content_type: Webhook content type to configure.
        :param Sequence[_builtins.str] events: GitHub events the webhook should send.
        :param _builtins.str repo_name: GitHub repository name.
        :param _builtins.str repo_owner: GitHub repository owner.
        :param _builtins.str secret: Webhook signing secret. Sensitive.
        :param _builtins.str webhook_url: Webhook URL to register in GitHub.
        """
        if content_type is not None:
            pulumi.set(__self__, "content_type", content_type)
        if events is not None:
            pulumi.set(__self__, "events", events)
        if repo_name is not None:
            pulumi.set(__self__, "repo_name", repo_name)
        if repo_owner is not None:
            pulumi.set(__self__, "repo_owner", repo_owner)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if webhook_url is not None:
            pulumi.set(__self__, "webhook_url", webhook_url)

    @_builtins.property
    @pulumi.getter(name="contentType")
    def content_type(self) -> Optional[_builtins.str]:
        """
        Webhook content type to configure.
        """
        return pulumi.get(self, "content_type")

    @_builtins.property
    @pulumi.getter
    def events(self) -> Optional[Sequence[_builtins.str]]:
        """
        GitHub events the webhook should send.
        """
        return pulumi.get(self, "events")

    @_builtins.property
    @pulumi.getter(name="repoName")
    def repo_name(self) -> Optional[_builtins.str]:
        """
        GitHub repository name.
        """
        return pulumi.get(self, "repo_name")

    @_builtins.property
    @pulumi.getter(name="repoOwner")
    def repo_owner(self) -> Optional[_builtins.str]:
        """
        GitHub repository owner.
        """
        return pulumi.get(self, "repo_owner")

    @_builtins.property
    @pulumi.getter
    def secret(self) -> Optional[_builtins.str]:
        """
        Webhook signing secret. Sensitive.
        """
        return pulumi.get(self, "secret")

    @_builtins.property
    @pulumi.getter(name="webhookUrl")
    def webhook_url(self) -> Optional[_builtins.str]:
        """
        Webhook URL to register in GitHub.
        """
        return pulumi.get(self, "webhook_url")


@pulumi.output_type
class ReviewWorkflowRepo(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "repoName":
            suggest = "repo_name"
        elif key == "repoOwner":
            suggest = "repo_owner"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ReviewWorkflowRepo. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ReviewWorkflowRepo.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ReviewWorkflowRepo.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 repo_name: _builtins.str,
                 repo_owner: _builtins.str):
        """
        :param _builtins.str repo_name: GitHub repository name.
        :param _builtins.str repo_owner: GitHub repository owner (user or organization).
        """
        pulumi.set(__self__, "repo_name", repo_name)
        pulumi.set(__self__, "repo_owner", repo_owner)

    @_builtins.property
    @pulumi.getter(name="repoName")
    def repo_name(self) -> _builtins.str:
        """
        GitHub repository name.
        """
        return pulumi.get(self, "repo_name")

    @_builtins.property
    @pulumi.getter(name="repoOwner")
    def repo_owner(self) -> _builtins.str:
        """
        GitHub repository owner (user or organization).
        """
        return pulumi.get(self, "repo_owner")


@pulumi.output_type
class ReviewWorkflowRepoStatus(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "githubHookId":
            suggest = "github_hook_id"
        elif key == "repoName":
            suggest = "repo_name"
        elif key == "repoOwner":
            suggest = "repo_owner"
        elif key == "webhookError":
            suggest = "webhook_error"
        elif key == "webhookStatus":
            suggest = "webhook_status"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ReviewWorkflowRepoStatus. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ReviewWorkflowRepoStatus.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ReviewWorkflowRepoStatus.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 github_hook_id: Optional[_builtins.int] = None,
                 repo_name: Optional[_builtins.str] = None,
                 repo_owner: Optional[_builtins.str] = None,
                 webhook_error: Optional[_builtins.str] = None,
                 webhook_status: Optional[_builtins.str] = None):
        """
        :param _builtins.int github_hook_id: GitHub webhook ID, when provisioned.
        :param _builtins.str repo_name: GitHub repository name.
        :param _builtins.str repo_owner: GitHub repository owner.
        :param _builtins.str webhook_error: Webhook provisioning error, when failed.
        :param _builtins.str webhook_status: Webhook provisioning status.
        """
        if github_hook_id is not None:
            pulumi.set(__self__, "github_hook_id", github_hook_id)
        if repo_name is not None:
            pulumi.set(__self__, "repo_name", repo_name)
        if repo_owner is not None:
            pulumi.set(__self__, "repo_owner", repo_owner)
        if webhook_error is not None:
            pulumi.set(__self__, "webhook_error", webhook_error)
        if webhook_status is not None:
            pulumi.set(__self__, "webhook_status", webhook_status)

    @_builtins.property
    @pulumi.getter(name="githubHookId")
    def github_hook_id(self) -> Optional[_builtins.int]:
        """
        GitHub webhook ID, when provisioned.
        """
        return pulumi.get(self, "github_hook_id")

    @_builtins.property
    @pulumi.getter(name="repoName")
    def repo_name(self) -> Optional[_builtins.str]:
        """
        GitHub repository name.
        """
        return pulumi.get(self, "repo_name")

    @_builtins.property
    @pulumi.getter(name="repoOwner")
    def repo_owner(self) -> Optional[_builtins.str]:
        """
        GitHub repository owner.
        """
        return pulumi.get(self, "repo_owner")

    @_builtins.property
    @pulumi.getter(name="webhookError")
    def webhook_error(self) -> Optional[_builtins.str]:
        """
        Webhook provisioning error, when failed.
        """
        return pulumi.get(self, "webhook_error")

    @_builtins.property
    @pulumi.getter(name="webhookStatus")
    def webhook_status(self) -> Optional[_builtins.str]:
        """
        Webhook provisioning status.
        """
        return pulumi.get(self, "webhook_status")


@pulumi.output_type
class GetCapabilitiesCapabilityResult(dict):
    def __init__(__self__, *,
                 allows: _builtins.str,
                 domain: _builtins.str,
                 key: _builtins.str,
                 sensitivity: _builtins.str):
        """
        :param _builtins.str allows: The action this capability allows.
        :param _builtins.str domain: The domain the capability belongs to.
        :param _builtins.str key: The capability key.
        :param _builtins.str sensitivity: The sensitivity level of the capability.
        """
        pulumi.set(__self__, "allows", allows)
        pulumi.set(__self__, "domain", domain)
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "sensitivity", sensitivity)

    @_builtins.property
    @pulumi.getter
    def allows(self) -> _builtins.str:
        """
        The action this capability allows.
        """
        return pulumi.get(self, "allows")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> _builtins.str:
        """
        The domain the capability belongs to.
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        """
        The capability key.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def sensitivity(self) -> _builtins.str:
        """
        The sensitivity level of the capability.
        """
        return pulumi.get(self, "sensitivity")


@pulumi.output_type
class GetIntegrationCatalogEntryResult(dict):
    def __init__(__self__, *,
                 auth_config_key: _builtins.str,
                 auth_mode: _builtins.str,
                 available: _builtins.bool,
                 capabilities: Sequence[_builtins.str],
                 category: _builtins.str,
                 description: _builtins.str,
                 docs_url: _builtins.str,
                 logo_url: _builtins.str,
                 name: _builtins.str,
                 provider: _builtins.str):
        """
        :param _builtins.str auth_config_key: Auth configuration key.
        :param _builtins.str auth_mode: Authentication mode.
        :param _builtins.bool available: Whether the integration is available.
        :param Sequence[_builtins.str] capabilities: Capabilities the integration provides.
        :param _builtins.str category: Category.
        :param _builtins.str description: Description.
        :param _builtins.str docs_url: Documentation URL.
        :param _builtins.str logo_url: Logo URL.
        :param _builtins.str name: Display name.
        :param _builtins.str provider: Integration provider key.
        """
        pulumi.set(__self__, "auth_config_key", auth_config_key)
        pulumi.set(__self__, "auth_mode", auth_mode)
        pulumi.set(__self__, "available", available)
        pulumi.set(__self__, "capabilities", capabilities)
        pulumi.set(__self__, "category", category)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "docs_url", docs_url)
        pulumi.set(__self__, "logo_url", logo_url)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "provider", provider)

    @_builtins.property
    @pulumi.getter(name="authConfigKey")
    def auth_config_key(self) -> _builtins.str:
        """
        Auth configuration key.
        """
        return pulumi.get(self, "auth_config_key")

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> _builtins.str:
        """
        Authentication mode.
        """
        return pulumi.get(self, "auth_mode")

    @_builtins.property
    @pulumi.getter
    def available(self) -> _builtins.bool:
        """
        Whether the integration is available.
        """
        return pulumi.get(self, "available")

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> Sequence[_builtins.str]:
        """
        Capabilities the integration provides.
        """
        return pulumi.get(self, "capabilities")

    @_builtins.property
    @pulumi.getter
    def category(self) -> _builtins.str:
        """
        Category.
        """
        return pulumi.get(self, "category")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="docsUrl")
    def docs_url(self) -> _builtins.str:
        """
        Documentation URL.
        """
        return pulumi.get(self, "docs_url")

    @_builtins.property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> _builtins.str:
        """
        Logo URL.
        """
        return pulumi.get(self, "logo_url")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Display name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def provider(self) -> _builtins.str:
        """
        Integration provider key.
        """
        return pulumi.get(self, "provider")


@pulumi.output_type
class GetResourceTypesResourceTypeResult(dict):
    def __init__(__self__, *,
                 key: _builtins.str,
                 notes: _builtins.str,
                 scope: _builtins.str):
        """
        :param _builtins.str key: The resource type key.
        :param _builtins.str notes: Notes describing the resource type.
        :param _builtins.str scope: The scope of the resource type.
        """
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "notes", notes)
        pulumi.set(__self__, "scope", scope)

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        """
        The resource type key.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def notes(self) -> _builtins.str:
        """
        Notes describing the resource type.
        """
        return pulumi.get(self, "notes")

    @_builtins.property
    @pulumi.getter
    def scope(self) -> _builtins.str:
        """
        The scope of the resource type.
        """
        return pulumi.get(self, "scope")


@pulumi.output_type
class GetReviewersReviewerResult(dict):
    def __init__(__self__, *,
                 agent_id: _builtins.str,
                 description: _builtins.str,
                 findings30d: _builtins.int,
                 is_builtin: _builtins.bool,
                 last_review_at: _builtins.str,
                 name: _builtins.str,
                 reviews30d: _builtins.int,
                 workflow_count: _builtins.int):
        """
        :param _builtins.str agent_id: Reviewer agent identifier.
        :param _builtins.str description: Description.
        :param _builtins.int findings30d: Findings raised in the last 30 days.
        :param _builtins.bool is_builtin: Whether this is a built-in reviewer.
        :param _builtins.str last_review_at: Timestamp of the most recent review.
        :param _builtins.str name: Display name.
        :param _builtins.int reviews30d: Reviews performed in the last 30 days.
        :param _builtins.int workflow_count: Number of workflows using this reviewer.
        """
        pulumi.set(__self__, "agent_id", agent_id)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "findings30d", findings30d)
        pulumi.set(__self__, "is_builtin", is_builtin)
        pulumi.set(__self__, "last_review_at", last_review_at)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "reviews30d", reviews30d)
        pulumi.set(__self__, "workflow_count", workflow_count)

    @_builtins.property
    @pulumi.getter(name="agentId")
    def agent_id(self) -> _builtins.str:
        """
        Reviewer agent identifier.
        """
        return pulumi.get(self, "agent_id")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def findings30d(self) -> _builtins.int:
        """
        Findings raised in the last 30 days.
        """
        return pulumi.get(self, "findings30d")

    @_builtins.property
    @pulumi.getter(name="isBuiltin")
    def is_builtin(self) -> _builtins.bool:
        """
        Whether this is a built-in reviewer.
        """
        return pulumi.get(self, "is_builtin")

    @_builtins.property
    @pulumi.getter(name="lastReviewAt")
    def last_review_at(self) -> _builtins.str:
        """
        Timestamp of the most recent review.
        """
        return pulumi.get(self, "last_review_at")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Display name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def reviews30d(self) -> _builtins.int:
        """
        Reviews performed in the last 30 days.
        """
        return pulumi.get(self, "reviews30d")

    @_builtins.property
    @pulumi.getter(name="workflowCount")
    def workflow_count(self) -> _builtins.int:
        """
        Number of workflows using this reviewer.
        """
        return pulumi.get(self, "workflow_count")


@pulumi.output_type
class GetSkillsSkillResult(dict):
    def __init__(__self__, *,
                 description: _builtins.str,
                 md5: _builtins.str,
                 name: _builtins.str,
                 path: _builtins.str,
                 skill_id: _builtins.str,
                 tags: Sequence[_builtins.str],
                 updated_at: _builtins.str,
                 version: _builtins.str):
        """
        :param _builtins.str description: Description.
        :param _builtins.str md5: MD5 checksum of the skill.
        :param _builtins.str name: Display name.
        :param _builtins.str path: Path of the skill.
        :param _builtins.str skill_id: Skill identifier.
        :param Sequence[_builtins.str] tags: Tags associated with the skill.
        :param _builtins.str updated_at: Timestamp of the last update.
        :param _builtins.str version: Version of the skill.
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "md5", md5)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "path", path)
        pulumi.set(__self__, "skill_id", skill_id)
        pulumi.set(__self__, "tags", tags)
        pulumi.set(__self__, "updated_at", updated_at)
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def md5(self) -> _builtins.str:
        """
        MD5 checksum of the skill.
        """
        return pulumi.get(self, "md5")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Display name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def path(self) -> _builtins.str:
        """
        Path of the skill.
        """
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter(name="skillId")
    def skill_id(self) -> _builtins.str:
        """
        Skill identifier.
        """
        return pulumi.get(self, "skill_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence[_builtins.str]:
        """
        Tags associated with the skill.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        """
        Timestamp of the last update.
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        """
        Version of the skill.
        """
        return pulumi.get(self, "version")


@pulumi.output_type
class GetWorkerCatalogEntryResult(dict):
    def __init__(__self__, *,
                 category: _builtins.str,
                 description: _builtins.str,
                 docs_url: _builtins.str,
                 id: _builtins.str,
                 missing_credentials: Sequence[_builtins.str],
                 name: _builtins.str,
                 ready: _builtins.bool,
                 status: _builtins.str,
                 supports_chat: _builtins.bool,
                 supports_mcp: _builtins.bool,
                 supports_triggers: _builtins.bool):
        """
        :param _builtins.str category: Category.
        :param _builtins.str description: Description.
        :param _builtins.str docs_url: Documentation URL.
        :param _builtins.str id: Catalog entry identifier.
        :param Sequence[_builtins.str] missing_credentials: Credentials that must be supplied before the worker can be deployed.
        :param _builtins.str name: Display name.
        :param _builtins.bool ready: Whether the catalog worker is ready to deploy.
        :param _builtins.str status: Status.
        :param _builtins.bool supports_chat: Whether the worker supports chat.
        :param _builtins.bool supports_mcp: Whether the worker supports MCP.
        :param _builtins.bool supports_triggers: Whether the worker supports triggers.
        """
        pulumi.set(__self__, "category", category)
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "docs_url", docs_url)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "missing_credentials", missing_credentials)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "ready", ready)
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "supports_chat", supports_chat)
        pulumi.set(__self__, "supports_mcp", supports_mcp)
        pulumi.set(__self__, "supports_triggers", supports_triggers)

    @_builtins.property
    @pulumi.getter
    def category(self) -> _builtins.str:
        """
        Category.
        """
        return pulumi.get(self, "category")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="docsUrl")
    def docs_url(self) -> _builtins.str:
        """
        Documentation URL.
        """
        return pulumi.get(self, "docs_url")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Catalog entry identifier.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="missingCredentials")
    def missing_credentials(self) -> Sequence[_builtins.str]:
        """
        Credentials that must be supplied before the worker can be deployed.
        """
        return pulumi.get(self, "missing_credentials")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Display name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def ready(self) -> _builtins.bool:
        """
        Whether the catalog worker is ready to deploy.
        """
        return pulumi.get(self, "ready")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Status.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="supportsChat")
    def supports_chat(self) -> _builtins.bool:
        """
        Whether the worker supports chat.
        """
        return pulumi.get(self, "supports_chat")

    @_builtins.property
    @pulumi.getter(name="supportsMcp")
    def supports_mcp(self) -> _builtins.bool:
        """
        Whether the worker supports MCP.
        """
        return pulumi.get(self, "supports_mcp")

    @_builtins.property
    @pulumi.getter(name="supportsTriggers")
    def supports_triggers(self) -> _builtins.bool:
        """
        Whether the worker supports triggers.
        """
        return pulumi.get(self, "supports_triggers")


