# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PolicyArgs', 'Policy']

@pulumi.input_type
class PolicyArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 grants: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Policy resource.

        :param pulumi.Input[_builtins.str] description: Free-form policy description.
        :param pulumi.Input[_builtins.str] grants: Capability grants attached to the policy, encoded as JSON.
        :param pulumi.Input[_builtins.str] name: Human-readable policy name.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if grants is not None:
            pulumi.set(__self__, "grants", grants)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Free-form policy description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def grants(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Capability grants attached to the policy, encoded as JSON.
        """
        return pulumi.get(self, "grants")

    @grants.setter
    def grants(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "grants", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable policy name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _PolicyState:
    def __init__(__self__, *,
                 builtin: pulumi.Input[Optional[_builtins.bool]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 grants: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Policy resources.

        :param pulumi.Input[_builtins.bool] builtin: Whether the policy is a built-in policy managed by the system.
        :param pulumi.Input[_builtins.str] created_at: Timestamp at which the policy was created.
        :param pulumi.Input[_builtins.str] description: Free-form policy description.
        :param pulumi.Input[_builtins.str] grants: Capability grants attached to the policy, encoded as JSON.
        :param pulumi.Input[_builtins.str] name: Human-readable policy name.
        """
        if builtin is not None:
            pulumi.set(__self__, "builtin", builtin)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if grants is not None:
            pulumi.set(__self__, "grants", grants)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def builtin(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the policy is a built-in policy managed by the system.
        """
        return pulumi.get(self, "builtin")

    @builtin.setter
    def builtin(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "builtin", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timestamp at which the policy was created.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Free-form policy description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def grants(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Capability grants attached to the policy, encoded as JSON.
        """
        return pulumi.get(self, "grants")

    @grants.setter
    def grants(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "grants", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable policy name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.type_token("agentops:index/policy:Policy")
class Policy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 grants: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        An authorization policy: a named collection of capability grants.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_agentops as agentops

        deploy = agentops.Policy("deploy",
            name="deploy-policy",
            description="Grants deploy capabilities",
            grants=json.dumps([{
                "capability": "agent.invoke",
                "resource_type": "agent",
            }]))
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Policies are imported by their id.

        ```sh
        $ pulumi import agentops:index/policy:Policy deploy pol_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Free-form policy description.
        :param pulumi.Input[_builtins.str] grants: Capability grants attached to the policy, encoded as JSON.
        :param pulumi.Input[_builtins.str] name: Human-readable policy name.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[PolicyArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An authorization policy: a named collection of capability grants.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_agentops as agentops

        deploy = agentops.Policy("deploy",
            name="deploy-policy",
            description="Grants deploy capabilities",
            grants=json.dumps([{
                "capability": "agent.invoke",
                "resource_type": "agent",
            }]))
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Policies are imported by their id.

        ```sh
        $ pulumi import agentops:index/policy:Policy deploy pol_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param PolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 grants: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PolicyArgs.__new__(PolicyArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["grants"] = grants
            __props__.__dict__["name"] = name
            __props__.__dict__["builtin"] = None
            __props__.__dict__["created_at"] = None
        super(Policy, __self__).__init__(
            'agentops:index/policy:Policy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            builtin: pulumi.Input[Optional[_builtins.bool]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            grants: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None) -> 'Policy':
        """
        Get an existing Policy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] builtin: Whether the policy is a built-in policy managed by the system.
        :param pulumi.Input[_builtins.str] created_at: Timestamp at which the policy was created.
        :param pulumi.Input[_builtins.str] description: Free-form policy description.
        :param pulumi.Input[_builtins.str] grants: Capability grants attached to the policy, encoded as JSON.
        :param pulumi.Input[_builtins.str] name: Human-readable policy name.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PolicyState.__new__(_PolicyState)

        __props__.__dict__["builtin"] = builtin
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["description"] = description
        __props__.__dict__["grants"] = grants
        __props__.__dict__["name"] = name
        return Policy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def builtin(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the policy is a built-in policy managed by the system.
        """
        return pulumi.get(self, "builtin")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp at which the policy was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Free-form policy description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def grants(self) -> pulumi.Output[_builtins.str]:
        """
        Capability grants attached to the policy, encoded as JSON.
        """
        return pulumi.get(self, "grants")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable policy name.
        """
        return pulumi.get(self, "name")

