# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RoleArgs', 'Role']

@pulumi.input_type
class RoleArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 policy_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Role resource.

        :param pulumi.Input[_builtins.str] description: Free-form role description.
        :param pulumi.Input[_builtins.str] name: Human-readable role name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] policy_ids: Identifiers of the policies attached to this role.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if policy_ids is not None:
            pulumi.set(__self__, "policy_ids", policy_ids)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Free-form role description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable role name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="policyIds")
    def policy_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Identifiers of the policies attached to this role.
        """
        return pulumi.get(self, "policy_ids")

    @policy_ids.setter
    def policy_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "policy_ids", value)


@pulumi.input_type
class _RoleState:
    def __init__(__self__, *,
                 builtin: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 holders: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 policy_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering Role resources.

        :param pulumi.Input[_builtins.bool] builtin: Whether the role is built in and managed by the system.
        :param pulumi.Input[_builtins.str] description: Free-form role description.
        :param pulumi.Input[_builtins.int] holders: Number of holders currently granted this role.
        :param pulumi.Input[_builtins.str] name: Human-readable role name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] policy_ids: Identifiers of the policies attached to this role.
        """
        if builtin is not None:
            pulumi.set(__self__, "builtin", builtin)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if holders is not None:
            pulumi.set(__self__, "holders", holders)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if policy_ids is not None:
            pulumi.set(__self__, "policy_ids", policy_ids)

    @_builtins.property
    @pulumi.getter
    def builtin(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the role is built in and managed by the system.
        """
        return pulumi.get(self, "builtin")

    @builtin.setter
    def builtin(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "builtin", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Free-form role description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def holders(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Number of holders currently granted this role.
        """
        return pulumi.get(self, "holders")

    @holders.setter
    def holders(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "holders", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable role name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="policyIds")
    def policy_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Identifiers of the policies attached to this role.
        """
        return pulumi.get(self, "policy_ids")

    @policy_ids.setter
    def policy_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "policy_ids", value)


@pulumi.type_token("agentops:index/role:Role")
class Role(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 policy_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        An authorization role: a named grouping of policies that can be granted to holders.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_agentops as agentops

        deployer = agentops.Role("deployer",
            name="deployer",
            description="Can deploy and manage agents",
            policy_ids=[deploy["id"]])
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Roles are imported by their id.

        ```sh
        $ pulumi import agentops:index/role:Role deployer role_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Free-form role description.
        :param pulumi.Input[_builtins.str] name: Human-readable role name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] policy_ids: Identifiers of the policies attached to this role.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[RoleArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An authorization role: a named grouping of policies that can be granted to holders.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_agentops as agentops

        deployer = agentops.Role("deployer",
            name="deployer",
            description="Can deploy and manage agents",
            policy_ids=[deploy["id"]])
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Roles are imported by their id.

        ```sh
        $ pulumi import agentops:index/role:Role deployer role_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param RoleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RoleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 policy_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RoleArgs.__new__(RoleArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            __props__.__dict__["policy_ids"] = policy_ids
            __props__.__dict__["builtin"] = None
            __props__.__dict__["holders"] = None
        super(Role, __self__).__init__(
            'agentops:index/role:Role',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            builtin: pulumi.Input[Optional[_builtins.bool]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            holders: pulumi.Input[Optional[_builtins.int]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            policy_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'Role':
        """
        Get an existing Role resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] builtin: Whether the role is built in and managed by the system.
        :param pulumi.Input[_builtins.str] description: Free-form role description.
        :param pulumi.Input[_builtins.int] holders: Number of holders currently granted this role.
        :param pulumi.Input[_builtins.str] name: Human-readable role name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] policy_ids: Identifiers of the policies attached to this role.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RoleState.__new__(_RoleState)

        __props__.__dict__["builtin"] = builtin
        __props__.__dict__["description"] = description
        __props__.__dict__["holders"] = holders
        __props__.__dict__["name"] = name
        __props__.__dict__["policy_ids"] = policy_ids
        return Role(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def builtin(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the role is built in and managed by the system.
        """
        return pulumi.get(self, "builtin")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Free-form role description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def holders(self) -> pulumi.Output[_builtins.int]:
        """
        Number of holders currently granted this role.
        """
        return pulumi.get(self, "holders")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable role name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="policyIds")
    def policy_ids(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Identifiers of the policies attached to this role.
        """
        return pulumi.get(self, "policy_ids")

