# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WorkflowArgs', 'Workflow']

@pulumi.input_type
class WorkflowArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 is_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 steps: pulumi.Input[Optional[_builtins.str]] = None,
                 trigger: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Workflow resource.

        :param pulumi.Input[_builtins.str] description: Free-form description.
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the workflow is active. Defaults to `true`.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Arbitrary key/value labels attached to the workflow.
        :param pulumi.Input[_builtins.str] name: Human-readable workflow name.
        :param pulumi.Input[_builtins.str] steps: Ordered list of workflow steps, encoded as a JSON array (JSON).
        :param pulumi.Input[_builtins.str] trigger: Trigger configuration for the workflow, encoded as a JSON object (JSON).
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_enabled is not None:
            pulumi.set(__self__, "is_enabled", is_enabled)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)
        if trigger is not None:
            pulumi.set(__self__, "trigger", trigger)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Free-form description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the workflow is active. Defaults to `true`.
        """
        return pulumi.get(self, "is_enabled")

    @is_enabled.setter
    def is_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "is_enabled", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Arbitrary key/value labels attached to the workflow.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable workflow name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def steps(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Ordered list of workflow steps, encoded as a JSON array (JSON).
        """
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "steps", value)

    @_builtins.property
    @pulumi.getter
    def trigger(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Trigger configuration for the workflow, encoded as a JSON object (JSON).
        """
        return pulumi.get(self, "trigger")

    @trigger.setter
    def trigger(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "trigger", value)


@pulumi.input_type
class _WorkflowState:
    def __init__(__self__, *,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 is_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 steps: pulumi.Input[Optional[_builtins.str]] = None,
                 trigger: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Workflow resources.

        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] description: Free-form description.
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the workflow is active. Defaults to `true`.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Arbitrary key/value labels attached to the workflow.
        :param pulumi.Input[_builtins.str] name: Human-readable workflow name.
        :param pulumi.Input[_builtins.str] steps: Ordered list of workflow steps, encoded as a JSON array (JSON).
        :param pulumi.Input[_builtins.str] trigger: Trigger configuration for the workflow, encoded as a JSON object (JSON).
        :param pulumi.Input[_builtins.str] updated_at: Last-update timestamp.
        """
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_enabled is not None:
            pulumi.set(__self__, "is_enabled", is_enabled)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if steps is not None:
            pulumi.set(__self__, "steps", steps)
        if trigger is not None:
            pulumi.set(__self__, "trigger", trigger)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Free-form description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the workflow is active. Defaults to `true`.
        """
        return pulumi.get(self, "is_enabled")

    @is_enabled.setter
    def is_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "is_enabled", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Arbitrary key/value labels attached to the workflow.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable workflow name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def steps(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Ordered list of workflow steps, encoded as a JSON array (JSON).
        """
        return pulumi.get(self, "steps")

    @steps.setter
    def steps(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "steps", value)

    @_builtins.property
    @pulumi.getter
    def trigger(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Trigger configuration for the workflow, encoded as a JSON object (JSON).
        """
        return pulumi.get(self, "trigger")

    @trigger.setter
    def trigger(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "trigger", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Last-update timestamp.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("agentops:index/workflow:Workflow")
class Workflow(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 is_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 steps: pulumi.Input[Optional[_builtins.str]] = None,
                 trigger: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A workflow composed of ordered steps and an optional trigger.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_agentops as agentops

        triage = agentops.Workflow("triage",
            name="incident-triage",
            description="Triage inbound incidents",
            is_enabled=True,
            labels={
                "owner": "sre",
            },
            trigger=json.dumps({
                "type": "manual",
            }),
            steps=json.dumps([{
                "id": "step-1",
                "agent_id": "agent_01hxyz",
            }]))
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Workflows are imported by their id.

        ```sh
        $ pulumi import agentops:index/workflow:Workflow triage wf_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Free-form description.
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the workflow is active. Defaults to `true`.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Arbitrary key/value labels attached to the workflow.
        :param pulumi.Input[_builtins.str] name: Human-readable workflow name.
        :param pulumi.Input[_builtins.str] steps: Ordered list of workflow steps, encoded as a JSON array (JSON).
        :param pulumi.Input[_builtins.str] trigger: Trigger configuration for the workflow, encoded as a JSON object (JSON).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[WorkflowArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A workflow composed of ordered steps and an optional trigger.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_agentops as agentops

        triage = agentops.Workflow("triage",
            name="incident-triage",
            description="Triage inbound incidents",
            is_enabled=True,
            labels={
                "owner": "sre",
            },
            trigger=json.dumps({
                "type": "manual",
            }),
            steps=json.dumps([{
                "id": "step-1",
                "agent_id": "agent_01hxyz",
            }]))
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Workflows are imported by their id.

        ```sh
        $ pulumi import agentops:index/workflow:Workflow triage wf_01hxyz
        ```


        :param str resource_name: The name of the resource.
        :param WorkflowArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkflowArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 is_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 steps: pulumi.Input[Optional[_builtins.str]] = None,
                 trigger: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkflowArgs.__new__(WorkflowArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["is_enabled"] = is_enabled
            __props__.__dict__["labels"] = labels
            __props__.__dict__["name"] = name
            __props__.__dict__["steps"] = steps
            __props__.__dict__["trigger"] = trigger
            __props__.__dict__["created_at"] = None
            __props__.__dict__["updated_at"] = None
        super(Workflow, __self__).__init__(
            'agentops:index/workflow:Workflow',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            is_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            steps: pulumi.Input[Optional[_builtins.str]] = None,
            trigger: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None) -> 'Workflow':
        """
        Get an existing Workflow resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_at: Creation timestamp.
        :param pulumi.Input[_builtins.str] description: Free-form description.
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the workflow is active. Defaults to `true`.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Arbitrary key/value labels attached to the workflow.
        :param pulumi.Input[_builtins.str] name: Human-readable workflow name.
        :param pulumi.Input[_builtins.str] steps: Ordered list of workflow steps, encoded as a JSON array (JSON).
        :param pulumi.Input[_builtins.str] trigger: Trigger configuration for the workflow, encoded as a JSON object (JSON).
        :param pulumi.Input[_builtins.str] updated_at: Last-update timestamp.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkflowState.__new__(_WorkflowState)

        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["description"] = description
        __props__.__dict__["is_enabled"] = is_enabled
        __props__.__dict__["labels"] = labels
        __props__.__dict__["name"] = name
        __props__.__dict__["steps"] = steps
        __props__.__dict__["trigger"] = trigger
        __props__.__dict__["updated_at"] = updated_at
        return Workflow(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Creation timestamp.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Free-form description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the workflow is active. Defaults to `true`.
        """
        return pulumi.get(self, "is_enabled")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Arbitrary key/value labels attached to the workflow.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable workflow name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def steps(self) -> pulumi.Output[_builtins.str]:
        """
        Ordered list of workflow steps, encoded as a JSON array (JSON).
        """
        return pulumi.get(self, "steps")

    @_builtins.property
    @pulumi.getter
    def trigger(self) -> pulumi.Output[_builtins.str]:
        """
        Trigger configuration for the workflow, encoded as a JSON object (JSON).
        """
        return pulumi.get(self, "trigger")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Last-update timestamp.
        """
        return pulumi.get(self, "updated_at")

