// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Inputs
{

    public sealed class HostedAgentSkillGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Skill content.
        /// </summary>
        [Input("content", required: true)]
        public Input<string> Content { get; set; } = null!;

        /// <summary>
        /// Skill identifier.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public HostedAgentSkillGetArgs()
        {
        }
        public static new HostedAgentSkillGetArgs Empty => new HostedAgentSkillGetArgs();
    }
}
