// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Inputs
{

    public sealed class HostedAgentImageGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Image pull policy.
        /// </summary>
        [Input("pullPolicy")]
        public Input<string>? PullPolicy { get; set; }

        /// <summary>
        /// Image registry host.
        /// </summary>
        [Input("registry")]
        public Input<string>? Registry { get; set; }

        /// <summary>
        /// Image repository.
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        /// <summary>
        /// Image tag.
        /// </summary>
        [Input("tag")]
        public Input<string>? Tag { get; set; }

        public HostedAgentImageGetArgs()
        {
        }
        public static new HostedAgentImageGetArgs Empty => new HostedAgentImageGetArgs();
    }
}
