// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Inputs
{

    public sealed class OutpostAllowlistGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Hostname or IP address.
        /// </summary>
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        /// <summary>
        /// Optional path prefix.
        /// </summary>
        [Input("pathPrefix")]
        public Input<string>? PathPrefix { get; set; }

        /// <summary>
        /// Port number.
        /// </summary>
        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        /// <summary>
        /// URL scheme (`Http` or `Https`).
        /// </summary>
        [Input("scheme", required: true)]
        public Input<string> Scheme { get; set; } = null!;

        public OutpostAllowlistGetArgs()
        {
        }
        public static new OutpostAllowlistGetArgs Empty => new OutpostAllowlistGetArgs();
    }
}
