// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Agentops.Inputs
{

    public sealed class ReviewWorkflowRepoStatusGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GitHub webhook ID, when provisioned.
        /// </summary>
        [Input("githubHookId")]
        public Input<int>? GithubHookId { get; set; }

        /// <summary>
        /// GitHub repository name.
        /// </summary>
        [Input("repoName")]
        public Input<string>? RepoName { get; set; }

        /// <summary>
        /// GitHub repository owner.
        /// </summary>
        [Input("repoOwner")]
        public Input<string>? RepoOwner { get; set; }

        /// <summary>
        /// Webhook provisioning error, when failed.
        /// </summary>
        [Input("webhookError")]
        public Input<string>? WebhookError { get; set; }

        /// <summary>
        /// Webhook provisioning status.
        /// </summary>
        [Input("webhookStatus")]
        public Input<string>? WebhookStatus { get; set; }

        public ReviewWorkflowRepoStatusGetArgs()
        {
        }
        public static new ReviewWorkflowRepoStatusGetArgs Empty => new ReviewWorkflowRepoStatusGetArgs();
    }
}
