// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A route on an `agentops.Channel` that forwards matching events to a target agent or workflow.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as agentops from "@pulumi/agentops";
 *
 * const deploys = new agentops.ChannelRoute("deploys", {
 *     channelId: alerts.id,
 *     ruleType: "keyword",
 *     targetType: "agent",
 *     targetId: "agent_01hxyz",
 *     priority: 10,
 *     match: JSON.stringify({
 *         keyword: "deploy",
 *     }),
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Channel routes are imported as "channel_id/route_id".
 *
 * ```sh
 * $ pulumi import agentops:index/channelRoute:ChannelRoute deploys chn_01hxyz/rt_01hxyz
 * ```
 */
export class ChannelRoute extends pulumi.CustomResource {
    /**
     * Get an existing ChannelRoute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ChannelRouteState, opts?: pulumi.CustomResourceOptions): ChannelRoute {
        return new ChannelRoute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'agentops:index/channelRoute:ChannelRoute';

    /**
     * Returns true if the given object is an instance of ChannelRoute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChannelRoute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChannelRoute.__pulumiType;
    }

    /**
     * Account that owns the route.
     */
    declare public /*out*/ readonly accountId: pulumi.Output<string>;
    /**
     * ID of the channel this route belongs to. Changing this forces a new route.
     */
    declare public readonly channelId: pulumi.Output<string>;
    /**
     * Creation timestamp.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Input payload template forwarded to the target, as a JSON object.
     */
    declare public readonly input: pulumi.Output<string>;
    /**
     * Whether this is the channel's default route.
     */
    declare public readonly isDefault: pulumi.Output<boolean>;
    /**
     * Whether the route is enabled.
     */
    declare public readonly isEnabled: pulumi.Output<boolean>;
    /**
     * Match criteria for the route, as a JSON object.
     */
    declare public readonly match: pulumi.Output<string>;
    /**
     * Evaluation priority; lower values are evaluated first.
     */
    declare public readonly priority: pulumi.Output<number>;
    /**
     * Match rule type. One of `private`, `channel`, `keyword`, `mention`.
     */
    declare public readonly ruleType: pulumi.Output<string>;
    /**
     * ID of the target agent or workflow.
     */
    declare public readonly targetId: pulumi.Output<string>;
    /**
     * Kind of target the route forwards to (e.g. `agent`, `workflow`).
     */
    declare public readonly targetType: pulumi.Output<string>;
    /**
     * Last-update timestamp.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a ChannelRoute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChannelRouteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ChannelRouteArgs | ChannelRouteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ChannelRouteState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["channelId"] = state?.channelId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["input"] = state?.input;
            resourceInputs["isDefault"] = state?.isDefault;
            resourceInputs["isEnabled"] = state?.isEnabled;
            resourceInputs["match"] = state?.match;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["ruleType"] = state?.ruleType;
            resourceInputs["targetId"] = state?.targetId;
            resourceInputs["targetType"] = state?.targetType;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as ChannelRouteArgs | undefined;
            if (args?.channelId === undefined && !opts.urn) {
                throw new Error("Missing required property 'channelId'");
            }
            if (args?.priority === undefined && !opts.urn) {
                throw new Error("Missing required property 'priority'");
            }
            if (args?.ruleType === undefined && !opts.urn) {
                throw new Error("Missing required property 'ruleType'");
            }
            if (args?.targetId === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetId'");
            }
            if (args?.targetType === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetType'");
            }
            resourceInputs["channelId"] = args?.channelId;
            resourceInputs["input"] = args?.input;
            resourceInputs["isDefault"] = args?.isDefault;
            resourceInputs["isEnabled"] = args?.isEnabled;
            resourceInputs["match"] = args?.match;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["ruleType"] = args?.ruleType;
            resourceInputs["targetId"] = args?.targetId;
            resourceInputs["targetType"] = args?.targetType;
            resourceInputs["accountId"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ChannelRoute.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ChannelRoute resources.
 */
export interface ChannelRouteState {
    /**
     * Account that owns the route.
     */
    accountId?: pulumi.Input<string | undefined>;
    /**
     * ID of the channel this route belongs to. Changing this forces a new route.
     */
    channelId?: pulumi.Input<string | undefined>;
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Input payload template forwarded to the target, as a JSON object.
     */
    input?: pulumi.Input<string | undefined>;
    /**
     * Whether this is the channel's default route.
     */
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the route is enabled.
     */
    isEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Match criteria for the route, as a JSON object.
     */
    match?: pulumi.Input<string | undefined>;
    /**
     * Evaluation priority; lower values are evaluated first.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * Match rule type. One of `private`, `channel`, `keyword`, `mention`.
     */
    ruleType?: pulumi.Input<string | undefined>;
    /**
     * ID of the target agent or workflow.
     */
    targetId?: pulumi.Input<string | undefined>;
    /**
     * Kind of target the route forwards to (e.g. `agent`, `workflow`).
     */
    targetType?: pulumi.Input<string | undefined>;
    /**
     * Last-update timestamp.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ChannelRoute resource.
 */
export interface ChannelRouteArgs {
    /**
     * ID of the channel this route belongs to. Changing this forces a new route.
     */
    channelId: pulumi.Input<string>;
    /**
     * Input payload template forwarded to the target, as a JSON object.
     */
    input?: pulumi.Input<string | undefined>;
    /**
     * Whether this is the channel's default route.
     */
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the route is enabled.
     */
    isEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Match criteria for the route, as a JSON object.
     */
    match?: pulumi.Input<string | undefined>;
    /**
     * Evaluation priority; lower values are evaluated first.
     */
    priority: pulumi.Input<number>;
    /**
     * Match rule type. One of `private`, `channel`, `keyword`, `mention`.
     */
    ruleType: pulumi.Input<string>;
    /**
     * ID of the target agent or workflow.
     */
    targetId: pulumi.Input<string>;
    /**
     * Kind of target the route forwards to (e.g. `agent`, `workflow`).
     */
    targetType: pulumi.Input<string>;
}
