// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An AgentOps integration connection. Connections cannot be updated in place: changing any argument forces a new connection. Credentials are write-only and never returned by the API.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as agentops from "@pulumi/agentops";
 *
 * const github = new agentops.IntegrationConnection("github", {
 *     providerKey: "github",
 *     displayName: "GitHub (org)",
 *     credentials: {
 *         token: githubToken,
 *     },
 *     metadata: JSON.stringify({
 *         org: "komodorio",
 *     }),
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Integration connections are imported by their id.
 *
 * ```sh
 * $ pulumi import agentops:index/integrationConnection:IntegrationConnection github conn_01hxyz
 * ```
 */
export class IntegrationConnection extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationConnection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationConnectionState, opts?: pulumi.CustomResourceOptions): IntegrationConnection {
        return new IntegrationConnection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'agentops:index/integrationConnection:IntegrationConnection';

    /**
     * Returns true if the given object is an instance of IntegrationConnection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationConnection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationConnection.__pulumiType;
    }

    /**
     * Auth configuration key assigned to the connection.
     */
    declare public /*out*/ readonly authConfigKey: pulumi.Output<string>;
    /**
     * Creation timestamp.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Identifier of the principal that created the connection.
     */
    declare public /*out*/ readonly createdBy: pulumi.Output<string>;
    /**
     * Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
     */
    declare public readonly credentials: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Type of credentials backing the connection.
     */
    declare public /*out*/ readonly credentialsType: pulumi.Output<string>;
    /**
     * Human-readable connection name. Changing this forces a new connection.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Provider-side connection identifier.
     */
    declare public /*out*/ readonly externalConnectionId: pulumi.Output<string>;
    /**
     * Timestamp the connection was last used.
     */
    declare public /*out*/ readonly lastUsedAt: pulumi.Output<string>;
    /**
     * Timestamp the connection was last validated.
     */
    declare public /*out*/ readonly lastValidatedAt: pulumi.Output<string>;
    /**
     * Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
     */
    declare public readonly metadata: pulumi.Output<string>;
    /**
     * Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
     */
    declare public readonly providerKey: pulumi.Output<string>;
    /**
     * Scopes granted to the connection.
     */
    declare public /*out*/ readonly scopes: pulumi.Output<string[]>;
    /**
     * Connection status.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Last-update timestamp.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a IntegrationConnection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationConnectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationConnectionArgs | IntegrationConnectionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationConnectionState | undefined;
            resourceInputs["authConfigKey"] = state?.authConfigKey;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["createdBy"] = state?.createdBy;
            resourceInputs["credentials"] = state?.credentials;
            resourceInputs["credentialsType"] = state?.credentialsType;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["externalConnectionId"] = state?.externalConnectionId;
            resourceInputs["lastUsedAt"] = state?.lastUsedAt;
            resourceInputs["lastValidatedAt"] = state?.lastValidatedAt;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["providerKey"] = state?.providerKey;
            resourceInputs["scopes"] = state?.scopes;
            resourceInputs["status"] = state?.status;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as IntegrationConnectionArgs | undefined;
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.providerKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'providerKey'");
            }
            resourceInputs["credentials"] = args?.credentials ? pulumi.secret(args.credentials) : undefined;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["providerKey"] = args?.providerKey;
            resourceInputs["authConfigKey"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["createdBy"] = undefined /*out*/;
            resourceInputs["credentialsType"] = undefined /*out*/;
            resourceInputs["externalConnectionId"] = undefined /*out*/;
            resourceInputs["lastUsedAt"] = undefined /*out*/;
            resourceInputs["lastValidatedAt"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["credentials"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationConnection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationConnection resources.
 */
export interface IntegrationConnectionState {
    /**
     * Auth configuration key assigned to the connection.
     */
    authConfigKey?: pulumi.Input<string | undefined>;
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the principal that created the connection.
     */
    createdBy?: pulumi.Input<string | undefined>;
    /**
     * Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
     */
    credentials?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Type of credentials backing the connection.
     */
    credentialsType?: pulumi.Input<string | undefined>;
    /**
     * Human-readable connection name. Changing this forces a new connection.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Provider-side connection identifier.
     */
    externalConnectionId?: pulumi.Input<string | undefined>;
    /**
     * Timestamp the connection was last used.
     */
    lastUsedAt?: pulumi.Input<string | undefined>;
    /**
     * Timestamp the connection was last validated.
     */
    lastValidatedAt?: pulumi.Input<string | undefined>;
    /**
     * Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
     */
    metadata?: pulumi.Input<string | undefined>;
    /**
     * Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
     */
    providerKey?: pulumi.Input<string | undefined>;
    /**
     * Scopes granted to the connection.
     */
    scopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Connection status.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Last-update timestamp.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationConnection resource.
 */
export interface IntegrationConnectionArgs {
    /**
     * Provider credentials as string key/value pairs. Write-only: never returned by the API, so it is not refreshed after creation. Changing this forces a new connection.
     */
    credentials?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Human-readable connection name. Changing this forces a new connection.
     */
    displayName: pulumi.Input<string>;
    /**
     * Arbitrary connection metadata, encoded as a JSON object (JSON). Changing this forces a new connection.
     */
    metadata?: pulumi.Input<string | undefined>;
    /**
     * Integration provider key (e.g. the catalog provider identifier). Changing this forces a new connection.
     */
    providerKey: pulumi.Input<string>;
}
