// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An AgentOps member. Members cannot be updated in place; changing any argument forces a new member.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as agentops from "@pulumi/agentops";
 *
 * const dev = new agentops.Member("dev", {
 *     email: "dev@example.com",
 *     fullName: "Dev One",
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Members are imported by their principal id.
 *
 * ```sh
 * $ pulumi import agentops:index/member:Member dev mbr_01hxyz
 * ```
 */
export class Member extends pulumi.CustomResource {
    /**
     * Get an existing Member resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MemberState, opts?: pulumi.CustomResourceOptions): Member {
        return new Member(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'agentops:index/member:Member';

    /**
     * Returns true if the given object is an instance of Member.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Member {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Member.__pulumiType;
    }

    /**
     * Creation timestamp.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Human-readable member name.
     */
    declare public /*out*/ readonly displayName: pulumi.Output<string>;
    /**
     * Email address of the member to invite.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Full name of the member.
     */
    declare public readonly fullName: pulumi.Output<string | undefined>;
    /**
     * Timestamp of the member's last login.
     */
    declare public /*out*/ readonly lastLoginAt: pulumi.Output<string>;
    /**
     * Member status.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * User identifier associated with the member.
     */
    declare public /*out*/ readonly userId: pulumi.Output<string>;

    /**
     * Create a Member resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MemberArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MemberArgs | MemberState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MemberState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["email"] = state?.email;
            resourceInputs["fullName"] = state?.fullName;
            resourceInputs["lastLoginAt"] = state?.lastLoginAt;
            resourceInputs["status"] = state?.status;
            resourceInputs["userId"] = state?.userId;
        } else {
            const args = argsOrState as MemberArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["fullName"] = args?.fullName;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["lastLoginAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Member.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Member resources.
 */
export interface MemberState {
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Human-readable member name.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Email address of the member to invite.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Full name of the member.
     */
    fullName?: pulumi.Input<string | undefined>;
    /**
     * Timestamp of the member's last login.
     */
    lastLoginAt?: pulumi.Input<string | undefined>;
    /**
     * Member status.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * User identifier associated with the member.
     */
    userId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Member resource.
 */
export interface MemberArgs {
    /**
     * Email address of the member to invite.
     */
    email: pulumi.Input<string>;
    /**
     * Full name of the member.
     */
    fullName?: pulumi.Input<string | undefined>;
}
