// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Deploys a curated worker from the worker catalog. The server pins the image and derives the customer and credentials from the catalog entry and your account, so you only name the instance — the result is a managed hosted agent. Destroying one archives it first where the account requires that, and waits for the archive to finish before deleting. Deploy-time inputs are write-only (the API does not return them), so out-of-band changes to them are not detected, and changing any of them forces a new deployment. This resource does not support import: the originating `catalogId` and the write-only inputs cannot be recovered from the API.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as agentops from "@pulumi/agentops";
 *
 * // Deploy a curated worker from the catalog. The server pins the image and derives
 * // the customer and credentials, so you only name the instance. Browse available
 * // entries (and their IDs / required credentials) via the agentops_worker_catalog
 * // data source.
 * const all = agentops.getWorkerCatalog({});
 * const k8sTroubleshooter = new agentops.WorkerCatalogDeployment("k8s_troubleshooter", {
 *     catalogId: "k8s-troubleshooter",
 *     agentId: "prod-k8s-troubleshooter",
 *     displayName: "Prod K8s Troubleshooter",
 *     credentialRef: "anthropic-api-key",
 *     integrationConnections: {
 *         aws: "conn_01hxyz",
 *     },
 * });
 * ```
 */
export class WorkerCatalogDeployment extends pulumi.CustomResource {
    /**
     * Get an existing WorkerCatalogDeployment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkerCatalogDeploymentState, opts?: pulumi.CustomResourceOptions): WorkerCatalogDeployment {
        return new WorkerCatalogDeployment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'agentops:index/workerCatalogDeployment:WorkerCatalogDeployment';

    /**
     * Returns true if the given object is an instance of WorkerCatalogDeployment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkerCatalogDeployment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkerCatalogDeployment.__pulumiType;
    }

    /**
     * Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
     */
    declare public readonly agentId: pulumi.Output<string>;
    /**
     * ID of the worker catalog entry to deploy. Changing this forces a new deployment.
     */
    declare public readonly catalogId: pulumi.Output<string>;
    /**
     * Creation timestamp.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
     */
    declare public readonly credentialRef: pulumi.Output<string | undefined>;
    /**
     * Customer/tenant the worker was deployed under, derived by the server.
     */
    declare public /*out*/ readonly customer: pulumi.Output<string>;
    /**
     * Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
     */
    declare public readonly displayName: pulumi.Output<string | undefined>;
    /**
     * Resolved runtime identity of the deployed worker.
     */
    declare public /*out*/ readonly identity: pulumi.Output<string>;
    /**
     * Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
     */
    declare public readonly integrationConnections: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * SHA of the most recent commit to the generated repository.
     */
    declare public /*out*/ readonly lastCommitSha: pulumi.Output<string>;
    /**
     * ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
     */
    declare public readonly mcpGroupId: pulumi.Output<string | undefined>;
    /**
     * Branch of the generated agent repository.
     */
    declare public /*out*/ readonly repoBranch: pulumi.Output<string>;
    /**
     * Name of the generated agent repository.
     */
    declare public /*out*/ readonly repoName: pulumi.Output<string>;
    /**
     * Owner of the generated agent repository.
     */
    declare public /*out*/ readonly repoOwner: pulumi.Output<string>;
    /**
     * Path within the generated agent repository.
     */
    declare public /*out*/ readonly repoPath: pulumi.Output<string>;
    /**
     * Runtime agent ID the deployment registers as.
     */
    declare public /*out*/ readonly runtimeAgentId: pulumi.Output<string>;
    /**
     * Deployment status (`online`, `offline`, `draft`, `deploying`, `deployFailed`).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Last-update timestamp.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Resolved deployment values, as a JSON object.
     */
    declare public /*out*/ readonly values: pulumi.Output<string>;
    /**
     * Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
     */
    declare public readonly waitForOnline: pulumi.Output<boolean | undefined>;
    /**
     * Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
     */
    declare public readonly waitTimeout: pulumi.Output<string | undefined>;

    /**
     * Create a WorkerCatalogDeployment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkerCatalogDeploymentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkerCatalogDeploymentArgs | WorkerCatalogDeploymentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkerCatalogDeploymentState | undefined;
            resourceInputs["agentId"] = state?.agentId;
            resourceInputs["catalogId"] = state?.catalogId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["credentialRef"] = state?.credentialRef;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["identity"] = state?.identity;
            resourceInputs["integrationConnections"] = state?.integrationConnections;
            resourceInputs["lastCommitSha"] = state?.lastCommitSha;
            resourceInputs["mcpGroupId"] = state?.mcpGroupId;
            resourceInputs["repoBranch"] = state?.repoBranch;
            resourceInputs["repoName"] = state?.repoName;
            resourceInputs["repoOwner"] = state?.repoOwner;
            resourceInputs["repoPath"] = state?.repoPath;
            resourceInputs["runtimeAgentId"] = state?.runtimeAgentId;
            resourceInputs["status"] = state?.status;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["values"] = state?.values;
            resourceInputs["waitForOnline"] = state?.waitForOnline;
            resourceInputs["waitTimeout"] = state?.waitTimeout;
        } else {
            const args = argsOrState as WorkerCatalogDeploymentArgs | undefined;
            if (args?.catalogId === undefined && !opts.urn) {
                throw new Error("Missing required property 'catalogId'");
            }
            resourceInputs["agentId"] = args?.agentId;
            resourceInputs["catalogId"] = args?.catalogId;
            resourceInputs["credentialRef"] = args?.credentialRef;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["integrationConnections"] = args?.integrationConnections;
            resourceInputs["mcpGroupId"] = args?.mcpGroupId;
            resourceInputs["waitForOnline"] = args?.waitForOnline;
            resourceInputs["waitTimeout"] = args?.waitTimeout;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["customer"] = undefined /*out*/;
            resourceInputs["identity"] = undefined /*out*/;
            resourceInputs["lastCommitSha"] = undefined /*out*/;
            resourceInputs["repoBranch"] = undefined /*out*/;
            resourceInputs["repoName"] = undefined /*out*/;
            resourceInputs["repoOwner"] = undefined /*out*/;
            resourceInputs["repoPath"] = undefined /*out*/;
            resourceInputs["runtimeAgentId"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["values"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkerCatalogDeployment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WorkerCatalogDeployment resources.
 */
export interface WorkerCatalogDeploymentState {
    /**
     * Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
     */
    agentId?: pulumi.Input<string | undefined>;
    /**
     * ID of the worker catalog entry to deploy. Changing this forces a new deployment.
     */
    catalogId?: pulumi.Input<string | undefined>;
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
     */
    credentialRef?: pulumi.Input<string | undefined>;
    /**
     * Customer/tenant the worker was deployed under, derived by the server.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Resolved runtime identity of the deployed worker.
     */
    identity?: pulumi.Input<string | undefined>;
    /**
     * Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
     */
    integrationConnections?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * SHA of the most recent commit to the generated repository.
     */
    lastCommitSha?: pulumi.Input<string | undefined>;
    /**
     * ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
     */
    mcpGroupId?: pulumi.Input<string | undefined>;
    /**
     * Branch of the generated agent repository.
     */
    repoBranch?: pulumi.Input<string | undefined>;
    /**
     * Name of the generated agent repository.
     */
    repoName?: pulumi.Input<string | undefined>;
    /**
     * Owner of the generated agent repository.
     */
    repoOwner?: pulumi.Input<string | undefined>;
    /**
     * Path within the generated agent repository.
     */
    repoPath?: pulumi.Input<string | undefined>;
    /**
     * Runtime agent ID the deployment registers as.
     */
    runtimeAgentId?: pulumi.Input<string | undefined>;
    /**
     * Deployment status (`online`, `offline`, `draft`, `deploying`, `deployFailed`).
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Last-update timestamp.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * Resolved deployment values, as a JSON object.
     */
    values?: pulumi.Input<string | undefined>;
    /**
     * Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
     */
    waitForOnline?: pulumi.Input<boolean | undefined>;
    /**
     * Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
     */
    waitTimeout?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a WorkerCatalogDeployment resource.
 */
export interface WorkerCatalogDeploymentArgs {
    /**
     * Stable identifier for the deployed instance. Server-assigned when omitted. Changing this forces a new deployment.
     */
    agentId?: pulumi.Input<string | undefined>;
    /**
     * ID of the worker catalog entry to deploy. Changing this forces a new deployment.
     */
    catalogId: pulumi.Input<string>;
    /**
     * Name of the LLM credential the worker runs with. Must be one of the catalog entry's allowed credentials; the server picks the default when omitted. Write-only. Changing this forces a new deployment.
     */
    credentialRef?: pulumi.Input<string | undefined>;
    /**
     * Human-readable name for the deployed worker. Write-only. Changing this forces a new deployment.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Integration connections to bind at deploy time, keyed by the provider the catalog entry requires. Write-only. Changing this forces a new deployment.
     */
    integrationConnections?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * ID of an MCP gateway group to attach. Write-only. Changing this forces a new deployment.
     */
    mcpGroupId?: pulumi.Input<string | undefined>;
    /**
     * Whether create should block until the deployed worker reports `online` (its first heartbeat). Defaults to `true`. Set to `false` to return as soon as the deployment is accepted. A failed cluster-side provision ends the wait as soon as it is observed, reporting the control plane's own reason rather than running out the timeout.
     */
    waitForOnline?: pulumi.Input<boolean | undefined>;
    /**
     * Maximum time to wait for the worker to become `online`, as a Go duration (e.g. `10m`, `90s`). Defaults to `10m`. Only used when `waitForOnline` is `true`.
     */
    waitTimeout?: pulumi.Input<string | undefined>;
}
