// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A workflow composed of ordered steps and an optional trigger.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as agentops from "@pulumi/agentops";
 *
 * const triage = new agentops.Workflow("triage", {
 *     name: "incident-triage",
 *     description: "Triage inbound incidents",
 *     isEnabled: true,
 *     labels: {
 *         owner: "sre",
 *     },
 *     trigger: JSON.stringify({
 *         type: "manual",
 *     }),
 *     steps: JSON.stringify([{
 *         id: "step-1",
 *         agent_id: "agent_01hxyz",
 *     }]),
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Workflows are imported by their id.
 *
 * ```sh
 * $ pulumi import agentops:index/workflow:Workflow triage wf_01hxyz
 * ```
 */
export class Workflow extends pulumi.CustomResource {
    /**
     * Get an existing Workflow resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkflowState, opts?: pulumi.CustomResourceOptions): Workflow {
        return new Workflow(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'agentops:index/workflow:Workflow';

    /**
     * Returns true if the given object is an instance of Workflow.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Workflow {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Workflow.__pulumiType;
    }

    /**
     * Creation timestamp.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Free-form description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Whether the workflow is active. Defaults to `true`.
     */
    declare public readonly isEnabled: pulumi.Output<boolean>;
    /**
     * Arbitrary key/value labels attached to the workflow.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string}>;
    /**
     * Human-readable workflow name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Ordered list of workflow steps, encoded as a JSON array (JSON).
     */
    declare public readonly steps: pulumi.Output<string>;
    /**
     * Trigger configuration for the workflow, encoded as a JSON object (JSON).
     */
    declare public readonly trigger: pulumi.Output<string>;
    /**
     * Last-update timestamp.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a Workflow resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WorkflowArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkflowArgs | WorkflowState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkflowState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["isEnabled"] = state?.isEnabled;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["steps"] = state?.steps;
            resourceInputs["trigger"] = state?.trigger;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as WorkflowArgs | undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["isEnabled"] = args?.isEnabled;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["steps"] = args?.steps;
            resourceInputs["trigger"] = args?.trigger;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Workflow.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Workflow resources.
 */
export interface WorkflowState {
    /**
     * Creation timestamp.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Free-form description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the workflow is active. Defaults to `true`.
     */
    isEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Arbitrary key/value labels attached to the workflow.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Human-readable workflow name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Ordered list of workflow steps, encoded as a JSON array (JSON).
     */
    steps?: pulumi.Input<string | undefined>;
    /**
     * Trigger configuration for the workflow, encoded as a JSON object (JSON).
     */
    trigger?: pulumi.Input<string | undefined>;
    /**
     * Last-update timestamp.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Workflow resource.
 */
export interface WorkflowArgs {
    /**
     * Free-form description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the workflow is active. Defaults to `true`.
     */
    isEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Arbitrary key/value labels attached to the workflow.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Human-readable workflow name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Ordered list of workflow steps, encoded as a JSON array (JSON).
     */
    steps?: pulumi.Input<string | undefined>;
    /**
     * Trigger configuration for the workflow, encoded as a JSON object (JSON).
     */
    trigger?: pulumi.Input<string | undefined>;
}
